// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-organisasjon:Arbeidslokasjon

package organisasjon

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arbeidslokasjon is the FINT administrasjon-organisasjon type Arbeidslokasjon.
//
// Fysisk lokasjon hvor en ansatt har sitt arbeidssted.
type Arbeidslokasjon struct {
	Forretningsadresse  *felleskompleksedatatyper.Adresse            `json:"forretningsadresse,omitempty"`
	Kontaktinformasjon  *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Lokasjonskode       felleskompleksedatatyper.Identifikator       `json:"lokasjonskode"`
	Lokasjonsnavn       *string                                      `json:"lokasjonsnavn,omitempty"`
	Organisasjonsnavn   *string                                      `json:"organisasjonsnavn,omitempty"`
	Organisasjonsnummer *felleskompleksedatatyper.Identifikator      `json:"organisasjonsnummer,omitempty"`
	Postadresse         *felleskompleksedatatyper.Adresse            `json:"postadresse,omitempty"`

	Links ArbeidslokasjonLinks `json:"_links,omitempty"`
}

// ArbeidslokasjonLinks is the typed _links envelope for Arbeidslokasjon.
type ArbeidslokasjonLinks struct {
	Arbeidsforhold []runtime.Link `json:"arbeidsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arbeidslokasjon.
func (l ArbeidslokasjonLinks) ByName(name string) []runtime.Link {
	switch name {
	case "arbeidsforhold":
		return l.Arbeidsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arbeidslokasjon) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arbeidslokasjon) ForEachID(fn func(name, value string) bool) {
	if !fn("lokasjonskode", r.Lokasjonskode.Identifikatorverdi) {
		return
	}
	if r.Organisasjonsnummer != nil && !fn("organisasjonsnummer", r.Organisasjonsnummer.Identifikatorverdi) {
		return
	}
}

// ArbeidslokasjonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArbeidslokasjonIDFieldNames = []string{
	"lokasjonskode",
	"organisasjonsnummer",
}

// IDFieldNames satisfies runtime.Resource.
func (Arbeidslokasjon) IDFieldNames() []string { return ArbeidslokasjonIDFieldNames }

// ArbeidslokasjonRelations is the runtime metadata for Arbeidslokasjon's relations
// (own and inherited, flattened).
var ArbeidslokasjonRelations = []runtime.Relation{
	{
		Name:         "arbeidsforhold",
		Target:       "administrasjon-personal:Arbeidsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidslokasjon",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Arbeidslokasjon) Relations() []runtime.Relation { return ArbeidslokasjonRelations }

func init() {
	runtime.Register("administrasjon-organisasjon:Arbeidslokasjon", func() runtime.Resource { return &Arbeidslokasjon{} })
}
