apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-link-walker-reader
  namespace: fint-core
  labels:
    app.kubernetes.io/name: fint-link-walker-reader
    app.kubernetes.io/instance: fint-link-walker-reader_fintlabs-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-felleskomponent
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs-no
spec:
  orgId: fintlabs.no
  replicas: 1
  port: 8080
  image: ghcr.io/fintlabs/fint-link-walker-reader:3.0.0-rc.18
  database:
    database: fint-core
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
  observability:
    metrics:
      path: /link-walker/actuator/prometheus
      port: "8080"
  probes:
    startup:
      path: /link-walker/actuator/health/liveness
      port: 8080
      failureThreshold: 30
      periodSeconds: 5
      timeoutSeconds: 5
    liveness:
      path: /link-walker/actuator/health/liveness
      port: 8080
      periodSeconds: 30
      timeoutSeconds: 5
    readiness:
      path: /link-walker/actuator/health/readiness
      port: 8080
      periodSeconds: 10
      timeoutSeconds: 5
