// Code generated by fint-model. DO NOT EDIT.
//
// Package runtime is the small, stable foundation imported by every
// generated FINT resource package. It carries shared types (Link,
// Identifikator, Relation) and the Resource interface + dispatch
// registry that a typed reader uses to materialize concrete resources
// from a (component, typeName) pair.
//
// A dynamic JSON walker can use the Relation metadata exposed by each
// generated type without importing the type's package — see
// (Resource).Relations().
package runtime

import "sync"

// Link is the FINT/HAL link object. Generated _links envelopes hold
// slices of Link (one slice per relation).
type Link struct {
	Href         string `json:"href"`
	Verification string `json:"verification,omitempty"`
}

// Identifikator is the FINT identifier value. Carried here (rather than
// in a generated package) so that IDFields() has a stable, package-
// independent return type. Its single field matches the JSON shape used
// by every concrete identifikator-typed attribute in the model.
type Identifikator struct {
	Identifikatorverdi string `json:"identifikatorverdi"`
}

// Relation is the runtime form of a relation entry — the same fields
// the metamodel.json schema carries, structurally compatible.
type Relation struct {
	Name          string         `json:"name"`
	Target        string         `json:"target"`
	Multiplicity  string         `json:"multiplicity"`
	Bidirectional *Bidirectional `json:"bidirectional,omitempty"`
	Deprecated    bool           `json:"deprecated,omitempty"`
}

// Bidirectional describes an inverse-named relation pairing.
type Bidirectional struct {
	IsSource    bool   `json:"isSource"`
	InverseName string `json:"inverseName"`
}

// Resource is satisfied by every generated FINT type. It exposes the
// minimum surface a generic walker / reader needs without reflection.
//
// ForEachID is a zero-allocation visitor over the populated identifier
// fields. fn receives (jsonName, identifikatorverdi) for each populated
// field and returns true to continue, false to stop. IDFieldNames is
// the static list of every identifier field name on the type (in the
// same order ForEachID visits them) — useful when you need the schema
// even if no values are populated.
type Resource interface {
	ForEachID(fn func(name, value string) bool)
	IDFieldNames() []string
	LinksByName(name string) []Link
	Relations() []Relation
}

// Multiplicity constants. Multiplicity strings on Relation are the
// source-of-truth UML form ("1", "0..1", "0..*", "1..*"); these
// constants are convenience handles for switch statements.
const (
	MultiplicityOne        = "1"
	MultiplicityZeroOrOne  = "0..1"
	MultiplicityZeroOrMany = "0..*"
	MultiplicityOneOrMany  = "1..*"
)

// dispatch registry — generated packages register their concrete types
// in init() so that callers can resolve a "component:Name" string back
// into a fresh, empty resource ready for json.Unmarshal.

var (
	dispatchMu sync.RWMutex
	dispatch   = map[string]func() Resource{}
)

// Register binds a "component:TypeName" key to a constructor that
// returns a fresh, zero-valued instance of the resource. Generated
// packages call this from init().
func Register(key string, ctor func() Resource) {
	dispatchMu.Lock()
	defer dispatchMu.Unlock()
	dispatch[key] = ctor
}

// New returns a fresh Resource for the given "component:TypeName" key,
// or nil if no package registered that key.
func New(key string) Resource {
	dispatchMu.RLock()
	defer dispatchMu.RUnlock()
	ctor, ok := dispatch[key]
	if !ok {
		return nil
	}
	return ctor()
}

// Keys returns every registered key. Useful for diagnostics and tests.
func Keys() []string {
	dispatchMu.RLock()
	defer dispatchMu.RUnlock()
	out := make([]string, 0, len(dispatch))
	for k := range dispatch {
		out = append(out, k)
	}
	return out
}
