// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Eksamen

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Eksamen is the FINT utdanning-timeplan type Eksamen.
//
// En eksamen som avholdes på en skole.
type Eksamen struct {
	Beskrivelse      *string                                `json:"beskrivelse,omitempty"`
	Navn             string                                 `json:"navn"`
	Oppmotetidspunkt *time.Time                             `json:"oppmotetidspunkt,omitempty"`
	SystemID         felleskompleksedatatyper.Identifikator `json:"systemId"`
	Tidsrom          felleskompleksedatatyper.Periode       `json:"tidsrom"`

	Links EksamenLinks `json:"_links,omitempty"`
}

// EksamenLinks is the typed _links envelope for Eksamen.
type EksamenLinks struct {
	Eksamensgruppe []runtime.Link `json:"eksamensgruppe,omitempty"`
	Rom            []runtime.Link `json:"rom,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Eksamen.
func (l EksamenLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "rom":
		return l.Rom
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Eksamen) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Eksamen) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EksamenIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EksamenIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Eksamen) IDFieldNames() []string { return EksamenIDFieldNames }

// EksamenRelations is the runtime metadata for Eksamen's relations
// (own and inherited, flattened).
var EksamenRelations = []runtime.Relation{
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "eksamen",
		},
	},
	{
		Name:         "rom",
		Target:       "utdanning-timeplan:Rom",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamen",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Eksamen) Relations() []runtime.Relation { return EksamenRelations }

func init() {
	runtime.Register("utdanning-timeplan:Eksamen", func() runtime.Resource { return &Eksamen{} })
}
