// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Fag

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fag is the FINT utdanning-timeplan type Fag.
//
// Emneområde i utdanning i henhold til læreplanverket.
//
// # Beskrivelse
//
// Utdanning gjennomføres i form av fag. Fag i videregående utdanning har en fagtype og en fagkode. Begge er definert i VIGO og Grep kodeverk.  For føring på vitnemål kan kun fagkoder fastsatt av Utdanningsdirektoratet benyttes.
//
// Fag og fagkoder kan slås opp hos Utdanningsdirektoratet på https://www.udir.no/laring-og-trivsel/lareplanverket/finn-fagkode/
//
// Fagkoder er også beskrevet i [Registreringshåndboken A04](http://regbok.udir.no/35004/3344/35042-1014304.html).
//
// # Fagtyper
//
// Fag grupperes etter  [Rundskriv Udir-01-2017](https://www.udir.no/regelverk-og-tilsyn/finn-regelverk/etter-tema/Innhold-i-opplaringen/udir-01-2017/) og skriv fra Utdanningsdirektoratet om [Føring av vitnemål og kompetansebevis for videregående opplæring i Kunnskapsløftet, pkt 2.5](https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/2-oppsett-av-vitnemal-og-kompetansebevis/#2.5-rekkefolge-for-foring-av-fag-og-fagtyper).
//
// De aktuelle fagtypene i henhold til [Registreringshåndboken A05](http://regbok.udir.no/35004/3344/35042-1014305.html) er:
//
// - Fellesfag
// - Felles programfag
// - Valgfrie programfag
// - Uspesifiserte programfag
// - Yrkesfaglig fordypning
// - Individuell opplæringsplan
//
// # Referanser
//
// * https://www.udir.no/laring-og-trivsel/lareplanverket/
// * https://www.udir.no/utdanningslopet/videregaende-opplaring/
// * http://regbok.udir.no/
// * http://grepwiki.udir.no/
// * https://www.vigo.no/vigokv/index.action
type Fag struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FagLinks `json:"_links,omitempty"`
}

// FagLinks is the typed _links envelope for Fag.
type FagLinks struct {
	Eksamensgruppe      []runtime.Link `json:"eksamensgruppe,omitempty"`
	Faggruppe           []runtime.Link `json:"faggruppe,omitempty"`
	Grepreferanse       []runtime.Link `json:"grepreferanse,omitempty"`
	Programomrade       []runtime.Link `json:"programomrade,omitempty"`
	Skole               []runtime.Link `json:"skole,omitempty"`
	Tilrettelegging     []runtime.Link `json:"tilrettelegging,omitempty"`
	Undervisningsgruppe []runtime.Link `json:"undervisningsgruppe,omitempty"`
	Vigoreferanse       []runtime.Link `json:"vigoreferanse,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fag.
func (l FagLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "faggruppe":
		return l.Faggruppe
	case "grepreferanse":
		return l.Grepreferanse
	case "programomrade":
		return l.Programomrade
	case "skole":
		return l.Skole
	case "tilrettelegging":
		return l.Tilrettelegging
	case "undervisningsgruppe":
		return l.Undervisningsgruppe
	case "vigoreferanse":
		return l.Vigoreferanse
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fag) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fag) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FagIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FagIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fag) IDFieldNames() []string { return FagIDFieldNames }

// FagRelations is the runtime metadata for Fag's relations
// (own and inherited, flattened).
var FagRelations = []runtime.Relation{
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fag",
		},
	},
	{
		Name:         "faggruppe",
		Target:       "utdanning-timeplan:Faggruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fag",
		},
	},
	{
		Name:         "grepreferanse",
		Target:       "utdanning-kodeverk:Grepreferanse",
		Multiplicity: "0..1",
	},
	{
		Name:         "programomrade",
		Target:       "utdanning-utdanningsprogram:Programomrade",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fag",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fag",
		},
	},
	{
		Name:         "tilrettelegging",
		Target:       "utdanning-elev:Elevtilrettelegging",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fag",
		},
	},
	{
		Name:         "undervisningsgruppe",
		Target:       "utdanning-timeplan:Undervisningsgruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fag",
		},
	},
	{
		Name:         "vigoreferanse",
		Target:       "utdanning-kodeverk:Vigoreferanse",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Fag) Relations() []runtime.Relation { return FagRelations }

func init() {
	runtime.Register("utdanning-timeplan:Fag", func() runtime.Resource { return &Fag{} })
}
