// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Faggruppemedlemskap

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Faggruppemedlemskap is the FINT utdanning-timeplan type Faggruppemedlemskap.
//
// Medlemskap i faggruppe.
type Faggruppemedlemskap struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FaggruppemedlemskapLinks `json:"_links,omitempty"`
}

// FaggruppemedlemskapLinks is the typed _links envelope for Faggruppemedlemskap.
type FaggruppemedlemskapLinks struct {
	Elevforhold []runtime.Link `json:"elevforhold,omitempty"`
	Faggruppe   []runtime.Link `json:"faggruppe,omitempty"`
	Fagmerknad  []runtime.Link `json:"fagmerknad,omitempty"`
	Fagstatus   []runtime.Link `json:"fagstatus,omitempty"`
	Varsel      []runtime.Link `json:"varsel,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Faggruppemedlemskap.
func (l FaggruppemedlemskapLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elevforhold":
		return l.Elevforhold
	case "faggruppe":
		return l.Faggruppe
	case "fagmerknad":
		return l.Fagmerknad
	case "fagstatus":
		return l.Fagstatus
	case "varsel":
		return l.Varsel
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Faggruppemedlemskap) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Faggruppemedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FaggruppemedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FaggruppemedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Faggruppemedlemskap) IDFieldNames() []string { return FaggruppemedlemskapIDFieldNames }

// FaggruppemedlemskapRelations is the runtime metadata for Faggruppemedlemskap's relations
// (own and inherited, flattened).
var FaggruppemedlemskapRelations = []runtime.Relation{
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
	},
	{
		Name:         "faggruppe",
		Target:       "utdanning-timeplan:Faggruppe",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "faggruppemedlemskap",
		},
	},
	{
		Name:         "fagmerknad",
		Target:       "utdanning-kodeverk:Fagmerknad",
		Multiplicity: "0..1",
	},
	{
		Name:         "fagstatus",
		Target:       "utdanning-kodeverk:Fagstatus",
		Multiplicity: "0..1",
	},
	{
		Name:         "varsel",
		Target:       "utdanning-elev:Varsel",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "faggruppemedlemskap",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Faggruppemedlemskap) Relations() []runtime.Relation { return FaggruppemedlemskapRelations }

func init() {
	runtime.Register("utdanning-timeplan:Faggruppemedlemskap", func() runtime.Resource { return &Faggruppemedlemskap{} })
}
