// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Rom

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Rom is the FINT utdanning-timeplan type Rom.
//
// Rom hvor timene gjennomføres.
type Rom struct {
	Navn     *string                                `json:"navn,omitempty"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links RomLinks `json:"_links,omitempty"`
}

// RomLinks is the typed _links envelope for Rom.
type RomLinks struct {
	Eksamen []runtime.Link `json:"eksamen,omitempty"`
	Time    []runtime.Link `json:"time,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Rom.
func (l RomLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamen":
		return l.Eksamen
	case "time":
		return l.Time
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Rom) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Rom) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// RomIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var RomIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Rom) IDFieldNames() []string { return RomIDFieldNames }

// RomRelations is the runtime metadata for Rom's relations
// (own and inherited, flattened).
var RomRelations = []runtime.Relation{
	{
		Name:         "eksamen",
		Target:       "utdanning-timeplan:Eksamen",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "rom",
		},
	},
	{
		Name:         "time",
		Target:       "utdanning-timeplan:Time",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "rom",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Rom) Relations() []runtime.Relation { return RomRelations }

func init() {
	runtime.Register("utdanning-timeplan:Rom", func() runtime.Resource { return &Rom{} })
}
