// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Undervisningsgruppe

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Undervisningsgruppe is the FINT utdanning-timeplan type Undervisningsgruppe.
//
// Gruppering av elever som mottar undervisning.
//
// # Beskrivelse
//
// Elever i forskjellige undervisningsgrupper kan ta samme faget.
// Flere fag kan undervises i samme undervisningsgruppe.
// Det kan være flere lærere i en undervisningsgruppe.
//
// Undervisningsgrupper har vanligvis en kode, men denne er lokalt definert, og varierer fra skole til skole, og fra fylke til fylke.
//
// Denne grupperingen omhandler administrering av undervisningen.
//
// Se også [Faggruppe](/docs/timeplan_faggruppe).
type Undervisningsgruppe struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links UndervisningsgruppeLinks `json:"_links,omitempty"`
}

// UndervisningsgruppeLinks is the typed _links envelope for Undervisningsgruppe.
type UndervisningsgruppeLinks struct {
	Fag                  []runtime.Link `json:"fag,omitempty"`
	Gruppemedlemskap     []runtime.Link `json:"gruppemedlemskap,omitempty"`
	Skole                []runtime.Link `json:"skole,omitempty"`
	Skolear              []runtime.Link `json:"skolear,omitempty"`
	Termin               []runtime.Link `json:"termin,omitempty"`
	Time                 []runtime.Link `json:"time,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Undervisningsgruppe.
func (l UndervisningsgruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fag":
		return l.Fag
	case "gruppemedlemskap":
		return l.Gruppemedlemskap
	case "skole":
		return l.Skole
	case "skolear":
		return l.Skolear
	case "termin":
		return l.Termin
	case "time":
		return l.Time
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Undervisningsgruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Undervisningsgruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// UndervisningsgruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var UndervisningsgruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Undervisningsgruppe) IDFieldNames() []string { return UndervisningsgruppeIDFieldNames }

// UndervisningsgruppeRelations is the runtime metadata for Undervisningsgruppe's relations
// (own and inherited, flattened).
var UndervisningsgruppeRelations = []runtime.Relation{
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "1..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "undervisningsgruppe",
		},
	},
	{
		Name:         "gruppemedlemskap",
		Target:       "utdanning-timeplan:Undervisningsgruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "undervisningsgruppe",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "undervisningsgruppe",
		},
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
	{
		Name:         "termin",
		Target:       "utdanning-kodeverk:Termin",
		Multiplicity: "0..*",
	},
	{
		Name:         "time",
		Target:       "utdanning-timeplan:Time",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "undervisningsgruppe",
		},
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "undervisningsgruppe",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Undervisningsgruppe) Relations() []runtime.Relation { return UndervisningsgruppeRelations }

func init() {
	runtime.Register("utdanning-timeplan:Undervisningsgruppe", func() runtime.Resource { return &Undervisningsgruppe{} })
}
