// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-timeplan:Undervisningsgruppemedlemskap

package timeplan

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Undervisningsgruppemedlemskap is the FINT utdanning-timeplan type Undervisningsgruppemedlemskap.
//
// Medlemskap i undervisningsgrupper.
//
// # Beskrivelse
//
// Gruppemedlemskap som knytter sammen elevforhold og undervisningsgrupper.
type Undervisningsgruppemedlemskap struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links UndervisningsgruppemedlemskapLinks `json:"_links,omitempty"`
}

// UndervisningsgruppemedlemskapLinks is the typed _links envelope for Undervisningsgruppemedlemskap.
type UndervisningsgruppemedlemskapLinks struct {
	Elevforhold         []runtime.Link `json:"elevforhold,omitempty"`
	Undervisningsgruppe []runtime.Link `json:"undervisningsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Undervisningsgruppemedlemskap.
func (l UndervisningsgruppemedlemskapLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elevforhold":
		return l.Elevforhold
	case "undervisningsgruppe":
		return l.Undervisningsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Undervisningsgruppemedlemskap) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Undervisningsgruppemedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// UndervisningsgruppemedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var UndervisningsgruppemedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Undervisningsgruppemedlemskap) IDFieldNames() []string {
	return UndervisningsgruppemedlemskapIDFieldNames
}

// UndervisningsgruppemedlemskapRelations is the runtime metadata for Undervisningsgruppemedlemskap's relations
// (own and inherited, flattened).
var UndervisningsgruppemedlemskapRelations = []runtime.Relation{
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "undervisningsgruppemedlemskap",
		},
	},
	{
		Name:         "undervisningsgruppe",
		Target:       "utdanning-timeplan:Undervisningsgruppe",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "gruppemedlemskap",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Undervisningsgruppemedlemskap) Relations() []runtime.Relation {
	return UndervisningsgruppemedlemskapRelations
}

func init() {
	runtime.Register("utdanning-timeplan:Undervisningsgruppemedlemskap", func() runtime.Resource { return &Undervisningsgruppemedlemskap{} })
}
