// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles:Kontaktperson

package felles

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kontaktperson is the FINT felles type Kontaktperson.
//
// Kontaktperson til en person.
//
// # Beskrivelse
//
// Kontaktperson er personer som kan kontaktes dersom det er behov for det.
//
// Kontaktperson kalles også pårørende.
type Kontaktperson struct {
	Kontaktinformasjon *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Navn               *felleskompleksedatatyper.Personnavn         `json:"navn,omitempty"`
	SystemID           felleskompleksedatatyper.Identifikator       `json:"systemId"`
	Type               string                                       `json:"type"`

	Links KontaktpersonLinks `json:"_links,omitempty"`
}

// KontaktpersonLinks is the typed _links envelope for Kontaktperson.
type KontaktpersonLinks struct {
	Kontaktperson []runtime.Link `json:"kontaktperson,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Kontaktperson.
func (l KontaktpersonLinks) ByName(name string) []runtime.Link {
	switch name {
	case "kontaktperson":
		return l.Kontaktperson
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Kontaktperson) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kontaktperson) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KontaktpersonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KontaktpersonIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kontaktperson) IDFieldNames() []string { return KontaktpersonIDFieldNames }

// KontaktpersonRelations is the runtime metadata for Kontaktperson's relations
// (own and inherited, flattened).
var KontaktpersonRelations = []runtime.Relation{
	{
		Name:         "kontaktperson",
		Target:       "felles:Person",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "parorende",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Kontaktperson) Relations() []runtime.Relation { return KontaktpersonRelations }

func init() {
	runtime.Register("felles:Kontaktperson", func() runtime.Resource { return &Kontaktperson{} })
}
