// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles:Person

package felles

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Person is the FINT felles type Person.
//
// # Fysiske private personer
//
// # Beskrivelse
//
// Fysiske personer. Arver felter fra [Aktør](Class:Aktør).
//
// # Eksempler
//
// ## Riktig
//
// * Karl August Haraldsen
//
// ## Feil
//
// * Statsminister
//
// # Referanse
//
// * [Wiki side](https://no.wikipedia.org/wiki/Fysisk_person)
type Person struct {
	Bilde              *string                                      `json:"bilde,omitempty"`
	Bostedsadresse     *felleskompleksedatatyper.Adresse            `json:"bostedsadresse,omitempty"`
	Fodselsdato        *time.Time                                   `json:"fodselsdato,omitempty"`
	Fodselsnummer      felleskompleksedatatyper.Identifikator       `json:"fodselsnummer"`
	Kontaktinformasjon *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Navn               felleskompleksedatatyper.Personnavn          `json:"navn"`
	Postadresse        *felleskompleksedatatyper.Adresse            `json:"postadresse,omitempty"`

	Links PersonLinks `json:"_links,omitempty"`
}

// PersonLinks is the typed _links envelope for Person.
type PersonLinks struct {
	Elev            []runtime.Link `json:"elev,omitempty"`
	Foreldre        []runtime.Link `json:"foreldre,omitempty"`
	Foreldreansvar  []runtime.Link `json:"foreldreansvar,omitempty"`
	Kjonn           []runtime.Link `json:"kjonn,omitempty"`
	Kommune         []runtime.Link `json:"kommune,omitempty"`
	Larling         []runtime.Link `json:"larling,omitempty"`
	Malform         []runtime.Link `json:"malform,omitempty"`
	Morsmal         []runtime.Link `json:"morsmal,omitempty"`
	Otungdom        []runtime.Link `json:"otungdom,omitempty"`
	Parorende       []runtime.Link `json:"parorende,omitempty"`
	Personalressurs []runtime.Link `json:"personalressurs,omitempty"`
	Statsborgerskap []runtime.Link `json:"statsborgerskap,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Person.
func (l PersonLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elev":
		return l.Elev
	case "foreldre":
		return l.Foreldre
	case "foreldreansvar":
		return l.Foreldreansvar
	case "kjonn":
		return l.Kjonn
	case "kommune":
		return l.Kommune
	case "larling":
		return l.Larling
	case "malform":
		return l.Malform
	case "morsmal":
		return l.Morsmal
	case "otungdom":
		return l.Otungdom
	case "parorende":
		return l.Parorende
	case "personalressurs":
		return l.Personalressurs
	case "statsborgerskap":
		return l.Statsborgerskap
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Person) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Person) ForEachID(fn func(name, value string) bool) {
	if !fn("fodselsnummer", r.Fodselsnummer.Identifikatorverdi) {
		return
	}
}

// PersonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersonIDFieldNames = []string{
	"fodselsnummer",
}

// IDFieldNames satisfies runtime.Resource.
func (Person) IDFieldNames() []string { return PersonIDFieldNames }

// PersonRelations is the runtime metadata for Person's relations
// (own and inherited, flattened).
var PersonRelations = []runtime.Relation{
	{
		Name:         "elev",
		Target:       "utdanning-elev:Elev",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "person",
		},
	},
	{
		Name:         "foreldre",
		Target:       "felles:Person",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "foreldreansvar",
		},
	},
	{
		Name:         "foreldreansvar",
		Target:       "felles:Person",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "foreldre",
		},
	},
	{
		Name:         "kjonn",
		Target:       "felles-kodeverk-iso:Kjonn",
		Multiplicity: "0..1",
	},
	{
		Name:         "kommune",
		Target:       "felles-kodeverk:Kommune",
		Multiplicity: "0..1",
	},
	{
		Name:         "larling",
		Target:       "utdanning-larling:Larling",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "person",
		},
	},
	{
		Name:         "malform",
		Target:       "felles-kodeverk-iso:Sprak",
		Multiplicity: "0..1",
	},
	{
		Name:         "morsmal",
		Target:       "felles-kodeverk-iso:Sprak",
		Multiplicity: "0..1",
	},
	{
		Name:         "otungdom",
		Target:       "utdanning-ot:OtUngdom",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "person",
		},
	},
	{
		Name:         "parorende",
		Target:       "felles:Kontaktperson",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "kontaktperson",
		},
	},
	{
		Name:         "personalressurs",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "person",
		},
	},
	{
		Name:         "statsborgerskap",
		Target:       "felles-kodeverk-iso:Landkode",
		Multiplicity: "0..*",
	},
}

// Relations satisfies runtime.Resource.
func (Person) Relations() []runtime.Relation { return PersonRelations }

func init() {
	runtime.Register("felles:Person", func() runtime.Resource { return &Person{} })
}
