// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-basisklasser:Gruppemedlemskap

package basisklasser

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Gruppemedlemskap is the FINT utdanning-basisklasser type Gruppemedlemskap.
//
// # Deltagelse i en gruppe
//
// # Beskrivelse
//
// Knytter sammen et elevforhold og en gruppe. Gjør det mulig å uttrykke gyldighetsperiode for et medlemskap.
type Gruppemedlemskap struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Gruppemedlemskap) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Gruppemedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// GruppemedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var GruppemedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Gruppemedlemskap) IDFieldNames() []string { return GruppemedlemskapIDFieldNames }

// GruppemedlemskapRelations is the runtime metadata for Gruppemedlemskap's relations
// (own and inherited, flattened).
var GruppemedlemskapRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Gruppemedlemskap) Relations() []runtime.Relation { return GruppemedlemskapRelations }

func init() {
	runtime.Register("utdanning-basisklasser:Gruppemedlemskap", func() runtime.Resource { return &Gruppemedlemskap{} })
}
