// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-basisklasser:Gruppe

package basisklasser

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Gruppe is the FINT utdanning-basisklasser type Gruppe.
//
// # En generisk samling av elever og lærere
//
// # Beskrivelse
//
// Gruppe representeres som en spesialisering (se tabell nedenfor).
//
// Grupper knyttes til Utdanningsforhold via Gruppemedlemskap eller direkte relasjoner.
type Gruppe struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Gruppe) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Gruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// GruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var GruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Gruppe) IDFieldNames() []string { return GruppeIDFieldNames }

// GruppeRelations is the runtime metadata for Gruppe's relations
// (own and inherited, flattened).
var GruppeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Gruppe) Relations() []runtime.Relation { return GruppeRelations }

func init() {
	runtime.Register("utdanning-basisklasser:Gruppe", func() runtime.Resource { return &Gruppe{} })
}
