// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:AdministrativEnhet

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// AdministrativEnhet is the FINT arkiv-noark type AdministrativEnhet.
//
// Navn på avdeling, kontor eller annen administrativ enhet som har ansvaret for saksbehandlingen.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 4.2
// * Noark 5 versjon 5.0 metadatakatalog - nr. M086
//
// # Referanser
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type AdministrativEnhet struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Navn              string                                 `json:"navn"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links AdministrativEnhetLinks `json:"_links,omitempty"`
}

// AdministrativEnhetLinks is the typed _links envelope for AdministrativEnhet.
type AdministrativEnhetLinks struct {
	Organisasjonselement []runtime.Link `json:"organisasjonselement,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on AdministrativEnhet.
func (l AdministrativEnhetLinks) ByName(name string) []runtime.Link {
	switch name {
	case "organisasjonselement":
		return l.Organisasjonselement
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r AdministrativEnhet) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r AdministrativEnhet) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// AdministrativEnhetIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AdministrativEnhetIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (AdministrativEnhet) IDFieldNames() []string { return AdministrativEnhetIDFieldNames }

// AdministrativEnhetRelations is the runtime metadata for AdministrativEnhet's relations
// (own and inherited, flattened).
var AdministrativEnhetRelations = []runtime.Relation{
	{
		Name:         "organisasjonselement",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (AdministrativEnhet) Relations() []runtime.Relation { return AdministrativEnhetRelations }

func init() {
	runtime.Register("arkiv-noark:AdministrativEnhet", func() runtime.Resource { return &AdministrativEnhet{} })
}
