// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Arkivressurs

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arkivressurs is the FINT arkiv-noark type Arkivressurs.
//
// Ansatt med rolle og rettigheter innen arkiv.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 4.3
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Arkivressurs struct {
	KildesystemID *felleskompleksedatatyper.Identifikator `json:"kildesystemId,omitempty"`
	SystemID      *felleskompleksedatatyper.Identifikator `json:"systemId,omitempty"`

	Links ArkivressursLinks `json:"_links,omitempty"`
}

// ArkivressursLinks is the typed _links envelope for Arkivressurs.
type ArkivressursLinks struct {
	Autorisasjon    []runtime.Link `json:"autorisasjon,omitempty"`
	Personalressurs []runtime.Link `json:"personalressurs,omitempty"`
	Tilgang         []runtime.Link `json:"tilgang,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arkivressurs.
func (l ArkivressursLinks) ByName(name string) []runtime.Link {
	switch name {
	case "autorisasjon":
		return l.Autorisasjon
	case "personalressurs":
		return l.Personalressurs
	case "tilgang":
		return l.Tilgang
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arkivressurs) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arkivressurs) ForEachID(fn func(name, value string) bool) {
	if r.KildesystemID != nil && !fn("kildesystemId", r.KildesystemID.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ArkivressursIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArkivressursIDFieldNames = []string{
	"kildesystemId",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Arkivressurs) IDFieldNames() []string { return ArkivressursIDFieldNames }

// ArkivressursRelations is the runtime metadata for Arkivressurs's relations
// (own and inherited, flattened).
var ArkivressursRelations = []runtime.Relation{
	{
		Name:         "autorisasjon",
		Target:       "arkiv-noark:Autorisasjon",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "arkivressurs",
		},
	},
	{
		Name:         "personalressurs",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "1",
	},
	{
		Name:         "tilgang",
		Target:       "arkiv-noark:Tilgang",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arkivressurs",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Arkivressurs) Relations() []runtime.Relation { return ArkivressursRelations }

func init() {
	runtime.Register("arkiv-noark:Arkivressurs", func() runtime.Resource { return &Arkivressurs{} })
}
