// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Arkivdel

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arkivdel is the FINT arkiv-noark type Arkivdel.
//
// En vilkårlig definert del av et arkiv. Et arkiv skal kunne deles opp i arkivdeler for å gruppere arkivet etter overordnede kriterier.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.3
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Arkivdel struct {
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`
	Tittel   string                                 `json:"tittel"`

	Links ArkivdelLinks `json:"_links,omitempty"`
}

// ArkivdelLinks is the typed _links envelope for Arkivdel.
type ArkivdelLinks struct {
	Klassifikasjonssystem []runtime.Link `json:"klassifikasjonssystem,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arkivdel.
func (l ArkivdelLinks) ByName(name string) []runtime.Link {
	switch name {
	case "klassifikasjonssystem":
		return l.Klassifikasjonssystem
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arkivdel) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arkivdel) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ArkivdelIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArkivdelIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Arkivdel) IDFieldNames() []string { return ArkivdelIDFieldNames }

// ArkivdelRelations is the runtime metadata for Arkivdel's relations
// (own and inherited, flattened).
var ArkivdelRelations = []runtime.Relation{
	{
		Name:         "klassifikasjonssystem",
		Target:       "arkiv-noark:Klassifikasjonssystem",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "arkivdel",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Arkivdel) Relations() []runtime.Relation { return ArkivdelRelations }

func init() {
	runtime.Register("arkiv-noark:Arkivdel", func() runtime.Resource { return &Arkivdel{} })
}
