// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Avskrivning

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Avskrivning is the FINT arkiv-noark type Avskrivning.
//
// En Journalpost av typen ”inngående dokument” eller ”organinternt dokument for oppfølging” står i restanse inntil de er markert som ferdigbehandlet, eller avskrives. Det følger av arkivforskriften &#167; 10 at avskrivningsmåte skal fremgå av journalen.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard, kapittel 3.4 Avskrivning og saksoppfølging
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Avskrivning struct {
	AvskrevetAv      string    `json:"avskrevetAv"`
	Avskrivningsdato time.Time `json:"avskrivningsdato"`
	Avskrivningsmate string    `json:"avskrivningsmate"`
}

// LinksByName satisfies runtime.Resource.
func (r Avskrivning) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Avskrivning) ForEachID(fn func(name, value string) bool) {
}

// AvskrivningIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AvskrivningIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Avskrivning) IDFieldNames() []string { return AvskrivningIDFieldNames }

// AvskrivningRelations is the runtime metadata for Avskrivning's relations
// (own and inherited, flattened).
var AvskrivningRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Avskrivning) Relations() []runtime.Relation { return AvskrivningRelations }

func init() {
	runtime.Register("arkiv-noark:Avskrivning", func() runtime.Resource { return &Avskrivning{} })
}
