// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Dokumentbeskrivelse

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Dokumentbeskrivelse is the FINT arkiv-noark type Dokumentbeskrivelse.
//
// Den vanligste bruken av <i>dokumentbeskrivelse </i>er for å skille mellom hoveddokument og vedlegg, hvor hoveddokumentet og hvert av vedleggene utgjør hvert sitt enkeltdokument.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.7
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Dokumentbeskrivelse struct {
	Beskrivelse       *string          `json:"beskrivelse,omitempty"`
	Dokumentnummer    *int64           `json:"dokumentnummer,omitempty"`
	Dokumentobjekt    []Dokumentobjekt `json:"dokumentobjekt,omitempty"`
	Forfatter         []string         `json:"forfatter,omitempty"`
	OpprettetDato     *time.Time       `json:"opprettetDato,omitempty"`
	Part              []Part           `json:"part,omitempty"`
	ReferanseArkivdel []string         `json:"referanseArkivdel,omitempty"`
	Skjerming         *Skjerming       `json:"skjerming,omitempty"`
	TilknyttetDato    *time.Time       `json:"tilknyttetDato,omitempty"`
	Tittel            string           `json:"tittel"`

	Links DokumentbeskrivelseLinks `json:"_links,omitempty"`
}

// DokumentbeskrivelseLinks is the typed _links envelope for Dokumentbeskrivelse.
type DokumentbeskrivelseLinks struct {
	DokumentType              []runtime.Link `json:"dokumentType,omitempty"`
	Dokumentstatus            []runtime.Link `json:"dokumentstatus,omitempty"`
	OpprettetAv               []runtime.Link `json:"opprettetAv,omitempty"`
	TilknyttetAv              []runtime.Link `json:"tilknyttetAv,omitempty"`
	TilknyttetRegistreringSom []runtime.Link `json:"tilknyttetRegistreringSom,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Dokumentbeskrivelse.
func (l DokumentbeskrivelseLinks) ByName(name string) []runtime.Link {
	switch name {
	case "dokumentType":
		return l.DokumentType
	case "dokumentstatus":
		return l.Dokumentstatus
	case "opprettetAv":
		return l.OpprettetAv
	case "tilknyttetAv":
		return l.TilknyttetAv
	case "tilknyttetRegistreringSom":
		return l.TilknyttetRegistreringSom
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Dokumentbeskrivelse) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Dokumentbeskrivelse) ForEachID(fn func(name, value string) bool) {
}

// DokumentbeskrivelseIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var DokumentbeskrivelseIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Dokumentbeskrivelse) IDFieldNames() []string { return DokumentbeskrivelseIDFieldNames }

// DokumentbeskrivelseRelations is the runtime metadata for Dokumentbeskrivelse's relations
// (own and inherited, flattened).
var DokumentbeskrivelseRelations = []runtime.Relation{
	{
		Name:         "dokumentType",
		Target:       "arkiv-kodeverk:DokumentType",
		Multiplicity: "1",
	},
	{
		Name:         "dokumentstatus",
		Target:       "arkiv-kodeverk:DokumentStatus",
		Multiplicity: "1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "tilknyttetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "tilknyttetRegistreringSom",
		Target:       "arkiv-kodeverk:TilknyttetRegistreringSom",
		Multiplicity: "1..*",
	},
}

// Relations satisfies runtime.Resource.
func (Dokumentbeskrivelse) Relations() []runtime.Relation { return DokumentbeskrivelseRelations }

func init() {
	runtime.Register("arkiv-noark:Dokumentbeskrivelse", func() runtime.Resource { return &Dokumentbeskrivelse{} })
}
