// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Dokumentfil

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Dokumentfil is the FINT arkiv-noark type Dokumentfil.
//
// Dokumentfila inneholder selve dokumentet. Dersom dokumentet er arkivert i flere versjoner, må vi ha et dokumentobjekt og en dokumentfil for hver versjon.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.7
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Dokumentfil struct {
	Data     string                                 `json:"data"`
	Filnavn  *string                                `json:"filnavn,omitempty"`
	Format   string                                 `json:"format"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Dokumentfil) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Dokumentfil) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// DokumentfilIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var DokumentfilIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Dokumentfil) IDFieldNames() []string { return DokumentfilIDFieldNames }

// DokumentfilRelations is the runtime metadata for Dokumentfil's relations
// (own and inherited, flattened).
var DokumentfilRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Dokumentfil) Relations() []runtime.Relation { return DokumentfilRelations }

func init() {
	runtime.Register("arkiv-noark:Dokumentfil", func() runtime.Resource { return &Dokumentfil{} })
}
