// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Journalpost

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Journalpost is the FINT arkiv-noark type Journalpost.
//
// En journalpost representer en "innføring i journalen". Journalen er en kronologisk fortegnelse over inn- og utgående dokumenter (dvs. korrespondansedokumenter) brukt i saksbehandlingen, og eventuelt også interne dokumenter.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.6
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Journalpost struct {
	AntallVedlegg            *int64                `json:"antallVedlegg,omitempty"`
	ArkivertDato             *time.Time            `json:"arkivertDato,omitempty"`
	Avskrivning              *Avskrivning          `json:"avskrivning,omitempty"`
	Beskrivelse              *string               `json:"beskrivelse,omitempty"`
	Dokumentbeskrivelse      []Dokumentbeskrivelse `json:"dokumentbeskrivelse,omitempty"`
	DokumentetsDato          *time.Time            `json:"dokumentetsDato,omitempty"`
	ForfallsDato             *time.Time            `json:"forfallsDato,omitempty"`
	Forfatter                []string              `json:"forfatter,omitempty"`
	JournalAr                *string               `json:"journalAr,omitempty"`
	JournalDato              *time.Time            `json:"journalDato,omitempty"`
	JournalPostnummer        *int64                `json:"journalPostnummer,omitempty"`
	JournalSekvensnummer     *int64                `json:"journalSekvensnummer,omitempty"`
	Klasse                   *Klasse               `json:"klasse,omitempty"`
	Korrespondansepart       []Korrespondansepart  `json:"korrespondansepart,omitempty"`
	Merknad                  []Merknad             `json:"merknad,omitempty"`
	MottattDato              *time.Time            `json:"mottattDato,omitempty"`
	Nokkelord                []string              `json:"nokkelord,omitempty"`
	OffentligTittel          *string               `json:"offentligTittel,omitempty"`
	OffentlighetsvurdertDato *time.Time            `json:"offentlighetsvurdertDato,omitempty"`
	OpprettetDato            *time.Time            `json:"opprettetDato,omitempty"`
	Part                     []Part                `json:"part,omitempty"`
	ReferanseArkivDel        []string              `json:"referanseArkivDel,omitempty"`
	RegistreringsID          *string               `json:"registreringsId,omitempty"`
	SendtDato                *time.Time            `json:"sendtDato,omitempty"`
	Skjerming                *Skjerming            `json:"skjerming,omitempty"`
	Tittel                   string                `json:"tittel"`

	Links JournalpostLinks `json:"_links,omitempty"`
}

// JournalpostLinks is the typed _links envelope for Journalpost.
type JournalpostLinks struct {
	AdministrativEnhet []runtime.Link `json:"administrativEnhet,omitempty"`
	Arkivdel           []runtime.Link `json:"arkivdel,omitempty"`
	ArkivertAv         []runtime.Link `json:"arkivertAv,omitempty"`
	Journalenhet       []runtime.Link `json:"journalenhet,omitempty"`
	Journalposttype    []runtime.Link `json:"journalposttype,omitempty"`
	Journalstatus      []runtime.Link `json:"journalstatus,omitempty"`
	OpprettetAv        []runtime.Link `json:"opprettetAv,omitempty"`
	Saksbehandler      []runtime.Link `json:"saksbehandler,omitempty"`
	Tilgangsgruppe     []runtime.Link `json:"tilgangsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Journalpost.
func (l JournalpostLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrativEnhet":
		return l.AdministrativEnhet
	case "arkivdel":
		return l.Arkivdel
	case "arkivertAv":
		return l.ArkivertAv
	case "journalenhet":
		return l.Journalenhet
	case "journalposttype":
		return l.Journalposttype
	case "journalstatus":
		return l.Journalstatus
	case "opprettetAv":
		return l.OpprettetAv
	case "saksbehandler":
		return l.Saksbehandler
	case "tilgangsgruppe":
		return l.Tilgangsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Journalpost) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Journalpost) ForEachID(fn func(name, value string) bool) {
}

// JournalpostIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var JournalpostIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Journalpost) IDFieldNames() []string { return JournalpostIDFieldNames }

// JournalpostRelations is the runtime metadata for Journalpost's relations
// (own and inherited, flattened).
var JournalpostRelations = []runtime.Relation{
	{
		Name:         "administrativEnhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivertAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "journalenhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "journalposttype",
		Target:       "arkiv-kodeverk:JournalpostType",
		Multiplicity: "1",
	},
	{
		Name:         "journalstatus",
		Target:       "arkiv-kodeverk:JournalStatus",
		Multiplicity: "1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksbehandler",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "tilgangsgruppe",
		Target:       "arkiv-kodeverk:Tilgangsgruppe",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Journalpost) Relations() []runtime.Relation { return JournalpostRelations }

func init() {
	runtime.Register("arkiv-noark:Journalpost", func() runtime.Resource { return &Journalpost{} })
}
