// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Korrespondansepart

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Korrespondansepart is the FINT arkiv-noark type Korrespondansepart.
//
// Virksomhet eller person som arkivskaper mottar eller sender arkivdokumenter til.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.6
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Korrespondansepart struct {
	Adresse                *felleskompleksedatatyper.Adresse            `json:"adresse,omitempty"`
	Fodselsnummer          *string                                      `json:"fodselsnummer,omitempty"`
	Kontaktinformasjon     *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Kontaktperson          *string                                      `json:"kontaktperson,omitempty"`
	KorrespondansepartNavn *string                                      `json:"korrespondansepartNavn,omitempty"`
	Organisasjonsnummer    *string                                      `json:"organisasjonsnummer,omitempty"`
	Skjerming              *Skjerming                                   `json:"skjerming,omitempty"`

	Links KorrespondansepartLinks `json:"_links,omitempty"`
}

// KorrespondansepartLinks is the typed _links envelope for Korrespondansepart.
type KorrespondansepartLinks struct {
	Korrespondanseparttype []runtime.Link `json:"korrespondanseparttype,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Korrespondansepart.
func (l KorrespondansepartLinks) ByName(name string) []runtime.Link {
	switch name {
	case "korrespondanseparttype":
		return l.Korrespondanseparttype
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Korrespondansepart) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Korrespondansepart) ForEachID(fn func(name, value string) bool) {
}

// KorrespondansepartIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KorrespondansepartIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Korrespondansepart) IDFieldNames() []string { return KorrespondansepartIDFieldNames }

// KorrespondansepartRelations is the runtime metadata for Korrespondansepart's relations
// (own and inherited, flattened).
var KorrespondansepartRelations = []runtime.Relation{
	{
		Name:         "korrespondanseparttype",
		Target:       "arkiv-kodeverk:KorrespondansepartType",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Korrespondansepart) Relations() []runtime.Relation { return KorrespondansepartRelations }

func init() {
	runtime.Register("arkiv-noark:Korrespondansepart", func() runtime.Resource { return &Korrespondansepart{} })
}
