// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Mappe

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Mappe is the FINT arkiv-noark type Mappe.
//
// En mappe grupperer dokumenter som på en eller annen måte hører sammen.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.5
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Mappe struct {
	AvsluttetDato   *time.Time                              `json:"avsluttetDato,omitempty"`
	Beskrivelse     *string                                 `json:"beskrivelse,omitempty"`
	Klasse          []Klasse                                `json:"klasse,omitempty"`
	MappeID         *felleskompleksedatatyper.Identifikator `json:"mappeId,omitempty"`
	Merknad         []Merknad                               `json:"merknad,omitempty"`
	Noekkelord      []string                                `json:"noekkelord,omitempty"`
	OffentligTittel *string                                 `json:"offentligTittel,omitempty"`
	OpprettetDato   *time.Time                              `json:"opprettetDato,omitempty"`
	Part            []Part                                  `json:"part,omitempty"`
	Skjerming       *Skjerming                              `json:"skjerming,omitempty"`
	SystemID        *felleskompleksedatatyper.Identifikator `json:"systemId,omitempty"`
	Tittel          *string                                 `json:"tittel,omitempty"`

	Links MappeLinks `json:"_links,omitempty"`
}

// MappeLinks is the typed _links envelope for Mappe.
type MappeLinks struct {
	Arkivdel    []runtime.Link `json:"arkivdel,omitempty"`
	AvsluttetAv []runtime.Link `json:"avsluttetAv,omitempty"`
	OpprettetAv []runtime.Link `json:"opprettetAv,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Mappe.
func (l MappeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "arkivdel":
		return l.Arkivdel
	case "avsluttetAv":
		return l.AvsluttetAv
	case "opprettetAv":
		return l.OpprettetAv
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Mappe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Mappe) ForEachID(fn func(name, value string) bool) {
	if r.MappeID != nil && !fn("mappeId", r.MappeID.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// MappeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var MappeIDFieldNames = []string{
	"mappeId",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Mappe) IDFieldNames() []string { return MappeIDFieldNames }

// MappeRelations is the runtime metadata for Mappe's relations
// (own and inherited, flattened).
var MappeRelations = []runtime.Relation{
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "avsluttetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Mappe) Relations() []runtime.Relation { return MappeRelations }

func init() {
	runtime.Register("arkiv-noark:Mappe", func() runtime.Resource { return &Mappe{} })
}
