// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Merknad

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Merknad is the FINT arkiv-noark type Merknad.
//
// Merknader knyttet til mappe, registrering eller dokumentbeskrivelse.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.8.4
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Merknad struct {
	Merknadsdato  time.Time `json:"merknadsdato"`
	Merknadstekst string    `json:"merknadstekst"`

	Links MerknadLinks `json:"_links,omitempty"`
}

// MerknadLinks is the typed _links envelope for Merknad.
type MerknadLinks struct {
	MerknadRegistrertAv []runtime.Link `json:"merknadRegistrertAv,omitempty"`
	Merknadstype        []runtime.Link `json:"merknadstype,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Merknad.
func (l MerknadLinks) ByName(name string) []runtime.Link {
	switch name {
	case "merknadRegistrertAv":
		return l.MerknadRegistrertAv
	case "merknadstype":
		return l.Merknadstype
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Merknad) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Merknad) ForEachID(fn func(name, value string) bool) {
}

// MerknadIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var MerknadIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Merknad) IDFieldNames() []string { return MerknadIDFieldNames }

// MerknadRelations is the runtime metadata for Merknad's relations
// (own and inherited, flattened).
var MerknadRelations = []runtime.Relation{
	{
		Name:         "merknadRegistrertAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "merknadstype",
		Target:       "arkiv-kodeverk:Merknadstype",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Merknad) Relations() []runtime.Relation { return MerknadRelations }

func init() {
	runtime.Register("arkiv-noark:Merknad", func() runtime.Resource { return &Merknad{} })
}
