// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Part

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Part is the FINT arkiv-noark type Part.
//
// Part til Mappe, Registrering eller Dokumentbeskrivelse.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.8.5
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Part struct {
	Adresse             *felleskompleksedatatyper.Adresse            `json:"adresse,omitempty"`
	Fodselsnummer       *string                                      `json:"fodselsnummer,omitempty"`
	Kontaktinformasjon  *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Kontaktperson       *string                                      `json:"kontaktperson,omitempty"`
	Organisasjonsnummer *string                                      `json:"organisasjonsnummer,omitempty"`
	PartNavn            string                                       `json:"partNavn"`

	Links PartLinks `json:"_links,omitempty"`
}

// PartLinks is the typed _links envelope for Part.
type PartLinks struct {
	PartRolle []runtime.Link `json:"partRolle,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Part.
func (l PartLinks) ByName(name string) []runtime.Link {
	switch name {
	case "partRolle":
		return l.PartRolle
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Part) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Part) ForEachID(fn func(name, value string) bool) {
}

// PartIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PartIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Part) IDFieldNames() []string { return PartIDFieldNames }

// PartRelations is the runtime metadata for Part's relations
// (own and inherited, flattened).
var PartRelations = []runtime.Relation{
	{
		Name:         "partRolle",
		Target:       "arkiv-kodeverk:PartRolle",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Part) Relations() []runtime.Relation { return PartRelations }

func init() {
	runtime.Register("arkiv-noark:Part", func() runtime.Resource { return &Part{} })
}
