// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Registrering

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Registrering is the FINT arkiv-noark type Registrering.
//
// En registrering utgjør arkivets primære byggeklosser.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.6
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Registrering struct {
	ArkivertDato        *time.Time            `json:"arkivertDato,omitempty"`
	Beskrivelse         *string               `json:"beskrivelse,omitempty"`
	Dokumentbeskrivelse []Dokumentbeskrivelse `json:"dokumentbeskrivelse,omitempty"`
	Forfatter           []string              `json:"forfatter,omitempty"`
	Klasse              *Klasse               `json:"klasse,omitempty"`
	Korrespondansepart  []Korrespondansepart  `json:"korrespondansepart,omitempty"`
	Merknad             []Merknad             `json:"merknad,omitempty"`
	Nokkelord           []string              `json:"nokkelord,omitempty"`
	OffentligTittel     *string               `json:"offentligTittel,omitempty"`
	OpprettetDato       *time.Time            `json:"opprettetDato,omitempty"`
	Part                []Part                `json:"part,omitempty"`
	ReferanseArkivDel   []string              `json:"referanseArkivDel,omitempty"`
	RegistreringsID     *string               `json:"registreringsId,omitempty"`
	Skjerming           *Skjerming            `json:"skjerming,omitempty"`
	Tittel              string                `json:"tittel"`

	Links RegistreringLinks `json:"_links,omitempty"`
}

// RegistreringLinks is the typed _links envelope for Registrering.
type RegistreringLinks struct {
	AdministrativEnhet []runtime.Link `json:"administrativEnhet,omitempty"`
	Arkivdel           []runtime.Link `json:"arkivdel,omitempty"`
	ArkivertAv         []runtime.Link `json:"arkivertAv,omitempty"`
	OpprettetAv        []runtime.Link `json:"opprettetAv,omitempty"`
	Saksbehandler      []runtime.Link `json:"saksbehandler,omitempty"`
	Tilgangsgruppe     []runtime.Link `json:"tilgangsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Registrering.
func (l RegistreringLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrativEnhet":
		return l.AdministrativEnhet
	case "arkivdel":
		return l.Arkivdel
	case "arkivertAv":
		return l.ArkivertAv
	case "opprettetAv":
		return l.OpprettetAv
	case "saksbehandler":
		return l.Saksbehandler
	case "tilgangsgruppe":
		return l.Tilgangsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Registrering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Registrering) ForEachID(fn func(name, value string) bool) {
}

// RegistreringIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var RegistreringIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Registrering) IDFieldNames() []string { return RegistreringIDFieldNames }

// RegistreringRelations is the runtime metadata for Registrering's relations
// (own and inherited, flattened).
var RegistreringRelations = []runtime.Relation{
	{
		Name:         "administrativEnhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivertAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksbehandler",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "tilgangsgruppe",
		Target:       "arkiv-kodeverk:Tilgangsgruppe",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Registrering) Relations() []runtime.Relation { return RegistreringRelations }

func init() {
	runtime.Register("arkiv-noark:Registrering", func() runtime.Resource { return &Registrering{} })
}
