// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Saksmappe

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Saksmappe is the FINT arkiv-noark type Saksmappe.
//
// Spesialisering av Mappe som tilsvarer en ”sak” i Noark.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.5
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Saksmappe struct {
	AvsluttetDato     *time.Time                              `json:"avsluttetDato,omitempty"`
	Beskrivelse       *string                                 `json:"beskrivelse,omitempty"`
	Journalpost       []Journalpost                           `json:"journalpost,omitempty"`
	Klasse            []Klasse                                `json:"klasse,omitempty"`
	MappeID           *felleskompleksedatatyper.Identifikator `json:"mappeId,omitempty"`
	Merknad           []Merknad                               `json:"merknad,omitempty"`
	Noekkelord        []string                                `json:"noekkelord,omitempty"`
	OffentligTittel   *string                                 `json:"offentligTittel,omitempty"`
	OpprettetDato     *time.Time                              `json:"opprettetDato,omitempty"`
	Part              []Part                                  `json:"part,omitempty"`
	Saksaar           *string                                 `json:"saksaar,omitempty"`
	Saksdato          *time.Time                              `json:"saksdato,omitempty"`
	Sakssekvensnummer *string                                 `json:"sakssekvensnummer,omitempty"`
	Skjerming         *Skjerming                              `json:"skjerming,omitempty"`
	SystemID          *felleskompleksedatatyper.Identifikator `json:"systemId,omitempty"`
	Tittel            *string                                 `json:"tittel,omitempty"`
	UtlaantDato       *time.Time                              `json:"utlaantDato,omitempty"`

	Links SaksmappeLinks `json:"_links,omitempty"`
}

// SaksmappeLinks is the typed _links envelope for Saksmappe.
type SaksmappeLinks struct {
	AdministrativEnhet []runtime.Link `json:"administrativEnhet,omitempty"`
	Arkivdel           []runtime.Link `json:"arkivdel,omitempty"`
	AvsluttetAv        []runtime.Link `json:"avsluttetAv,omitempty"`
	Journalenhet       []runtime.Link `json:"journalenhet,omitempty"`
	OpprettetAv        []runtime.Link `json:"opprettetAv,omitempty"`
	Saksansvarlig      []runtime.Link `json:"saksansvarlig,omitempty"`
	Saksmappetype      []runtime.Link `json:"saksmappetype,omitempty"`
	Saksstatus         []runtime.Link `json:"saksstatus,omitempty"`
	Tilgangsgruppe     []runtime.Link `json:"tilgangsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Saksmappe.
func (l SaksmappeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrativEnhet":
		return l.AdministrativEnhet
	case "arkivdel":
		return l.Arkivdel
	case "avsluttetAv":
		return l.AvsluttetAv
	case "journalenhet":
		return l.Journalenhet
	case "opprettetAv":
		return l.OpprettetAv
	case "saksansvarlig":
		return l.Saksansvarlig
	case "saksmappetype":
		return l.Saksmappetype
	case "saksstatus":
		return l.Saksstatus
	case "tilgangsgruppe":
		return l.Tilgangsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Saksmappe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Saksmappe) ForEachID(fn func(name, value string) bool) {
	if r.MappeID != nil && !fn("mappeId", r.MappeID.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SaksmappeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SaksmappeIDFieldNames = []string{
	"mappeId",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Saksmappe) IDFieldNames() []string { return SaksmappeIDFieldNames }

// SaksmappeRelations is the runtime metadata for Saksmappe's relations
// (own and inherited, flattened).
var SaksmappeRelations = []runtime.Relation{
	{
		Name:         "administrativEnhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "1",
	},
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "avsluttetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "journalenhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksansvarlig",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksmappetype",
		Target:       "arkiv-kodeverk:Saksmappetype",
		Multiplicity: "0..1",
	},
	{
		Name:         "saksstatus",
		Target:       "arkiv-kodeverk:Saksstatus",
		Multiplicity: "1",
	},
	{
		Name:         "tilgangsgruppe",
		Target:       "arkiv-kodeverk:Tilgangsgruppe",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Saksmappe) Relations() []runtime.Relation { return SaksmappeRelations }

func init() {
	runtime.Register("arkiv-noark:Saksmappe", func() runtime.Resource { return &Saksmappe{} })
}
