// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Skjerming

package noark

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Skjerming is the FINT arkiv-noark type Skjerming.
//
// Skjerming benyttes til å skjerme registrerte opplysninger eller enkeltdokumenter. Skjermingen trer i kraft når en tilgangskode påføres den enkelte mappe, registrering eller det enkelte dokument.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 2.8.1
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Skjerming struct {
	Links SkjermingLinks `json:"_links,omitempty"`
}

// SkjermingLinks is the typed _links envelope for Skjerming.
type SkjermingLinks struct {
	Skjermingshjemmel   []runtime.Link `json:"skjermingshjemmel,omitempty"`
	Tilgangsrestriksjon []runtime.Link `json:"tilgangsrestriksjon,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Skjerming.
func (l SkjermingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "skjermingshjemmel":
		return l.Skjermingshjemmel
	case "tilgangsrestriksjon":
		return l.Tilgangsrestriksjon
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Skjerming) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Skjerming) ForEachID(fn func(name, value string) bool) {
}

// SkjermingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SkjermingIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Skjerming) IDFieldNames() []string { return SkjermingIDFieldNames }

// SkjermingRelations is the runtime metadata for Skjerming's relations
// (own and inherited, flattened).
var SkjermingRelations = []runtime.Relation{
	{
		Name:         "skjermingshjemmel",
		Target:       "arkiv-kodeverk:Skjermingshjemmel",
		Multiplicity: "1",
	},
	{
		Name:         "tilgangsrestriksjon",
		Target:       "arkiv-kodeverk:Tilgangsrestriksjon",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Skjerming) Relations() []runtime.Relation { return SkjermingRelations }

func init() {
	runtime.Register("arkiv-noark:Skjerming", func() runtime.Resource { return &Skjerming{} })
}
