// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-noark:Tilgang

package noark

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Tilgang is the FINT arkiv-noark type Tilgang.
//
// Styring av hvem som har tilgang til hvilke opplysninger.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 standard - kap. 4
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Tilgang struct {
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`
	Tittel   string                                 `json:"tittel"`

	Links TilgangLinks `json:"_links,omitempty"`
}

// TilgangLinks is the typed _links envelope for Tilgang.
type TilgangLinks struct {
	AdministrativEnhet []runtime.Link `json:"administrativEnhet,omitempty"`
	Arkivdel           []runtime.Link `json:"arkivdel,omitempty"`
	Arkivressurs       []runtime.Link `json:"arkivressurs,omitempty"`
	Rolle              []runtime.Link `json:"rolle,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Tilgang.
func (l TilgangLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrativEnhet":
		return l.AdministrativEnhet
	case "arkivdel":
		return l.Arkivdel
	case "arkivressurs":
		return l.Arkivressurs
	case "rolle":
		return l.Rolle
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Tilgang) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Tilgang) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// TilgangIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var TilgangIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Tilgang) IDFieldNames() []string { return TilgangIDFieldNames }

// TilgangRelations is the runtime metadata for Tilgang's relations
// (own and inherited, flattened).
var TilgangRelations = []runtime.Relation{
	{
		Name:         "administrativEnhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "arkivressurs",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "tilgang",
		},
	},
	{
		Name:         "rolle",
		Target:       "arkiv-kodeverk:Rolle",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Tilgang) Relations() []runtime.Relation { return TilgangRelations }

func init() {
	runtime.Register("arkiv-noark:Tilgang", func() runtime.Resource { return &Tilgang{} })
}
