// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-datautstyr:DigitalEnhet

package datautstyr

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// DigitalEnhet is the FINT ressurs-datautstyr type DigitalEnhet.
//
// Beskriver ulike digitale enheter slik som feks pc, nettbrett, mobil.
type DigitalEnhet struct {
	DataobjektID    *felleskompleksedatatyper.Identifikator `json:"dataobjektId,omitempty"`
	Flerbrukerenhet *bool                                   `json:"flerbrukerenhet,omitempty"`
	Navn            *string                                 `json:"navn,omitempty"`
	Privateid       *bool                                   `json:"privateid,omitempty"`
	Serienummer     string                                  `json:"serienummer"`
	SystemID        felleskompleksedatatyper.Identifikator  `json:"systemId"`

	Links DigitalEnhetLinks `json:"_links,omitempty"`
}

// DigitalEnhetLinks is the typed _links envelope for DigitalEnhet.
type DigitalEnhetLinks struct {
	Administrator          []runtime.Link `json:"administrator,omitempty"`
	Eier                   []runtime.Link `json:"eier,omitempty"`
	Elev                   []runtime.Link `json:"elev,omitempty"`
	Enhetsgruppemedlemskap []runtime.Link `json:"enhetsgruppemedlemskap,omitempty"`
	Enhetstype             []runtime.Link `json:"enhetstype,omitempty"`
	Personalressurs        []runtime.Link `json:"personalressurs,omitempty"`
	Plattform              []runtime.Link `json:"plattform,omitempty"`
	Produsent              []runtime.Link `json:"produsent,omitempty"`
	Status                 []runtime.Link `json:"status,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on DigitalEnhet.
func (l DigitalEnhetLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrator":
		return l.Administrator
	case "eier":
		return l.Eier
	case "elev":
		return l.Elev
	case "enhetsgruppemedlemskap":
		return l.Enhetsgruppemedlemskap
	case "enhetstype":
		return l.Enhetstype
	case "personalressurs":
		return l.Personalressurs
	case "plattform":
		return l.Plattform
	case "produsent":
		return l.Produsent
	case "status":
		return l.Status
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r DigitalEnhet) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r DigitalEnhet) ForEachID(fn func(name, value string) bool) {
	if r.DataobjektID != nil && !fn("dataobjektId", r.DataobjektID.Identifikatorverdi) {
		return
	}
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// DigitalEnhetIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var DigitalEnhetIDFieldNames = []string{
	"dataobjektId",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (DigitalEnhet) IDFieldNames() []string { return DigitalEnhetIDFieldNames }

// DigitalEnhetRelations is the runtime metadata for DigitalEnhet's relations
// (own and inherited, flattened).
var DigitalEnhetRelations = []runtime.Relation{
	{
		Name:         "administrator",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "1",
	},
	{
		Name:         "eier",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
	},
	{
		Name:         "elev",
		Target:       "utdanning-elev:Elev",
		Multiplicity: "0..1",
	},
	{
		Name:         "enhetsgruppemedlemskap",
		Target:       "ressurs-datautstyr:Enhetsgruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "digitalEnhet",
		},
	},
	{
		Name:         "enhetstype",
		Target:       "ressurs-kodeverk:Enhetstype",
		Multiplicity: "1",
	},
	{
		Name:         "personalressurs",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "plattform",
		Target:       "ressurs-kodeverk:Plattform",
		Multiplicity: "1",
	},
	{
		Name:         "produsent",
		Target:       "ressurs-kodeverk:Produsent",
		Multiplicity: "0..1",
	},
	{
		Name:         "status",
		Target:       "ressurs-kodeverk:Status",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (DigitalEnhet) Relations() []runtime.Relation { return DigitalEnhetRelations }

func init() {
	runtime.Register("ressurs-datautstyr:DigitalEnhet", func() runtime.Resource { return &DigitalEnhet{} })
}
