// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-datautstyr:Enhetsgruppe

package datautstyr

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Enhetsgruppe is the FINT ressurs-datautstyr type Enhetsgruppe.
//
// Angir en gruppering av ensartede digitale enheter. Feks klassesett med iPader eller datalab med ekstra kraftige maskiner.
type Enhetsgruppe struct {
	Navn     string                                 `json:"navn"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links EnhetsgruppeLinks `json:"_links,omitempty"`
}

// EnhetsgruppeLinks is the typed _links envelope for Enhetsgruppe.
type EnhetsgruppeLinks struct {
	Enhetsgruppemedlemskap []runtime.Link `json:"enhetsgruppemedlemskap,omitempty"`
	Enhetstype             []runtime.Link `json:"enhetstype,omitempty"`
	Organisasjonsenhet     []runtime.Link `json:"organisasjonsenhet,omitempty"`
	Plattform              []runtime.Link `json:"plattform,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Enhetsgruppe.
func (l EnhetsgruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "enhetsgruppemedlemskap":
		return l.Enhetsgruppemedlemskap
	case "enhetstype":
		return l.Enhetstype
	case "organisasjonsenhet":
		return l.Organisasjonsenhet
	case "plattform":
		return l.Plattform
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Enhetsgruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Enhetsgruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EnhetsgruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EnhetsgruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Enhetsgruppe) IDFieldNames() []string { return EnhetsgruppeIDFieldNames }

// EnhetsgruppeRelations is the runtime metadata for Enhetsgruppe's relations
// (own and inherited, flattened).
var EnhetsgruppeRelations = []runtime.Relation{
	{
		Name:         "enhetsgruppemedlemskap",
		Target:       "ressurs-datautstyr:Enhetsgruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "enhetsgruppe",
		},
	},
	{
		Name:         "enhetstype",
		Target:       "ressurs-kodeverk:Enhetstype",
		Multiplicity: "1",
	},
	{
		Name:         "organisasjonsenhet",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "1",
	},
	{
		Name:         "plattform",
		Target:       "ressurs-kodeverk:Plattform",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Enhetsgruppe) Relations() []runtime.Relation { return EnhetsgruppeRelations }

func init() {
	runtime.Register("ressurs-datautstyr:Enhetsgruppe", func() runtime.Resource { return &Enhetsgruppe{} })
}
