// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-datautstyr:Enhetsgruppemedlemskap

package datautstyr

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Enhetsgruppemedlemskap is the FINT ressurs-datautstyr type Enhetsgruppemedlemskap.
//
// Medlemskap i enhetsgrupper.
//
// Gruppemedlemskap som knytter sammen Digitalenhet og Enhetsgrupper.
type Enhetsgruppemedlemskap struct {
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links EnhetsgruppemedlemskapLinks `json:"_links,omitempty"`
}

// EnhetsgruppemedlemskapLinks is the typed _links envelope for Enhetsgruppemedlemskap.
type EnhetsgruppemedlemskapLinks struct {
	DigitalEnhet []runtime.Link `json:"digitalEnhet,omitempty"`
	Enhetsgruppe []runtime.Link `json:"enhetsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Enhetsgruppemedlemskap.
func (l EnhetsgruppemedlemskapLinks) ByName(name string) []runtime.Link {
	switch name {
	case "digitalEnhet":
		return l.DigitalEnhet
	case "enhetsgruppe":
		return l.Enhetsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Enhetsgruppemedlemskap) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Enhetsgruppemedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EnhetsgruppemedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EnhetsgruppemedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Enhetsgruppemedlemskap) IDFieldNames() []string { return EnhetsgruppemedlemskapIDFieldNames }

// EnhetsgruppemedlemskapRelations is the runtime metadata for Enhetsgruppemedlemskap's relations
// (own and inherited, flattened).
var EnhetsgruppemedlemskapRelations = []runtime.Relation{
	{
		Name:         "digitalEnhet",
		Target:       "ressurs-datautstyr:DigitalEnhet",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "enhetsgruppemedlemskap",
		},
	},
	{
		Name:         "enhetsgruppe",
		Target:       "ressurs-datautstyr:Enhetsgruppe",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "enhetsgruppemedlemskap",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Enhetsgruppemedlemskap) Relations() []runtime.Relation { return EnhetsgruppemedlemskapRelations }

func init() {
	runtime.Register("ressurs-datautstyr:Enhetsgruppemedlemskap", func() runtime.Resource { return &Enhetsgruppemedlemskap{} })
}
