// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-regnskap:Bilag

package regnskap

import (
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Bilag is the FINT okonomi-regnskap type Bilag.
//
// Dokumentasjon til en transaksjon.
type Bilag struct {
	Bilagsdato   time.Time `json:"bilagsdato"`
	Bilagsnummer *string   `json:"bilagsnummer,omitempty"`
	Data         *string   `json:"data,omitempty"`
	Filnavn      *string   `json:"filnavn,omitempty"`
	Referanse    *string   `json:"referanse,omitempty"`
	Url          *string   `json:"url,omitempty"`
}

// LinksByName satisfies runtime.Resource.
func (r Bilag) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Bilag) ForEachID(fn func(name, value string) bool) {
}

// BilagIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BilagIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Bilag) IDFieldNames() []string { return BilagIDFieldNames }

// BilagRelations is the runtime metadata for Bilag's relations
// (own and inherited, flattened).
var BilagRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Bilag) Relations() []runtime.Relation { return BilagRelations }

func init() {
	runtime.Register("okonomi-regnskap:Bilag", func() runtime.Resource { return &Bilag{} })
}
