// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-regnskap:Leverandor

package regnskap

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Leverandor is the FINT okonomi-regnskap type Leverandor.
//
// Person eller virksomhet som leverer produkter eller tjenester.
type Leverandor struct {
	Kontonummer      *string                                 `json:"kontonummer,omitempty"`
	Leverandornummer *felleskompleksedatatyper.Identifikator `json:"leverandornummer,omitempty"`
	SystemID         felleskompleksedatatyper.Identifikator  `json:"systemId"`

	Links LeverandorLinks `json:"_links,omitempty"`
}

// LeverandorLinks is the typed _links envelope for Leverandor.
type LeverandorLinks struct {
	Leverandorgruppe []runtime.Link `json:"leverandorgruppe,omitempty"`
	Person           []runtime.Link `json:"person,omitempty"`
	Virksomhet       []runtime.Link `json:"virksomhet,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Leverandor.
func (l LeverandorLinks) ByName(name string) []runtime.Link {
	switch name {
	case "leverandorgruppe":
		return l.Leverandorgruppe
	case "person":
		return l.Person
	case "virksomhet":
		return l.Virksomhet
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Leverandor) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Leverandor) ForEachID(fn func(name, value string) bool) {
	if r.Leverandornummer != nil && !fn("leverandornummer", r.Leverandornummer.Identifikatorverdi) {
		return
	}
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// LeverandorIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var LeverandorIDFieldNames = []string{
	"leverandornummer",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Leverandor) IDFieldNames() []string { return LeverandorIDFieldNames }

// LeverandorRelations is the runtime metadata for Leverandor's relations
// (own and inherited, flattened).
var LeverandorRelations = []runtime.Relation{
	{
		Name:         "leverandorgruppe",
		Target:       "okonomi-regnskap:Leverandorgruppe",
		Multiplicity: "0..1",
	},
	{
		Name:         "person",
		Target:       "felles:Person",
		Multiplicity: "0..1",
	},
	{
		Name:         "virksomhet",
		Target:       "felles:Virksomhet",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Leverandor) Relations() []runtime.Relation { return LeverandorRelations }

func init() {
	runtime.Register("okonomi-regnskap:Leverandor", func() runtime.Resource { return &Leverandor{} })
}
