// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-regnskap:Leverandorgruppe

package regnskap

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Leverandorgruppe is the FINT okonomi-regnskap type Leverandorgruppe.
//
// Gruppering av leverandører.
type Leverandorgruppe struct {
	Navn     string                                 `json:"navn"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links LeverandorgruppeLinks `json:"_links,omitempty"`
}

// LeverandorgruppeLinks is the typed _links envelope for Leverandorgruppe.
type LeverandorgruppeLinks struct {
	Leverandor []runtime.Link `json:"leverandor,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Leverandorgruppe.
func (l LeverandorgruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "leverandor":
		return l.Leverandor
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Leverandorgruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Leverandorgruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// LeverandorgruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var LeverandorgruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Leverandorgruppe) IDFieldNames() []string { return LeverandorgruppeIDFieldNames }

// LeverandorgruppeRelations is the runtime metadata for Leverandorgruppe's relations
// (own and inherited, flattened).
var LeverandorgruppeRelations = []runtime.Relation{
	{
		Name:         "leverandor",
		Target:       "okonomi-regnskap:Leverandor",
		Multiplicity: "0..*",
	},
}

// Relations satisfies runtime.Resource.
func (Leverandorgruppe) Relations() []runtime.Relation { return LeverandorgruppeRelations }

func init() {
	runtime.Register("okonomi-regnskap:Leverandorgruppe", func() runtime.Resource { return &Leverandorgruppe{} })
}
