spring:
  kafka:
    consumer:
      group-id: link-walker
  webflux:
    base-path: /link-walker

fint:
  baseUrl: "https://play-with-fint.felleskomponent.no/"
  application-id: link-walker
  kafka:
    topic:
      org-id: flais.io
      domain-context: flais
    application-id: ${fint.application-id}
