springfox:
 title: Fint Link Walker
 version: '@version@'

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  threads:
    virtual:
      enabled: true

fint:
  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
