springfox:
 title: Fint Link Walker
 version: '@version@'

server:
  port: 8080

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

fint:
  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
