springfox:
 title: Fint Link Walker
 version: '@version@'

server:
 port: 8082

security:
  basic:
    enabled: false

fint:
  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client