fint:
  application-id: link-walker
  kafka:
    application-id: ${fint.application-id}

spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.apache.kafka: DEBUG
    no.fintlabs.kafka: DEBUG
    org.springframework.kafka: DEBUG
    no.fintlabs: DEBUG