spring:
  kafka:
    consumer:
      group-id: link-walker
  webflux:
    base-path: /link-walker

fint:
  gateway-url: ""
  metaModel: "https://beta.felleskomponent.no/fint/metamodell/klasse"
  application-id: link-walker
  kafka:
    topic:
      org-id: flais.io
      domain-context: flais
    application-id: ${fint.application-id}
