spring:
  threads:
    virtual:
      enabled: true

fint:
  kafka:
    application-id: fint-link-walker

logging:
  level:
    org.apache.kafka: WARN
    no.fintlabs.kafka: WARN
    org.springframework.kafka: WARN
    no.fintlabs: DEBUG