// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   personvern-samtykke:Behandling

package samtykke

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Behandling is the FINT personvern-samtykke type Behandling.
//
// # All bruk av personopplysninger
//
// # Beskrivelse
//
// All bruk av personopplysninger, slik som innsamling, registrering, sammenstilling, lagring og utlevering, eller en kombinasjon av slike bruksmåter.
//
// Personopplysninger skal bare brukes for spesifikke, uttrykkelige, angitte og legitime formål. Virksomheten har plikt til å gi den enkelte informasjon om formålet med behandling av personopplysning samt behandlingsgrunnlaget.
type Behandling struct {
	Aktiv    bool                                   `json:"aktiv"`
	Formal   string                                 `json:"formal"`
	Slettet  *time.Time                             `json:"slettet,omitempty"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links BehandlingLinks `json:"_links,omitempty"`
}

// BehandlingLinks is the typed _links envelope for Behandling.
type BehandlingLinks struct {
	Behandlingsgrunnlag []runtime.Link `json:"behandlingsgrunnlag,omitempty"`
	Personopplysning    []runtime.Link `json:"personopplysning,omitempty"`
	Samtykke            []runtime.Link `json:"samtykke,omitempty"`
	Tjeneste            []runtime.Link `json:"tjeneste,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Behandling.
func (l BehandlingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "behandlingsgrunnlag":
		return l.Behandlingsgrunnlag
	case "personopplysning":
		return l.Personopplysning
	case "samtykke":
		return l.Samtykke
	case "tjeneste":
		return l.Tjeneste
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Behandling) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Behandling) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// BehandlingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BehandlingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Behandling) IDFieldNames() []string { return BehandlingIDFieldNames }

// BehandlingRelations is the runtime metadata for Behandling's relations
// (own and inherited, flattened).
var BehandlingRelations = []runtime.Relation{
	{
		Name:         "behandlingsgrunnlag",
		Target:       "personvern-kodeverk:Behandlingsgrunnlag",
		Multiplicity: "1",
	},
	{
		Name:         "personopplysning",
		Target:       "personvern-kodeverk:Personopplysning",
		Multiplicity: "1",
	},
	{
		Name:         "samtykke",
		Target:       "personvern-samtykke:Samtykke",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "behandling",
		},
	},
	{
		Name:         "tjeneste",
		Target:       "personvern-samtykke:Tjeneste",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "behandling",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Behandling) Relations() []runtime.Relation { return BehandlingRelations }

func init() {
	runtime.Register("personvern-samtykke:Behandling", func() runtime.Resource { return &Behandling{} })
}
