// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   personvern-samtykke:Samtykke

package samtykke

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Samtykke is the FINT personvern-samtykke type Samtykke.
//
// Tillatelse til behandling av personopplysning.
//
// # Beskrivelse
//
// En virksomhet kan behandle personopplysninger dersom den har innhentet gyldig samtykke fra personen eller personene det gjelder.
type Samtykke struct {
	Gyldighetsperiode felleskompleksedatatyper.Periode       `json:"gyldighetsperiode"`
	Opprettet         time.Time                              `json:"opprettet"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links SamtykkeLinks `json:"_links,omitempty"`
}

// SamtykkeLinks is the typed _links envelope for Samtykke.
type SamtykkeLinks struct {
	Behandling           []runtime.Link `json:"behandling,omitempty"`
	Organisasjonselement []runtime.Link `json:"organisasjonselement,omitempty"`
	Person               []runtime.Link `json:"person,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Samtykke.
func (l SamtykkeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "behandling":
		return l.Behandling
	case "organisasjonselement":
		return l.Organisasjonselement
	case "person":
		return l.Person
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Samtykke) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Samtykke) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SamtykkeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SamtykkeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Samtykke) IDFieldNames() []string { return SamtykkeIDFieldNames }

// SamtykkeRelations is the runtime metadata for Samtykke's relations
// (own and inherited, flattened).
var SamtykkeRelations = []runtime.Relation{
	{
		Name:         "behandling",
		Target:       "personvern-samtykke:Behandling",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "samtykke",
		},
	},
	{
		Name:         "organisasjonselement",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
	},
	{
		Name:         "person",
		Target:       "felles:Person",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Samtykke) Relations() []runtime.Relation { return SamtykkeRelations }

func init() {
	runtime.Register("personvern-samtykke:Samtykke", func() runtime.Resource { return &Samtykke{} })
}
