// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kodeverk:Fylke

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fylke is the FINT felles-kodeverk type Fylke.
//
// # Liste over Norges fylker
//
// # Referanser
//
// * "SSB: Standard for fylkesinndeling":http://www.ssb.no/klass/#!/klassifikasjoner/104
// * "data.norge.no":
// http://data.norge.no/data/statistisk-sentralbyr%C3%A5/fylkesinndeling
type Fylke struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FylkeLinks `json:"_links,omitempty"`
}

// FylkeLinks is the typed _links envelope for Fylke.
type FylkeLinks struct {
	Kommune []runtime.Link `json:"kommune,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fylke.
func (l FylkeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "kommune":
		return l.Kommune
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fylke) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fylke) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FylkeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FylkeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fylke) IDFieldNames() []string { return FylkeIDFieldNames }

// FylkeRelations is the runtime metadata for Fylke's relations
// (own and inherited, flattened).
var FylkeRelations = []runtime.Relation{
	{
		Name:         "kommune",
		Target:       "felles-kodeverk:Kommune",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fylke",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Fylke) Relations() []runtime.Relation { return FylkeRelations }

func init() {
	runtime.Register("felles-kodeverk:Fylke", func() runtime.Resource { return &Fylke{} })
}
