// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kodeverk:Kommune

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kommune is the FINT felles-kodeverk type Kommune.
//
// # Liste over Norges kommuner
//
// Kilde:
//
// * "SSB. Kommuneinndeling 2017":http://www.ssb.no/klass/#!/klassifikasjoner/131
// * "data.norge.no om kommuneinndeling":http://data.norge.no/data/statistisk-sentralbyr%C3%A5/kommuneinndeling
type Kommune struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links KommuneLinks `json:"_links,omitempty"`
}

// KommuneLinks is the typed _links envelope for Kommune.
type KommuneLinks struct {
	Fylke []runtime.Link `json:"fylke,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Kommune.
func (l KommuneLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fylke":
		return l.Fylke
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Kommune) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kommune) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KommuneIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KommuneIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kommune) IDFieldNames() []string { return KommuneIDFieldNames }

// KommuneRelations is the runtime metadata for Kommune's relations
// (own and inherited, flattened).
var KommuneRelations = []runtime.Relation{
	{
		Name:         "fylke",
		Target:       "felles-kodeverk:Fylke",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "kommune",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Kommune) Relations() []runtime.Relation { return KommuneRelations }

func init() {
	runtime.Register("felles-kodeverk:Kommune", func() runtime.Resource { return &Kommune{} })
}
