// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kodeverk:Valuta

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Valuta is the FINT felles-kodeverk type Valuta.
//
// Valutakodene for offisielle valutaer.
//
// # Referanse
// I henhold til [ISO 4217](https://no.wikipedia.org/wiki/ISO_4217)
type Valuta struct {
	Bokstavkode felleskompleksedatatyper.Identifikator `json:"bokstavkode"`
	Navn        string                                 `json:"navn"`
	Nummerkode  felleskompleksedatatyper.Identifikator `json:"nummerkode"`
}

// LinksByName satisfies runtime.Resource.
func (r Valuta) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Valuta) ForEachID(fn func(name, value string) bool) {
	if !fn("bokstavkode", r.Bokstavkode.Identifikatorverdi) {
		return
	}
	if !fn("nummerkode", r.Nummerkode.Identifikatorverdi) {
		return
	}
}

// ValutaIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ValutaIDFieldNames = []string{
	"bokstavkode",
	"nummerkode",
}

// IDFieldNames satisfies runtime.Resource.
func (Valuta) IDFieldNames() []string { return ValutaIDFieldNames }

// ValutaRelations is the runtime metadata for Valuta's relations
// (own and inherited, flattened).
var ValutaRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Valuta) Relations() []runtime.Relation { return ValutaRelations }

func init() {
	runtime.Register("felles-kodeverk:Valuta", func() runtime.Resource { return &Valuta{} })
}
