// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kodeverk-iso:Kjonn

package iso

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kjonn is the FINT felles-kodeverk-iso type Kjonn.
//
// Liste over verdier for kjønn basert på ISO/IEC 5218.
//
// # Beskrivelse
//
// Liste over verdier for kjønn basert på ISO/IEC 5218.
//
// Når vi i daglig tale prater om kjønn presiserer vi sjelden hva vi mener. Avhengig av sammenheng kan vi mene enten biologisk, sosialt, mentalt eller juridisk kjønn. Kjønn kan med andre ord betraktes som et samlebegrep.
// Kilde: llh.no
//
// # Referanser
//
// * [FINT API for ISO/IEC 5218](https://api.felleskomponent.no/felles/kodeverk/kjonn)
// * [ISO/IEC 5218:2004](https://iso.org/standard/36266.html)
// * [Wikipedia artikkel](https://en.wikipedia.org/wiki/ISO/IEC_5218)
//
// # Eksempler
//
//	0 = uvisst (not known)
//	1 = mann (male)
//	2 = kvinne (female)
//	9 = gjelder ikke (not applicable)
type Kjonn struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Kjonn) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kjonn) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KjonnIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KjonnIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kjonn) IDFieldNames() []string { return KjonnIDFieldNames }

// KjonnRelations is the runtime metadata for Kjonn's relations
// (own and inherited, flattened).
var KjonnRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Kjonn) Relations() []runtime.Relation { return KjonnRelations }

func init() {
	runtime.Register("felles-kodeverk-iso:Kjonn", func() runtime.Resource { return &Kjonn{} })
}
