// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kodeverk-iso:Sprak

package iso

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Sprak is the FINT felles-kodeverk-iso type Sprak.
//
// Liste over verdier for språk  (2 bokstav)
//
// # Beskrivelse
//
// Liste over alle språk etter ISO 639-1 standard (2 bokstav)
//
// # Eksempler
//
// NO, NB, NN, DA, etc.
//
// # Referanse
//
// [FINT api for ISO 639-1 Alpha2](https://api.felleskomponent.no/felles/kodeverk/iso/6391alpha2)
type Sprak struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Sprak) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Sprak) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SprakIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SprakIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Sprak) IDFieldNames() []string { return SprakIDFieldNames }

// SprakRelations is the runtime metadata for Sprak's relations
// (own and inherited, flattened).
var SprakRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Sprak) Relations() []runtime.Relation { return SprakRelations }

func init() {
	runtime.Register("felles-kodeverk-iso:Sprak", func() runtime.Resource { return &Sprak{} })
}
