// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-fullmakt:Fullmakt

package fullmakt

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fullmakt is the FINT administrasjon-fullmakt type Fullmakt.
//
// Fullmakt til å gjøre handlinger i forhold til en gitt Rolle.
//
// # Beskrivelse
//
// Fullmakter innehas av fysiske eller juridiske personer, og er knyttet til kontodimensjon eller organisasjonselement. Fullmakter er delegert til personer, disse benevnes som fullmektige.
//
// Fullmektige kan ha stedfortreder. Stedfortrederen kan utøve den samme fullmakten som den fullmektige.
//
// Fullmakter beskrives i delegasjonsreglementet for organisasjonen. For fylkeskommuner er dette et reglement besluttet av Fylkestinget og videre delegert av Fylkesrådmannen.
//
// Dersom fullmakt har relasjon til mer enn en kontodimensjon (og organisasjonselement) er det å regne som en kombinasjonsfullmakt.
//
// # Eksempler
//
// Rektor ved Eidsvoll VGS har anvisningsfullmakt for ansvar 241.
type Fullmakt struct {
	Gyldighetsperiode felleskompleksedatatyper.Periode       `json:"gyldighetsperiode"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FullmaktLinks `json:"_links,omitempty"`
}

// FullmaktLinks is the typed _links envelope for Fullmakt.
type FullmaktLinks struct {
	Aktivitet            []runtime.Link `json:"aktivitet,omitempty"`
	Anlegg               []runtime.Link `json:"anlegg,omitempty"`
	Ansvar               []runtime.Link `json:"ansvar,omitempty"`
	Art                  []runtime.Link `json:"art,omitempty"`
	Diverse              []runtime.Link `json:"diverse,omitempty"`
	Formal               []runtime.Link `json:"formal,omitempty"`
	Fullmektig           []runtime.Link `json:"fullmektig,omitempty"`
	Funksjon             []runtime.Link `json:"funksjon,omitempty"`
	Kontrakt             []runtime.Link `json:"kontrakt,omitempty"`
	Lopenummer           []runtime.Link `json:"lopenummer,omitempty"`
	Objekt               []runtime.Link `json:"objekt,omitempty"`
	Organisasjonselement []runtime.Link `json:"organisasjonselement,omitempty"`
	Prosjekt             []runtime.Link `json:"prosjekt,omitempty"`
	Ramme                []runtime.Link `json:"ramme,omitempty"`
	Rolle                []runtime.Link `json:"rolle,omitempty"`
	Stedfortreder        []runtime.Link `json:"stedfortreder,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fullmakt.
func (l FullmaktLinks) ByName(name string) []runtime.Link {
	switch name {
	case "aktivitet":
		return l.Aktivitet
	case "anlegg":
		return l.Anlegg
	case "ansvar":
		return l.Ansvar
	case "art":
		return l.Art
	case "diverse":
		return l.Diverse
	case "formal":
		return l.Formal
	case "fullmektig":
		return l.Fullmektig
	case "funksjon":
		return l.Funksjon
	case "kontrakt":
		return l.Kontrakt
	case "lopenummer":
		return l.Lopenummer
	case "objekt":
		return l.Objekt
	case "organisasjonselement":
		return l.Organisasjonselement
	case "prosjekt":
		return l.Prosjekt
	case "ramme":
		return l.Ramme
	case "rolle":
		return l.Rolle
	case "stedfortreder":
		return l.Stedfortreder
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fullmakt) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fullmakt) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FullmaktIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FullmaktIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fullmakt) IDFieldNames() []string { return FullmaktIDFieldNames }

// FullmaktRelations is the runtime metadata for Fullmakt's relations
// (own and inherited, flattened).
var FullmaktRelations = []runtime.Relation{
	{
		Name:         "aktivitet",
		Target:       "administrasjon-kodeverk:Aktivitet",
		Multiplicity: "0..1",
	},
	{
		Name:         "anlegg",
		Target:       "administrasjon-kodeverk:Anlegg",
		Multiplicity: "0..1",
	},
	{
		Name:         "ansvar",
		Target:       "administrasjon-kodeverk:Ansvar",
		Multiplicity: "0..1",
	},
	{
		Name:         "art",
		Target:       "administrasjon-kodeverk:Art",
		Multiplicity: "0..1",
	},
	{
		Name:         "diverse",
		Target:       "administrasjon-kodeverk:Diverse",
		Multiplicity: "0..1",
	},
	{
		Name:         "formal",
		Target:       "administrasjon-kodeverk:Formal",
		Multiplicity: "0..1",
	},
	{
		Name:         "fullmektig",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fullmakt",
		},
	},
	{
		Name:         "funksjon",
		Target:       "administrasjon-kodeverk:Funksjon",
		Multiplicity: "0..1",
	},
	{
		Name:         "kontrakt",
		Target:       "administrasjon-kodeverk:Kontrakt",
		Multiplicity: "0..1",
	},
	{
		Name:         "lopenummer",
		Target:       "administrasjon-kodeverk:Lopenummer",
		Multiplicity: "0..1",
	},
	{
		Name:         "objekt",
		Target:       "administrasjon-kodeverk:Objekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "organisasjonselement",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
	},
	{
		Name:         "prosjekt",
		Target:       "administrasjon-kodeverk:Prosjekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "ramme",
		Target:       "administrasjon-kodeverk:Ramme",
		Multiplicity: "0..1",
	},
	{
		Name:         "rolle",
		Target:       "administrasjon-fullmakt:Rolle",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fullmakt",
		},
	},
	{
		Name:         "stedfortreder",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "stedfortreder",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Fullmakt) Relations() []runtime.Relation { return FullmaktRelations }

func init() {
	runtime.Register("administrasjon-fullmakt:Fullmakt", func() runtime.Resource { return &Fullmakt{} })
}
