// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-basisklasser:Aktor

package basisklasser

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Aktor is the FINT felles-basisklasser type Aktor.
//
// Person eller enhet vi samhandler med.
//
// # Beskrivelse
//
// Abstrakt klasse som inneholder relasjon til kontaktinformasjon og identifikator. Må enten brukes som Person, Enhet, eller annen underliggende klasse, som feks organisasjonselement.
type Aktor struct {
	Kontaktinformasjon *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Postadresse        *felleskompleksedatatyper.Adresse            `json:"postadresse,omitempty"`
}

// LinksByName satisfies runtime.Resource.
func (r Aktor) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Aktor) ForEachID(fn func(name, value string) bool) {
}

// AktorIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AktorIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Aktor) IDFieldNames() []string { return AktorIDFieldNames }

// AktorRelations is the runtime metadata for Aktor's relations
// (own and inherited, flattened).
var AktorRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Aktor) Relations() []runtime.Relation { return AktorRelations }

func init() {
	runtime.Register("felles-basisklasser:Aktor", func() runtime.Resource { return &Aktor{} })
}
