// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kulturminnevern:TilskuddFredaBygningPrivatEie

package kulturminnevern

import (
	arkivnoark "github.com/FINTLabs/fint-model-go/arkiv/noark"
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// TilskuddFredaBygningPrivatEie is the FINT arkiv-kulturminnevern type TilskuddFredaBygningPrivatEie.
//
// Sak om søknad om tilskudd til freda bygninger i privat eie (FRIP).
type TilskuddFredaBygningPrivatEie struct {
	AvsluttetDato     *time.Time                                `json:"avsluttetDato,omitempty"`
	Beskrivelse       *string                                   `json:"beskrivelse,omitempty"`
	Bygningsnavn      *string                                   `json:"bygningsnavn,omitempty"`
	Journalpost       []arkivnoark.Journalpost                  `json:"journalpost,omitempty"`
	Klasse            []arkivnoark.Klasse                       `json:"klasse,omitempty"`
	KulturminneID     string                                    `json:"kulturminneId"`
	MappeID           *felleskompleksedatatyper.Identifikator   `json:"mappeId,omitempty"`
	Matrikkelnummer   *felleskompleksedatatyper.Matrikkelnummer `json:"matrikkelnummer,omitempty"`
	Merknad           []arkivnoark.Merknad                      `json:"merknad,omitempty"`
	Noekkelord        []string                                  `json:"noekkelord,omitempty"`
	OffentligTittel   *string                                   `json:"offentligTittel,omitempty"`
	OpprettetDato     *time.Time                                `json:"opprettetDato,omitempty"`
	Part              []arkivnoark.Part                         `json:"part,omitempty"`
	Saksaar           *string                                   `json:"saksaar,omitempty"`
	Saksdato          *time.Time                                `json:"saksdato,omitempty"`
	Sakssekvensnummer *string                                   `json:"sakssekvensnummer,omitempty"`
	Skjerming         *arkivnoark.Skjerming                     `json:"skjerming,omitempty"`
	Soknadsnummer     *felleskompleksedatatyper.Identifikator   `json:"soknadsnummer,omitempty"`
	SystemID          *felleskompleksedatatyper.Identifikator   `json:"systemId,omitempty"`
	Tittel            *string                                   `json:"tittel,omitempty"`
	UtlaantDato       *time.Time                                `json:"utlaantDato,omitempty"`

	Links TilskuddFredaBygningPrivatEieLinks `json:"_links,omitempty"`
}

// TilskuddFredaBygningPrivatEieLinks is the typed _links envelope for TilskuddFredaBygningPrivatEie.
type TilskuddFredaBygningPrivatEieLinks struct {
	AdministrativEnhet []runtime.Link `json:"administrativEnhet,omitempty"`
	Arkivdel           []runtime.Link `json:"arkivdel,omitempty"`
	AvsluttetAv        []runtime.Link `json:"avsluttetAv,omitempty"`
	Journalenhet       []runtime.Link `json:"journalenhet,omitempty"`
	OpprettetAv        []runtime.Link `json:"opprettetAv,omitempty"`
	Saksansvarlig      []runtime.Link `json:"saksansvarlig,omitempty"`
	Saksmappetype      []runtime.Link `json:"saksmappetype,omitempty"`
	Saksstatus         []runtime.Link `json:"saksstatus,omitempty"`
	Tilgangsgruppe     []runtime.Link `json:"tilgangsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on TilskuddFredaBygningPrivatEie.
func (l TilskuddFredaBygningPrivatEieLinks) ByName(name string) []runtime.Link {
	switch name {
	case "administrativEnhet":
		return l.AdministrativEnhet
	case "arkivdel":
		return l.Arkivdel
	case "avsluttetAv":
		return l.AvsluttetAv
	case "journalenhet":
		return l.Journalenhet
	case "opprettetAv":
		return l.OpprettetAv
	case "saksansvarlig":
		return l.Saksansvarlig
	case "saksmappetype":
		return l.Saksmappetype
	case "saksstatus":
		return l.Saksstatus
	case "tilgangsgruppe":
		return l.Tilgangsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r TilskuddFredaBygningPrivatEie) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r TilskuddFredaBygningPrivatEie) ForEachID(fn func(name, value string) bool) {
	if r.MappeID != nil && !fn("mappeId", r.MappeID.Identifikatorverdi) {
		return
	}
	if r.Soknadsnummer != nil && !fn("soknadsnummer", r.Soknadsnummer.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// TilskuddFredaBygningPrivatEieIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var TilskuddFredaBygningPrivatEieIDFieldNames = []string{
	"mappeId",
	"soknadsnummer",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (TilskuddFredaBygningPrivatEie) IDFieldNames() []string {
	return TilskuddFredaBygningPrivatEieIDFieldNames
}

// TilskuddFredaBygningPrivatEieRelations is the runtime metadata for TilskuddFredaBygningPrivatEie's relations
// (own and inherited, flattened).
var TilskuddFredaBygningPrivatEieRelations = []runtime.Relation{
	{
		Name:         "administrativEnhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "1",
	},
	{
		Name:         "arkivdel",
		Target:       "arkiv-noark:Arkivdel",
		Multiplicity: "0..1",
	},
	{
		Name:         "avsluttetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "journalenhet",
		Target:       "arkiv-noark:AdministrativEnhet",
		Multiplicity: "0..1",
	},
	{
		Name:         "opprettetAv",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksansvarlig",
		Target:       "arkiv-noark:Arkivressurs",
		Multiplicity: "1",
	},
	{
		Name:         "saksmappetype",
		Target:       "arkiv-kodeverk:Saksmappetype",
		Multiplicity: "0..1",
	},
	{
		Name:         "saksstatus",
		Target:       "arkiv-kodeverk:Saksstatus",
		Multiplicity: "1",
	},
	{
		Name:         "tilgangsgruppe",
		Target:       "arkiv-kodeverk:Tilgangsgruppe",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (TilskuddFredaBygningPrivatEie) Relations() []runtime.Relation {
	return TilskuddFredaBygningPrivatEieRelations
}

func init() {
	runtime.Register("arkiv-kulturminnevern:TilskuddFredaBygningPrivatEie", func() runtime.Resource { return &TilskuddFredaBygningPrivatEie{} })
}
