// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:JournalStatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// JournalStatus is the FINT arkiv-kodeverk type JournalStatus.
//
// Status til journalposten, dvs. om dokumentet er registrert, under behandling eller endelig arkivert.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M053
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type JournalStatus struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r JournalStatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r JournalStatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// JournalStatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var JournalStatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (JournalStatus) IDFieldNames() []string { return JournalStatusIDFieldNames }

// JournalStatusRelations is the runtime metadata for JournalStatus's relations
// (own and inherited, flattened).
var JournalStatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (JournalStatus) Relations() []runtime.Relation { return JournalStatusRelations }

func init() {
	runtime.Register("arkiv-kodeverk:JournalStatus", func() runtime.Resource { return &JournalStatus{} })
}
