// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:JournalpostType

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// JournalpostType is the FINT arkiv-kodeverk type JournalpostType.
//
// Navn på type journalpost.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M082
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type JournalpostType struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r JournalpostType) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r JournalpostType) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// JournalpostTypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var JournalpostTypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (JournalpostType) IDFieldNames() []string { return JournalpostTypeIDFieldNames }

// JournalpostTypeRelations is the runtime metadata for JournalpostType's relations
// (own and inherited, flattened).
var JournalpostTypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (JournalpostType) Relations() []runtime.Relation { return JournalpostTypeRelations }

func init() {
	runtime.Register("arkiv-kodeverk:JournalpostType", func() runtime.Resource { return &JournalpostType{} })
}
