// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:KorrespondansepartType

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// KorrespondansepartType is the FINT arkiv-kodeverk type KorrespondansepartType.
//
// Kodeverk over korrespondansepart typer.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M087
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type KorrespondansepartType struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r KorrespondansepartType) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r KorrespondansepartType) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KorrespondansepartTypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KorrespondansepartTypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (KorrespondansepartType) IDFieldNames() []string { return KorrespondansepartTypeIDFieldNames }

// KorrespondansepartTypeRelations is the runtime metadata for KorrespondansepartType's relations
// (own and inherited, flattened).
var KorrespondansepartTypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (KorrespondansepartType) Relations() []runtime.Relation { return KorrespondansepartTypeRelations }

func init() {
	runtime.Register("arkiv-kodeverk:KorrespondansepartType", func() runtime.Resource { return &KorrespondansepartType{} })
}
