// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Merknadstype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Merknadstype is the FINT arkiv-kodeverk type Merknadstype.
//
// # Navn på type merknad
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M084
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Merknadstype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Merknadstype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Merknadstype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// MerknadstypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var MerknadstypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Merknadstype) IDFieldNames() []string { return MerknadstypeIDFieldNames }

// MerknadstypeRelations is the runtime metadata for Merknadstype's relations
// (own and inherited, flattened).
var MerknadstypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Merknadstype) Relations() []runtime.Relation { return MerknadstypeRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Merknadstype", func() runtime.Resource { return &Merknadstype{} })
}
