// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:PartRolle

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// PartRolle is the FINT arkiv-kodeverk type PartRolle.
//
// Angivelse av rollen til parten.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M303
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type PartRolle struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r PartRolle) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r PartRolle) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PartRolleIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PartRolleIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (PartRolle) IDFieldNames() []string { return PartRolleIDFieldNames }

// PartRolleRelations is the runtime metadata for PartRolle's relations
// (own and inherited, flattened).
var PartRolleRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (PartRolle) Relations() []runtime.Relation { return PartRolleRelations }

func init() {
	runtime.Register("arkiv-kodeverk:PartRolle", func() runtime.Resource { return &PartRolle{} })
}
