// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Rolle

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Rolle is the FINT arkiv-kodeverk type Rolle.
//
// Rollen til en arkivressurs.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M581
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Rolle struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Rolle) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Rolle) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// RolleIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var RolleIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Rolle) IDFieldNames() []string { return RolleIDFieldNames }

// RolleRelations is the runtime metadata for Rolle's relations
// (own and inherited, flattened).
var RolleRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Rolle) Relations() []runtime.Relation { return RolleRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Rolle", func() runtime.Resource { return &Rolle{} })
}
