// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Saksmappetype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Saksmappetype is the FINT arkiv-kodeverk type Saksmappetype.
//
// Saksmappetyper brukes for å differensiere innhold og etter hvilke rutiner saker skal behandles.
//
// Dette er ikke en del av Noark standarden.
//
// # Synonymer
// <ul>
//
//	<li>Sakstype (P360)</li>
//
// </ul>
//
// # Eksempel
//
// * Sak
// * PE
// * TS
type Saksmappetype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Saksmappetype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Saksmappetype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SaksmappetypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SaksmappetypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Saksmappetype) IDFieldNames() []string { return SaksmappetypeIDFieldNames }

// SaksmappetypeRelations is the runtime metadata for Saksmappetype's relations
// (own and inherited, flattened).
var SaksmappetypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Saksmappetype) Relations() []runtime.Relation { return SaksmappetypeRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Saksmappetype", func() runtime.Resource { return &Saksmappetype{} })
}
