// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Saksstatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Saksstatus is the FINT arkiv-kodeverk type Saksstatus.
//
// Status til saksmappen, dvs. hvor langt saksbehandlingen har kommet.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M052
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Saksstatus struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Saksstatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Saksstatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SaksstatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SaksstatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Saksstatus) IDFieldNames() []string { return SaksstatusIDFieldNames }

// SaksstatusRelations is the runtime metadata for Saksstatus's relations
// (own and inherited, flattened).
var SaksstatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Saksstatus) Relations() []runtime.Relation { return SaksstatusRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Saksstatus", func() runtime.Resource { return &Saksstatus{} })
}
