// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Skjermingshjemmel

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Skjermingshjemmel is the FINT arkiv-kodeverk type Skjermingshjemmel.
//
// Henvisning til hjemmel (paragraf) i offentlighetsloven, sikkerhetsloven eller beskyttelsesinstruksen.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M501
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Skjermingshjemmel struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Skjermingshjemmel) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Skjermingshjemmel) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SkjermingshjemmelIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SkjermingshjemmelIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Skjermingshjemmel) IDFieldNames() []string { return SkjermingshjemmelIDFieldNames }

// SkjermingshjemmelRelations is the runtime metadata for Skjermingshjemmel's relations
// (own and inherited, flattened).
var SkjermingshjemmelRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Skjermingshjemmel) Relations() []runtime.Relation { return SkjermingshjemmelRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Skjermingshjemmel", func() runtime.Resource { return &Skjermingshjemmel{} })
}
