// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Tilgangsrestriksjon

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Tilgangsrestriksjon is the FINT arkiv-kodeverk type Tilgangsrestriksjon.
//
// Angivelse av at dokumentene som tilhører arkivenheten ikke er offentligtilgjengelig i henhold til offentlighetsloven eller av en annen grunn.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M500
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Tilgangsrestriksjon struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Tilgangsrestriksjon) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Tilgangsrestriksjon) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// TilgangsrestriksjonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var TilgangsrestriksjonIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Tilgangsrestriksjon) IDFieldNames() []string { return TilgangsrestriksjonIDFieldNames }

// TilgangsrestriksjonRelations is the runtime metadata for Tilgangsrestriksjon's relations
// (own and inherited, flattened).
var TilgangsrestriksjonRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Tilgangsrestriksjon) Relations() []runtime.Relation { return TilgangsrestriksjonRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Tilgangsrestriksjon", func() runtime.Resource { return &Tilgangsrestriksjon{} })
}
