// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:TilknyttetRegistreringSom

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// TilknyttetRegistreringSom is the FINT arkiv-kodeverk type TilknyttetRegistreringSom.
//
// Angivelse av hvilken "rolle" dokumentet har i forhold til registreringen.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M217
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type TilknyttetRegistreringSom struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r TilknyttetRegistreringSom) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r TilknyttetRegistreringSom) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// TilknyttetRegistreringSomIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var TilknyttetRegistreringSomIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (TilknyttetRegistreringSom) IDFieldNames() []string {
	return TilknyttetRegistreringSomIDFieldNames
}

// TilknyttetRegistreringSomRelations is the runtime metadata for TilknyttetRegistreringSom's relations
// (own and inherited, flattened).
var TilknyttetRegistreringSomRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (TilknyttetRegistreringSom) Relations() []runtime.Relation {
	return TilknyttetRegistreringSomRelations
}

func init() {
	runtime.Register("arkiv-kodeverk:TilknyttetRegistreringSom", func() runtime.Resource { return &TilknyttetRegistreringSom{} })
}
