// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   arkiv-kodeverk:Variantformat

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Variantformat is the FINT arkiv-kodeverk type Variantformat.
//
// Angivelse av hvilken variant et dokument forekommer i.
//
// # Beskrivelse
//
// * Noark 5 versjon 5.0 metadatakatalog - nr. M700
//
// # Referanser
//
// * https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden
type Variantformat struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Variantformat) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Variantformat) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// VariantformatIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var VariantformatIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Variantformat) IDFieldNames() []string { return VariantformatIDFieldNames }

// VariantformatRelations is the runtime metadata for Variantformat's relations
// (own and inherited, flattened).
var VariantformatRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Variantformat) Relations() []runtime.Relation { return VariantformatRelations }

func init() {
	runtime.Register("arkiv-kodeverk:Variantformat", func() runtime.Resource { return &Variantformat{} })
}
