spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linkwalker}
    username: ${SPRING_DATASOURCE_USERNAME:linkwalker}
    password: ${SPRING_DATASOURCE_PASSWORD:linkwalker}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /link-walker

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      probes:
        enabled: true
