// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-kodeverk:Vare

package kodeverk

import (
	administrasjonkompleksedatatyper "github.com/FINTLabs/fint-model-go/administrasjon/kompleksedatatyper"
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Vare is the FINT okonomi-kodeverk type Vare.
//
// Vare eller tjeneste som kan leveres og faktureres.
//
// # Beskrivelse
//
// Varer leveres i en mengde beskrevet i en enhet, til en nettopris per enhet.  Til hver vare er det tilknyttet en kode som angir sats for merverdiavgift.
//
// Konteringen som varen har i økonomisystemet kan også angis.
type Vare struct {
	Enhet             string                                        `json:"enhet"`
	Gyldighetsperiode *felleskompleksedatatyper.Periode             `json:"gyldighetsperiode,omitempty"`
	Kode              string                                        `json:"kode"`
	Kontering         *administrasjonkompleksedatatyper.Kontostreng `json:"kontering,omitempty"`
	Navn              string                                        `json:"navn"`
	Passiv            *bool                                         `json:"passiv,omitempty"`
	Pris              int64                                         `json:"pris"`
	SystemID          felleskompleksedatatyper.Identifikator        `json:"systemId"`

	Links VareLinks `json:"_links,omitempty"`
}

// VareLinks is the typed _links envelope for Vare.
type VareLinks struct {
	Fakturautsteder []runtime.Link `json:"fakturautsteder,omitempty"`
	Merverdiavgift  []runtime.Link `json:"merverdiavgift,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Vare.
func (l VareLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fakturautsteder":
		return l.Fakturautsteder
	case "merverdiavgift":
		return l.Merverdiavgift
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Vare) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Vare) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// VareIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var VareIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Vare) IDFieldNames() []string { return VareIDFieldNames }

// VareRelations is the runtime metadata for Vare's relations
// (own and inherited, flattened).
var VareRelations = []runtime.Relation{
	{
		Name:         "fakturautsteder",
		Target:       "okonomi-faktura:Fakturautsteder",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "vare",
		},
	},
	{
		Name:         "merverdiavgift",
		Target:       "okonomi-kodeverk:Merverdiavgift",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Vare) Relations() []runtime.Relation { return VareRelations }

func init() {
	runtime.Register("okonomi-kodeverk:Vare", func() runtime.Resource { return &Vare{} })
}
