// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   personvern-kodeverk:Personopplysning

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Personopplysning is the FINT personvern-kodeverk type Personopplysning.
//
// Opplysninger og vurderinger som kan knyttes til enkeltpersoner.
//
// # Beskrivelse
//
// Typiske personopplysninger er navn, adresse, telefonnummer, e-post og fødselsnummer. Et bilde regnes som en personopplysning dersom personer kan gjenkjennes.
//
// # Referanser
//
// Personvernforordningen artikkel 4
type Personopplysning struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Personopplysning) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Personopplysning) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PersonopplysningIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersonopplysningIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Personopplysning) IDFieldNames() []string { return PersonopplysningIDFieldNames }

// PersonopplysningRelations is the runtime metadata for Personopplysning's relations
// (own and inherited, flattened).
var PersonopplysningRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Personopplysning) Relations() []runtime.Relation { return PersonopplysningRelations }

func init() {
	runtime.Register("personvern-kodeverk:Personopplysning", func() runtime.Resource { return &Personopplysning{} })
}
