// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-eiendel:Applikasjonsressurs

package eiendel

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Applikasjonsressurs is the FINT ressurs-eiendel type Applikasjonsressurs.
//
// Informasjon om hvor en applikasjon kan benyttes.
//
// En ressurs er knyttet til en avtale som beskriver antall lisenser, lisensmodell og hvem som kan benytte den.
type Applikasjonsressurs struct {
	Beskrivelse       *string                                `json:"beskrivelse,omitempty"`
	Enhetskostnad     *int64                                 `json:"enhetskostnad,omitempty"`
	Gyldighetsperiode felleskompleksedatatyper.Periode       `json:"gyldighetsperiode"`
	KreverGodkjenning *bool                                  `json:"kreverGodkjenning,omitempty"`
	Lisensantall      *int64                                 `json:"lisensantall,omitempty"`
	Navn              string                                 `json:"navn"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ApplikasjonsressursLinks `json:"_links,omitempty"`
}

// ApplikasjonsressursLinks is the typed _links envelope for Applikasjonsressurs.
type ApplikasjonsressursLinks struct {
	Applikasjon            []runtime.Link `json:"applikasjon,omitempty"`
	Brukertype             []runtime.Link `json:"brukertype,omitempty"`
	Eier                   []runtime.Link `json:"eier,omitempty"`
	Handhevingstype        []runtime.Link `json:"handhevingstype,omitempty"`
	Lisensmodell           []runtime.Link `json:"lisensmodell,omitempty"`
	Ressurstilgjengelighet []runtime.Link `json:"ressurstilgjengelighet,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Applikasjonsressurs.
func (l ApplikasjonsressursLinks) ByName(name string) []runtime.Link {
	switch name {
	case "applikasjon":
		return l.Applikasjon
	case "brukertype":
		return l.Brukertype
	case "eier":
		return l.Eier
	case "handhevingstype":
		return l.Handhevingstype
	case "lisensmodell":
		return l.Lisensmodell
	case "ressurstilgjengelighet":
		return l.Ressurstilgjengelighet
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Applikasjonsressurs) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Applikasjonsressurs) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ApplikasjonsressursIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ApplikasjonsressursIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Applikasjonsressurs) IDFieldNames() []string { return ApplikasjonsressursIDFieldNames }

// ApplikasjonsressursRelations is the runtime metadata for Applikasjonsressurs's relations
// (own and inherited, flattened).
var ApplikasjonsressursRelations = []runtime.Relation{
	{
		Name:         "applikasjon",
		Target:       "ressurs-eiendel:Applikasjon",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "ressurs",
		},
	},
	{
		Name:         "brukertype",
		Target:       "ressurs-kodeverk:Brukertype",
		Multiplicity: "1..*",
	},
	{
		Name:         "eier",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "1",
	},
	{
		Name:         "handhevingstype",
		Target:       "ressurs-kodeverk:Handhevingstype",
		Multiplicity: "0..1",
	},
	{
		Name:         "lisensmodell",
		Target:       "ressurs-kodeverk:Lisensmodell",
		Multiplicity: "0..1",
	},
	{
		Name:         "ressurstilgjengelighet",
		Target:       "ressurs-eiendel:Applikasjonsressurstilgjengelighet",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "ressurs",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Applikasjonsressurs) Relations() []runtime.Relation { return ApplikasjonsressursRelations }

func init() {
	runtime.Register("ressurs-eiendel:Applikasjonsressurs", func() runtime.Resource { return &Applikasjonsressurs{} })
}
