// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-eiendel:Applikasjon

package eiendel

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Applikasjon is the FINT ressurs-eiendel type Applikasjon.
//
// En applikasjon med tilhørende ressurser.
//
// En ressurs kan være en lisens eller en rolle som tilganger inne i en applikasjon. Applikasjonen kan være en desktopapplikasjon eller en skybasert tjeneste. Brukere kan da få tilgang til denne applikasjonen hvis vedkommende har fått tildelt en ressurs knyttet til applikasjonen.
type Applikasjon struct {
	Beskrivelse       *string                                `json:"beskrivelse,omitempty"`
	Gyldighetsperiode felleskompleksedatatyper.Periode       `json:"gyldighetsperiode"`
	Navn              string                                 `json:"navn"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ApplikasjonLinks `json:"_links,omitempty"`
}

// ApplikasjonLinks is the typed _links envelope for Applikasjon.
type ApplikasjonLinks struct {
	Applikasjonskategori []runtime.Link `json:"applikasjonskategori,omitempty"`
	Plattform            []runtime.Link `json:"plattform,omitempty"`
	Ressurs              []runtime.Link `json:"ressurs,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Applikasjon.
func (l ApplikasjonLinks) ByName(name string) []runtime.Link {
	switch name {
	case "applikasjonskategori":
		return l.Applikasjonskategori
	case "plattform":
		return l.Plattform
	case "ressurs":
		return l.Ressurs
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Applikasjon) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Applikasjon) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ApplikasjonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ApplikasjonIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Applikasjon) IDFieldNames() []string { return ApplikasjonIDFieldNames }

// ApplikasjonRelations is the runtime metadata for Applikasjon's relations
// (own and inherited, flattened).
var ApplikasjonRelations = []runtime.Relation{
	{
		Name:         "applikasjonskategori",
		Target:       "ressurs-kodeverk:Applikasjonskategori",
		Multiplicity: "0..*",
	},
	{
		Name:         "plattform",
		Target:       "ressurs-kodeverk:Plattform",
		Multiplicity: "0..*",
	},
	{
		Name:         "ressurs",
		Target:       "ressurs-eiendel:Applikasjonsressurs",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "applikasjon",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Applikasjon) Relations() []runtime.Relation { return ApplikasjonRelations }

func init() {
	runtime.Register("ressurs-eiendel:Applikasjon", func() runtime.Resource { return &Applikasjon{} })
}
