apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../base
commonLabels:
  app.kubernetes.io/name: fint-link-walker
  app.kubernetes.io/instance: fint-link-walker_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: 'kunde-beta.felleskomponent.no'
    target:
      kind: Application
      name: fint-link-walker
