// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Anmerkninger

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Anmerkninger is the FINT utdanning-vurdering type Anmerkninger.
//
// Anmerkninger for en elev for et elevforhold.
type Anmerkninger struct {
	Atferd   int                                    `json:"atferd"`
	Orden    int                                    `json:"orden"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links AnmerkningerLinks `json:"_links,omitempty"`
}

// AnmerkningerLinks is the typed _links envelope for Anmerkninger.
type AnmerkningerLinks struct {
	Skolear []runtime.Link `json:"skolear,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Anmerkninger.
func (l AnmerkningerLinks) ByName(name string) []runtime.Link {
	switch name {
	case "skolear":
		return l.Skolear
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Anmerkninger) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Anmerkninger) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// AnmerkningerIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AnmerkningerIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Anmerkninger) IDFieldNames() []string { return AnmerkningerIDFieldNames }

// AnmerkningerRelations is the runtime metadata for Anmerkninger's relations
// (own and inherited, flattened).
var AnmerkningerRelations = []runtime.Relation{
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Anmerkninger) Relations() []runtime.Relation { return AnmerkningerRelations }

func init() {
	runtime.Register("utdanning-vurdering:Anmerkninger", func() runtime.Resource { return &Anmerkninger{} })
}
