// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Eksamensvurdering

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Eksamensvurdering is the FINT utdanning-vurdering type Eksamensvurdering.
//
// Eksamensvurdering gis etter deltakelse på eksamen.
type Eksamensvurdering struct {
	Kommentar      string                                 `json:"kommentar"`
	SystemID       felleskompleksedatatyper.Identifikator `json:"systemId"`
	Vurderingsdato time.Time                              `json:"vurderingsdato"`

	Links EksamensvurderingLinks `json:"_links,omitempty"`
}

// EksamensvurderingLinks is the typed _links envelope for Eksamensvurdering.
type EksamensvurderingLinks struct {
	Eksamensgruppe   []runtime.Link `json:"eksamensgruppe,omitempty"`
	Elevvurdering    []runtime.Link `json:"elevvurdering,omitempty"`
	Fag              []runtime.Link `json:"fag,omitempty"`
	Karakter         []runtime.Link `json:"karakter,omitempty"`
	Karakterhistorie []runtime.Link `json:"karakterhistorie,omitempty"`
	Skolear          []runtime.Link `json:"skolear,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Eksamensvurdering.
func (l EksamensvurderingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "elevvurdering":
		return l.Elevvurdering
	case "fag":
		return l.Fag
	case "karakter":
		return l.Karakter
	case "karakterhistorie":
		return l.Karakterhistorie
	case "skolear":
		return l.Skolear
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Eksamensvurdering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Eksamensvurdering) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EksamensvurderingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EksamensvurderingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Eksamensvurdering) IDFieldNames() []string { return EksamensvurderingIDFieldNames }

// EksamensvurderingRelations is the runtime metadata for Eksamensvurdering's relations
// (own and inherited, flattened).
var EksamensvurderingRelations = []runtime.Relation{
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "1",
	},
	{
		Name:         "elevvurdering",
		Target:       "utdanning-vurdering:Elevvurdering",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensvurdering",
		},
	},
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "1",
	},
	{
		Name:         "karakter",
		Target:       "utdanning-vurdering:Karakterverdi",
		Multiplicity: "0..1",
	},
	{
		Name:         "karakterhistorie",
		Target:       "utdanning-vurdering:Karakterhistorie",
		Multiplicity: "0..1",
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Eksamensvurdering) Relations() []runtime.Relation { return EksamensvurderingRelations }

func init() {
	runtime.Register("utdanning-vurdering:Eksamensvurdering", func() runtime.Resource { return &Eksamensvurdering{} })
}
