// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Eksamensgruppemedlemskap

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Eksamensgruppemedlemskap is the FINT utdanning-vurdering type Eksamensgruppemedlemskap.
//
// Medlemskap i eksamensgrupper.
//
// # Beskrivelse
//
// Gruppemedlemskap som knytter sammen elevforhold og eksamensgrupper.
type Eksamensgruppemedlemskap struct {
	Delegert          *bool                                  `json:"delegert,omitempty"`
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kandidatnummer    *string                                `json:"kandidatnummer,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links EksamensgruppemedlemskapLinks `json:"_links,omitempty"`
}

// EksamensgruppemedlemskapLinks is the typed _links envelope for Eksamensgruppemedlemskap.
type EksamensgruppemedlemskapLinks struct {
	Betalingsstatus   []runtime.Link `json:"betalingsstatus,omitempty"`
	DelegertTil       []runtime.Link `json:"delegertTil,omitempty"`
	Eksamensgruppe    []runtime.Link `json:"eksamensgruppe,omitempty"`
	Elevforhold       []runtime.Link `json:"elevforhold,omitempty"`
	ForetrukketSensor []runtime.Link `json:"foretrukketSensor,omitempty"`
	ForetrukketSkole  []runtime.Link `json:"foretrukketSkole,omitempty"`
	Nus               []runtime.Link `json:"nus,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Eksamensgruppemedlemskap.
func (l EksamensgruppemedlemskapLinks) ByName(name string) []runtime.Link {
	switch name {
	case "betalingsstatus":
		return l.Betalingsstatus
	case "delegertTil":
		return l.DelegertTil
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "elevforhold":
		return l.Elevforhold
	case "foretrukketSensor":
		return l.ForetrukketSensor
	case "foretrukketSkole":
		return l.ForetrukketSkole
	case "nus":
		return l.Nus
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Eksamensgruppemedlemskap) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Eksamensgruppemedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EksamensgruppemedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EksamensgruppemedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Eksamensgruppemedlemskap) IDFieldNames() []string { return EksamensgruppemedlemskapIDFieldNames }

// EksamensgruppemedlemskapRelations is the runtime metadata for Eksamensgruppemedlemskap's relations
// (own and inherited, flattened).
var EksamensgruppemedlemskapRelations = []runtime.Relation{
	{
		Name:         "betalingsstatus",
		Target:       "utdanning-kodeverk:Betalingsstatus",
		Multiplicity: "0..1",
	},
	{
		Name:         "delegertTil",
		Target:       "felles-kodeverk:Fylke",
		Multiplicity: "0..1",
	},
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "gruppemedlemskap",
		},
	},
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensgruppemedlemskap",
		},
	},
	{
		Name:         "foretrukketSensor",
		Target:       "utdanning-vurdering:Sensor",
		Multiplicity: "0..1",
	},
	{
		Name:         "foretrukketSkole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "0..1",
	},
	{
		Name:         "nus",
		Target:       "utdanning-kodeverk:Karakterstatus",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Eksamensgruppemedlemskap) Relations() []runtime.Relation {
	return EksamensgruppemedlemskapRelations
}

func init() {
	runtime.Register("utdanning-vurdering:Eksamensgruppemedlemskap", func() runtime.Resource { return &Eksamensgruppemedlemskap{} })
}
