// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Eksamensgruppe

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Eksamensgruppe is the FINT utdanning-vurdering type Eksamensgruppe.
//
// # Gruppering av elever som tar samme eksamen
//
// # Beskrivelse
//
// Underordnet til fag.
//
// Kan brukes for å:
// * Vise forhold mellom eksamensresultat og sensor
// * Vise gruppering av elever som tok eksamen sammen
//
// Det er også mulig å koble resultater av eksamener direkte på klasse `Fag`.
//
// Eksamensgrupper har en kode som er sentralt definert av VIGO.
type Eksamensgruppe struct {
	Beskrivelse  string                                 `json:"beskrivelse"`
	Eksamensdato *time.Time                             `json:"eksamensdato,omitempty"`
	Navn         string                                 `json:"navn"`
	SystemID     felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links EksamensgruppeLinks `json:"_links,omitempty"`
}

// EksamensgruppeLinks is the typed _links envelope for Eksamensgruppe.
type EksamensgruppeLinks struct {
	Eksamen              []runtime.Link `json:"eksamen,omitempty"`
	Eksamensform         []runtime.Link `json:"eksamensform,omitempty"`
	Fag                  []runtime.Link `json:"fag,omitempty"`
	Gruppemedlemskap     []runtime.Link `json:"gruppemedlemskap,omitempty"`
	Sensor               []runtime.Link `json:"sensor,omitempty"`
	Skole                []runtime.Link `json:"skole,omitempty"`
	Skolear              []runtime.Link `json:"skolear,omitempty"`
	Termin               []runtime.Link `json:"termin,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Eksamensgruppe.
func (l EksamensgruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamen":
		return l.Eksamen
	case "eksamensform":
		return l.Eksamensform
	case "fag":
		return l.Fag
	case "gruppemedlemskap":
		return l.Gruppemedlemskap
	case "sensor":
		return l.Sensor
	case "skole":
		return l.Skole
	case "skolear":
		return l.Skolear
	case "termin":
		return l.Termin
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Eksamensgruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Eksamensgruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EksamensgruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EksamensgruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Eksamensgruppe) IDFieldNames() []string { return EksamensgruppeIDFieldNames }

// EksamensgruppeRelations is the runtime metadata for Eksamensgruppe's relations
// (own and inherited, flattened).
var EksamensgruppeRelations = []runtime.Relation{
	{
		Name:         "eksamen",
		Target:       "utdanning-timeplan:Eksamen",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensgruppe",
		},
	},
	{
		Name:         "eksamensform",
		Target:       "utdanning-kodeverk:Eksamensform",
		Multiplicity: "0..1",
	},
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensgruppe",
		},
	},
	{
		Name:         "gruppemedlemskap",
		Target:       "utdanning-vurdering:Eksamensgruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "eksamensgruppe",
		},
	},
	{
		Name:         "sensor",
		Target:       "utdanning-vurdering:Sensor",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "eksamensgruppe",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensgruppe",
		},
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
	{
		Name:         "termin",
		Target:       "utdanning-kodeverk:Termin",
		Multiplicity: "1",
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "eksamensgruppe",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Eksamensgruppe) Relations() []runtime.Relation { return EksamensgruppeRelations }

func init() {
	runtime.Register("utdanning-vurdering:Eksamensgruppe", func() runtime.Resource { return &Eksamensgruppe{} })
}
