// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Elevfravar

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Elevfravar is the FINT utdanning-vurdering type Elevfravar.
//
// Manglende tilstedeværelse i opplæringen.
//
// # Beskrivelse
//
// Fravær føres med relasjon til den undervisningen eleven har vært fraværende fra.
//
// # Fraværsgrense
//
// * Elever i videregående skole skal møte opp og delta aktivt i opplæringen.
// * Fravær skal registreres, og det foreligger grenser på hvor mye fravær som tillates før rett til å få halvårsvurdering med karakter eller standpunktkarakter i et fag bortfaller.
// * Eleven må legge fram relevant dokumentasjon for å få fravær unntatt fra fraværsgrensen.
// * Fraværsgrensen gjelder timefravær i enkeltfag, ikke elevenes totale fravær.
// * Eleven skal få et varsel om han eller hun står i fare for å ikke få karakter på grunn av fravær.
//
// # Fravær eksamen
// Det føres ikke lenger fravær på eksamen. Dette vil bli satt som karakter. Pga dette utgår relasjonen til eksamensgruppe. Ved en senere hovedoppdatering av Informasjonsmodellen vil multiplisitet for relasjonen  undervisningsgruppe bli satt til 1.
//
// # Referanser
//
// * UDir Registreringshåndbok: http://regbok.udir.no/35004/3344/35042-1018643.html
// * Forskrift til opplæringslova &#167; 3-3, siste ledd: https://lovdata.no/forskrift/2006-06-23-724/&#167;3-3
// * Forskrift til opplæringslova &#167; 3-47: https://lovdata.no/forskrift/2006-06-23-724/&#167;3-47
// * UDir. Føring av vitnemål og kompetansebevis for videregående opplæring i Kunnskapsløftet, pkt 8: https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/8-fravar/
// * SNL. Fravær: https://snl.no/fravær
// * Rundskriv Udir-3-2016: https://www.udir.no/regelverk-og-tilsyn/finn-regelverk/etter-tema/Vitnemal/fravarsgrense---udir-3-2016/
// * UDir. Fravær i videregående skole: https://www.udir.no/regelverk-og-tilsyn/finn-regelverk/etter-tema/Vitnemal/fravar-i-videregaende-skole/
type Elevfravar struct {
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ElevfravarLinks `json:"_links,omitempty"`
}

// ElevfravarLinks is the typed _links envelope for Elevfravar.
type ElevfravarLinks struct {
	Elevforhold         []runtime.Link `json:"elevforhold,omitempty"`
	Fravarsregistrering []runtime.Link `json:"fravarsregistrering,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Elevfravar.
func (l ElevfravarLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elevforhold":
		return l.Elevforhold
	case "fravarsregistrering":
		return l.Fravarsregistrering
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Elevfravar) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Elevfravar) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ElevfravarIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ElevfravarIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Elevfravar) IDFieldNames() []string { return ElevfravarIDFieldNames }

// ElevfravarRelations is the runtime metadata for Elevfravar's relations
// (own and inherited, flattened).
var ElevfravarRelations = []runtime.Relation{
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fravarsregistreringer",
		},
	},
	{
		Name:         "fravarsregistrering",
		Target:       "utdanning-vurdering:Fravarsregistrering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevfravar",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Elevfravar) Relations() []runtime.Relation { return ElevfravarRelations }

func init() {
	runtime.Register("utdanning-vurdering:Elevfravar", func() runtime.Resource { return &Elevfravar{} })
}
