// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Elevvurdering

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Elevvurdering is the FINT utdanning-vurdering type Elevvurdering.
//
// Vurderingsinformasjon for en elev.
type Elevvurdering struct {
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ElevvurderingLinks `json:"_links,omitempty"`
}

// ElevvurderingLinks is the typed _links envelope for Elevvurdering.
type ElevvurderingLinks struct {
	Eksamensvurdering        []runtime.Link `json:"eksamensvurdering,omitempty"`
	Elevforhold              []runtime.Link `json:"elevforhold,omitempty"`
	Halvarsfagvurdering      []runtime.Link `json:"halvarsfagvurdering,omitempty"`
	Halvarsordensvurdering   []runtime.Link `json:"halvarsordensvurdering,omitempty"`
	Sluttfagvurdering        []runtime.Link `json:"sluttfagvurdering,omitempty"`
	Sluttordensvurdering     []runtime.Link `json:"sluttordensvurdering,omitempty"`
	Underveisfagvurdering    []runtime.Link `json:"underveisfagvurdering,omitempty"`
	Underveisordensvurdering []runtime.Link `json:"underveisordensvurdering,omitempty"`
	Vitnemalsmerknad         []runtime.Link `json:"vitnemalsmerknad,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Elevvurdering.
func (l ElevvurderingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensvurdering":
		return l.Eksamensvurdering
	case "elevforhold":
		return l.Elevforhold
	case "halvarsfagvurdering":
		return l.Halvarsfagvurdering
	case "halvarsordensvurdering":
		return l.Halvarsordensvurdering
	case "sluttfagvurdering":
		return l.Sluttfagvurdering
	case "sluttordensvurdering":
		return l.Sluttordensvurdering
	case "underveisfagvurdering":
		return l.Underveisfagvurdering
	case "underveisordensvurdering":
		return l.Underveisordensvurdering
	case "vitnemalsmerknad":
		return l.Vitnemalsmerknad
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Elevvurdering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Elevvurdering) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ElevvurderingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ElevvurderingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Elevvurdering) IDFieldNames() []string { return ElevvurderingIDFieldNames }

// ElevvurderingRelations is the runtime metadata for Elevvurdering's relations
// (own and inherited, flattened).
var ElevvurderingRelations = []runtime.Relation{
	{
		Name:         "eksamensvurdering",
		Target:       "utdanning-vurdering:Eksamensvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "halvarsfagvurdering",
		Target:       "utdanning-vurdering:Halvarsfagvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "halvarsordensvurdering",
		Target:       "utdanning-vurdering:Halvarsordensvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "sluttfagvurdering",
		Target:       "utdanning-vurdering:Sluttfagvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "sluttordensvurdering",
		Target:       "utdanning-vurdering:Sluttordensvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "underveisfagvurdering",
		Target:       "utdanning-vurdering:Underveisfagvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "underveisordensvurdering",
		Target:       "utdanning-vurdering:Underveisordensvurdering",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "elevvurdering",
		},
	},
	{
		Name:         "vitnemalsmerknad",
		Target:       "utdanning-kodeverk:Vitnemalsmerknad",
		Multiplicity: "0..*",
	},
}

// Relations satisfies runtime.Resource.
func (Elevvurdering) Relations() []runtime.Relation { return ElevvurderingRelations }

func init() {
	runtime.Register("utdanning-vurdering:Elevvurdering", func() runtime.Resource { return &Elevvurdering{} })
}
