// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Fagvurdering

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Fagvurdering is the FINT utdanning-vurdering type Fagvurdering.
//
// Karakterer og andre vurderingsuttrykk.
//
// # Beskrivelse
//
// Vurdering i fag skal ha relasjon til det faget det er foretatt vurdering i.
//
// # Referanser
//
// * UDir. Registreringshåndbok, Karakterer og andre vurderingsuttrykk: [regbok.udir.no/35004/3344/35042-1021153.html](http://regbok.udir.no/35004/3344/35042-1021153.html)
// * Føring av vitnemål og kompetansebevis for videregående opplæring i Kunnskapsløftet 2017. Karakterer og andre vurderingsuttrykk: [https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/5-karakterer-og-andre-vurderingsuttrykk/](https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/5-karakterer-og-andre-vurderingsuttrykk/)
// * Forskrift til opplæringslova &#167; 3-4: [https://lovdata.no/dokument/SF/forskrift/2006-06-23-724/KAPITTEL_4-1#&#167;3-4](https://lovdata.no/dokument/SF/forskrift/2006-06-23-724/KAPITTEL_4-1#&#167;3-4)
type Fagvurdering struct {
	Kommentar      string                                 `json:"kommentar"`
	SystemID       felleskompleksedatatyper.Identifikator `json:"systemId"`
	Vurderingsdato time.Time                              `json:"vurderingsdato"`

	Links FagvurderingLinks `json:"_links,omitempty"`
}

// FagvurderingLinks is the typed _links envelope for Fagvurdering.
type FagvurderingLinks struct {
	Fag      []runtime.Link `json:"fag,omitempty"`
	Karakter []runtime.Link `json:"karakter,omitempty"`
	Skolear  []runtime.Link `json:"skolear,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fagvurdering.
func (l FagvurderingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fag":
		return l.Fag
	case "karakter":
		return l.Karakter
	case "skolear":
		return l.Skolear
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fagvurdering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fagvurdering) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FagvurderingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FagvurderingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fagvurdering) IDFieldNames() []string { return FagvurderingIDFieldNames }

// FagvurderingRelations is the runtime metadata for Fagvurdering's relations
// (own and inherited, flattened).
var FagvurderingRelations = []runtime.Relation{
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "1",
	},
	{
		Name:         "karakter",
		Target:       "utdanning-vurdering:Karakterverdi",
		Multiplicity: "0..1",
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Fagvurdering) Relations() []runtime.Relation { return FagvurderingRelations }

func init() {
	runtime.Register("utdanning-vurdering:Fagvurdering", func() runtime.Resource { return &Fagvurdering{} })
}
