// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Fravarsregistrering

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fravarsregistrering is the FINT utdanning-vurdering type Fravarsregistrering.
//
// Manglende tilstedeværelse i opplæringen.
type Fravarsregistrering struct {
	ForesPaVitnemal bool                                   `json:"foresPaVitnemal"`
	Kommentar       *string                                `json:"kommentar,omitempty"`
	Periode         felleskompleksedatatyper.Periode       `json:"periode"`
	SystemID        felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FravarsregistreringLinks `json:"_links,omitempty"`
}

// FravarsregistreringLinks is the typed _links envelope for Fravarsregistrering.
type FravarsregistreringLinks struct {
	Elevfravar          []runtime.Link `json:"elevfravar,omitempty"`
	Faggruppe           []runtime.Link `json:"faggruppe,omitempty"`
	Fravarstype         []runtime.Link `json:"fravarstype,omitempty"`
	RegistrertAv        []runtime.Link `json:"registrertAv,omitempty"`
	Undervisningsgruppe []runtime.Link `json:"undervisningsgruppe,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fravarsregistrering.
func (l FravarsregistreringLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elevfravar":
		return l.Elevfravar
	case "faggruppe":
		return l.Faggruppe
	case "fravarstype":
		return l.Fravarstype
	case "registrertAv":
		return l.RegistrertAv
	case "undervisningsgruppe":
		return l.Undervisningsgruppe
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fravarsregistrering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fravarsregistrering) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FravarsregistreringIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FravarsregistreringIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fravarsregistrering) IDFieldNames() []string { return FravarsregistreringIDFieldNames }

// FravarsregistreringRelations is the runtime metadata for Fravarsregistrering's relations
// (own and inherited, flattened).
var FravarsregistreringRelations = []runtime.Relation{
	{
		Name:         "elevfravar",
		Target:       "utdanning-vurdering:Elevfravar",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fravarsregistrering",
		},
	},
	{
		Name:         "faggruppe",
		Target:       "utdanning-timeplan:Faggruppe",
		Multiplicity: "0..1",
	},
	{
		Name:         "fravarstype",
		Target:       "utdanning-kodeverk:Fravarstype",
		Multiplicity: "1",
	},
	{
		Name:         "registrertAv",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "undervisningsgruppe",
		Target:       "utdanning-timeplan:Undervisningsgruppe",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Fravarsregistrering) Relations() []runtime.Relation { return FravarsregistreringRelations }

func init() {
	runtime.Register("utdanning-vurdering:Fravarsregistrering", func() runtime.Resource { return &Fravarsregistrering{} })
}
