// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Fravarsprosent

package vurdering

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fravarsprosent is the FINT utdanning-vurdering type Fravarsprosent.
//
// Fraværsdata for en periode.
type Fravarsprosent struct {
	Fravarstimer       int `json:"fravarstimer"`
	Prosent            int `json:"prosent"`
	Undervisningstimer int `json:"undervisningstimer"`
}

// LinksByName satisfies runtime.Resource.
func (r Fravarsprosent) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fravarsprosent) ForEachID(fn func(name, value string) bool) {
}

// FravarsprosentIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FravarsprosentIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Fravarsprosent) IDFieldNames() []string { return FravarsprosentIDFieldNames }

// FravarsprosentRelations is the runtime metadata for Fravarsprosent's relations
// (own and inherited, flattened).
var FravarsprosentRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Fravarsprosent) Relations() []runtime.Relation { return FravarsprosentRelations }

func init() {
	runtime.Register("utdanning-vurdering:Fravarsprosent", func() runtime.Resource { return &Fravarsprosent{} })
}
