// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Karakterverdi

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Karakterverdi is the FINT utdanning-vurdering type Karakterverdi.
//
// # Karakterer, målestokk for vurdering av elevers faglige standpunkt, prøve- eller eksamensprestasjoner
//
// # Beskrivelse
//
// De enkelte karakterer, som til sammen danner en karakterskala, blir betegnet med tall eller andre symboler.
//
// Den relaterte skalaen må refereres fra selve verdi.
//
// # Eksempel
//
// * 6 - Seks
// * IM - Ikke møtt
// * GK - Godkjent
// * R - Realkompetanse
//
// # Referanse
//
// * Vigo Kodeverkdatabase. Karakter: [vigo.no/vigokv/karakter.action](https://www.vigo.no/vigokv/karakter.action)
// * SNL. karakterer: [snl.no/karakterer](https://snl.no/karakterer)
type Karakterverdi struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links KarakterverdiLinks `json:"_links,omitempty"`
}

// KarakterverdiLinks is the typed _links envelope for Karakterverdi.
type KarakterverdiLinks struct {
	Skala []runtime.Link `json:"skala,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Karakterverdi.
func (l KarakterverdiLinks) ByName(name string) []runtime.Link {
	switch name {
	case "skala":
		return l.Skala
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Karakterverdi) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Karakterverdi) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KarakterverdiIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KarakterverdiIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Karakterverdi) IDFieldNames() []string { return KarakterverdiIDFieldNames }

// KarakterverdiRelations is the runtime metadata for Karakterverdi's relations
// (own and inherited, flattened).
var KarakterverdiRelations = []runtime.Relation{
	{
		Name:         "skala",
		Target:       "utdanning-kodeverk:Karakterskala",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "verdi",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Karakterverdi) Relations() []runtime.Relation { return KarakterverdiRelations }

func init() {
	runtime.Register("utdanning-vurdering:Karakterverdi", func() runtime.Resource { return &Karakterverdi{} })
}
