// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Ordensvurdering

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Ordensvurdering is the FINT utdanning-vurdering type Ordensvurdering.
//
// Vurdering av orden og atferd..
//
// # Beskrivelse
//
// Vurderinger av orden og atferd gjøres uten relasjon til noen gruppe, kun til et elevforhold.
//
// # Referanser
//
// * UDir. Registreringshåndbok, Karakterer og andre vurderingsuttrykk: [regbok.udir.no/35004/3344/35042-1021153.html](http://regbok.udir.no/35004/3344/35042-1021153.html)
// * Føring av vitnemål og kompetansebevis for videregående opplæring i Kunnskapsløftet 2017. Karakterer og andre vurderingsuttrykk: [https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/5-karakterer-og-andre-vurderingsuttrykk/](https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/5-karakterer-og-andre-vurderingsuttrykk/)
// * Forskrift til opplæringslova &#167; 3-4: [https://lovdata.no/dokument/SF/forskrift/2006-06-23-724/KAPITTEL_4-1#&#167;3-4](https://lovdata.no/dokument/SF/forskrift/2006-06-23-724/KAPITTEL_4-1#&#167;3-4)
type Ordensvurdering struct {
	Kommentar      string                                 `json:"kommentar"`
	SystemID       felleskompleksedatatyper.Identifikator `json:"systemId"`
	Vurderingsdato time.Time                              `json:"vurderingsdato"`

	Links OrdensvurderingLinks `json:"_links,omitempty"`
}

// OrdensvurderingLinks is the typed _links envelope for Ordensvurdering.
type OrdensvurderingLinks struct {
	Atferd  []runtime.Link `json:"atferd,omitempty"`
	Orden   []runtime.Link `json:"orden,omitempty"`
	Skolear []runtime.Link `json:"skolear,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Ordensvurdering.
func (l OrdensvurderingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "atferd":
		return l.Atferd
	case "orden":
		return l.Orden
	case "skolear":
		return l.Skolear
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Ordensvurdering) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Ordensvurdering) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// OrdensvurderingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var OrdensvurderingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Ordensvurdering) IDFieldNames() []string { return OrdensvurderingIDFieldNames }

// OrdensvurderingRelations is the runtime metadata for Ordensvurdering's relations
// (own and inherited, flattened).
var OrdensvurderingRelations = []runtime.Relation{
	{
		Name:         "atferd",
		Target:       "utdanning-vurdering:Karakterverdi",
		Multiplicity: "1",
	},
	{
		Name:         "orden",
		Target:       "utdanning-vurdering:Karakterverdi",
		Multiplicity: "1",
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Ordensvurdering) Relations() []runtime.Relation { return OrdensvurderingRelations }

func init() {
	runtime.Register("utdanning-vurdering:Ordensvurdering", func() runtime.Resource { return &Ordensvurdering{} })
}
