// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-vurdering:Sensor

package vurdering

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Sensor is the FINT utdanning-vurdering type Sensor.
//
// Skoleressurs som sensurerer eksamensbesvarelser.
type Sensor struct {
	Aktiv        bool                                   `json:"aktiv"`
	Sensornummer *int                                   `json:"sensornummer,omitempty"`
	SystemID     felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links SensorLinks `json:"_links,omitempty"`
}

// SensorLinks is the typed _links envelope for Sensor.
type SensorLinks struct {
	Eksamensgruppe []runtime.Link `json:"eksamensgruppe,omitempty"`
	Skoleressurs   []runtime.Link `json:"skoleressurs,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Sensor.
func (l SensorLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "skoleressurs":
		return l.Skoleressurs
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Sensor) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Sensor) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SensorIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SensorIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Sensor) IDFieldNames() []string { return SensorIDFieldNames }

// SensorRelations is the runtime metadata for Sensor's relations
// (own and inherited, flattened).
var SensorRelations = []runtime.Relation{
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "sensor",
		},
	},
	{
		Name:         "skoleressurs",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "sensor",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Sensor) Relations() []runtime.Relation { return SensorRelations }

func init() {
	runtime.Register("utdanning-vurdering:Sensor", func() runtime.Resource { return &Sensor{} })
}
