// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kompleksedatatyper:Adresse

package kompleksedatatyper

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Adresse is the FINT felles-kompleksedatatyper type Adresse.
//
// Fysisk adresse eller postadresse.
//
// # Beskrivelse
//
// Dette kan enten være en postadresse eller en fysisk adresse som det er mulig å besøke.
//
// # Eksempel
//
// |               adresse               |    poststed    | postnummer | land |
// |-------------------------------------|----------------|------------|------|
// | Nydalen allé 11                     | Oslo           |       0484 | NO   |
// | Fakturamottak&lt;br&gt;Postboks 501 Lund  | Kristiansand   |       4605 | -    |
// | Postboks 517 Lundsiden              | KRISTIANSAND S |       4605 | -    |
//
// # Referanser
//
// - http://www.bring.no/radgivning/sende-noe/klargjoring/klargjoring-adressert/adressering-til-postmottakere-i-norge
// - http://www.bring.no/radgivning/sende-noe/klargjoring/klargjoring-adressert/adressering-til-mottakere-i-utlandet
type Adresse struct {
	Adresselinje []string `json:"adresselinje,omitempty"`
	Postnummer   *string  `json:"postnummer,omitempty"`
	Poststed     *string  `json:"poststed,omitempty"`

	Links AdresseLinks `json:"_links,omitempty"`
}

// AdresseLinks is the typed _links envelope for Adresse.
type AdresseLinks struct {
	Land []runtime.Link `json:"land,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Adresse.
func (l AdresseLinks) ByName(name string) []runtime.Link {
	switch name {
	case "land":
		return l.Land
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Adresse) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Adresse) ForEachID(fn func(name, value string) bool) {
}

// AdresseIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AdresseIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Adresse) IDFieldNames() []string { return AdresseIDFieldNames }

// AdresseRelations is the runtime metadata for Adresse's relations
// (own and inherited, flattened).
var AdresseRelations = []runtime.Relation{
	{
		Name:         "land",
		Target:       "felles-kodeverk-iso:Landkode",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Adresse) Relations() []runtime.Relation { return AdresseRelations }

func init() {
	runtime.Register("felles-kompleksedatatyper:Adresse", func() runtime.Resource { return &Adresse{} })
}
