// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kompleksedatatyper:Identifikator

package kompleksedatatyper

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Identifikator is the FINT felles-kompleksedatatyper type Identifikator.
//
// Unik identifikasjon til et objekt.
//
// # Beskrivelse
//
// En kombinasjon av tegn eller og/eller bokstaver som unikt identifiserer et objekt blant andre objekter av samme type uten arv.
//
// Identifikatorer må være stabile over tid, og henvise til samme objekt.
//
// Dersom identifikatorer konstrueres av sammensatte verdier må særskilt hensyn tas for å sikre at identifikatorverdien ikke endres over tid.
//
// # Eksempel
//
// Kan for eksempel brukes til å identifisere en person ut fra fødselsnummer eller ansattnummer.
//
// * For en person kan det være fødselsnummer
// * For er personresurs kan det være ansattnummer eller signatur
// * For er elev kan det være elevnummer.
// * For organisasjonselement kan det være organisasjonsnummer fra Enhetsregistret.
// * systemId kan være objektID eller rowID i underliggende database, dersom denne er stabil over tid.
type Identifikator struct {
	Gyldighetsperiode  *Periode `json:"gyldighetsperiode,omitempty"`
	Identifikatorverdi string   `json:"identifikatorverdi"`
}

// LinksByName satisfies runtime.Resource.
func (r Identifikator) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Identifikator) ForEachID(fn func(name, value string) bool) {
}

// IdentifikatorIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var IdentifikatorIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Identifikator) IDFieldNames() []string { return IdentifikatorIDFieldNames }

// IdentifikatorRelations is the runtime metadata for Identifikator's relations
// (own and inherited, flattened).
var IdentifikatorRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Identifikator) Relations() []runtime.Relation { return IdentifikatorRelations }

func init() {
	runtime.Register("felles-kompleksedatatyper:Identifikator", func() runtime.Resource { return &Identifikator{} })
}
