// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kompleksedatatyper:Matrikkelnummer

package kompleksedatatyper

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Matrikkelnummer is the FINT felles-kompleksedatatyper type Matrikkelnummer.
//
// Entydig identifisering av metrikkelenhet innen kommune, definert i matrikkelforskriften § 7.
type Matrikkelnummer struct {
	Adresse        *Adresse `json:"adresse,omitempty"`
	Bruksnummer    *string  `json:"bruksnummer,omitempty"`
	Festenummer    *string  `json:"festenummer,omitempty"`
	Gardsnummer    *string  `json:"gardsnummer,omitempty"`
	Seksjonsnummer *string  `json:"seksjonsnummer,omitempty"`

	Links MatrikkelnummerLinks `json:"_links,omitempty"`
}

// MatrikkelnummerLinks is the typed _links envelope for Matrikkelnummer.
type MatrikkelnummerLinks struct {
	Kommunenummer []runtime.Link `json:"kommunenummer,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Matrikkelnummer.
func (l MatrikkelnummerLinks) ByName(name string) []runtime.Link {
	switch name {
	case "kommunenummer":
		return l.Kommunenummer
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Matrikkelnummer) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Matrikkelnummer) ForEachID(fn func(name, value string) bool) {
}

// MatrikkelnummerIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var MatrikkelnummerIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Matrikkelnummer) IDFieldNames() []string { return MatrikkelnummerIDFieldNames }

// MatrikkelnummerRelations is the runtime metadata for Matrikkelnummer's relations
// (own and inherited, flattened).
var MatrikkelnummerRelations = []runtime.Relation{
	{
		Name:         "kommunenummer",
		Target:       "felles-kodeverk:Kommune",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Matrikkelnummer) Relations() []runtime.Relation { return MatrikkelnummerRelations }

func init() {
	runtime.Register("felles-kompleksedatatyper:Matrikkelnummer", func() runtime.Resource { return &Matrikkelnummer{} })
}
