// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   felles-kompleksedatatyper:Personnavn

package kompleksedatatyper

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Personnavn is the FINT felles-kompleksedatatyper type Personnavn.
//
// # Angir navn til en person
//
// # Beskrivelse
//
// Inneholder fornavn og etternavn for å beskrive navn til en person.
//
// Fornavn, mellomnavn og etternavn skal leveres fra fagsystemene som de er, uten noe endringer.
//
// # Referanse
//
// * [Navneloven](https://lovdata.no/dokument/NL/lov/2002-06-07-19/)
// * [Håndbok i folkeregistrering](http://www.skatteetaten.no/no/Radgiver/Rettskilder/Handboker/Handbok-i-folkeregistrering/)
// * [Skal du ha to etternavn?](http://www.skatteetaten.no/no/Person/Folkeregister/Endre-navn/Skal-du-ha-to-etternavn/)
//
// # Eksempler
//
// |            Navn           |       Fornavn       | Mellomnavn | Etternavn   |
// |---------------------------|---------------------|------------|--------------|
// | Ole Olsen                 | Ole                 | -          | Olsen        |
// | Lise Sofie Fuglevik Olsen | Lise Sofie          | Fuglevik   | Olsen        |
// | Lise Sofie Fuglevik Olsen | Lise Sofie Fuglevik | -          | Olsen        |
// | Anne Kari Nilsen-Olsen    | Anne Kari           | -          | Nilsen-Olsen |
type Personnavn struct {
	Etternavn  string  `json:"etternavn"`
	Fornavn    string  `json:"fornavn"`
	Mellomnavn *string `json:"mellomnavn,omitempty"`
}

// LinksByName satisfies runtime.Resource.
func (r Personnavn) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Personnavn) ForEachID(fn func(name, value string) bool) {
}

// PersonnavnIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersonnavnIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Personnavn) IDFieldNames() []string { return PersonnavnIDFieldNames }

// PersonnavnRelations is the runtime metadata for Personnavn's relations
// (own and inherited, flattened).
var PersonnavnRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Personnavn) Relations() []runtime.Relation { return PersonnavnRelations }

func init() {
	runtime.Register("felles-kompleksedatatyper:Personnavn", func() runtime.Resource { return &Personnavn{} })
}
