// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-personal:Arbeidsforhold

package personal

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arbeidsforhold is the FINT administrasjon-personal type Arbeidsforhold.
//
// # Arbeidsforhold er et avtaleforhold mellom personalressurs og arbeidsgiver
//
// # Beskrivelse
//
// Arbeidsforhold defineres som et avtaleforhold hvor den ene part (arbeidstakeren / personalressurs) forplikter seg til å utføre arbeid for den annen part (arbeidsgiveren / organisasjonselement). Arbeidsforholdet kan også utføres av en person fra vikarbyrå, eller et firma gjennom en kontrakt/avtale.
//
// # Eksempler
//
// * Ansatt som rådgiver i fast stilling
// * Vikariat for en annen person som er i permisjon fra sitt arbeidsforhold
type Arbeidsforhold struct {
	Ansettelsesprosent     int64                                  `json:"ansettelsesprosent"`
	Arbeidsforholdsperiode *felleskompleksedatatyper.Periode      `json:"arbeidsforholdsperiode,omitempty"`
	Arslonn                int64                                  `json:"arslonn"`
	Gyldighetsperiode      felleskompleksedatatyper.Periode       `json:"gyldighetsperiode"`
	Hovedstilling          bool                                   `json:"hovedstilling"`
	Lonnsprosent           int64                                  `json:"lonnsprosent"`
	Stillingsnummer        string                                 `json:"stillingsnummer"`
	Stillingstittel        *string                                `json:"stillingstittel,omitempty"`
	SystemID               felleskompleksedatatyper.Identifikator `json:"systemId"`
	Tilstedeprosent        int64                                  `json:"tilstedeprosent"`

	Links ArbeidsforholdLinks `json:"_links,omitempty"`
}

// ArbeidsforholdLinks is the typed _links envelope for Arbeidsforhold.
type ArbeidsforholdLinks struct {
	Aktivitet            []runtime.Link `json:"aktivitet,omitempty"`
	Anlegg               []runtime.Link `json:"anlegg,omitempty"`
	Ansvar               []runtime.Link `json:"ansvar,omitempty"`
	Arbeidsforholdstype  []runtime.Link `json:"arbeidsforholdstype,omitempty"`
	Arbeidslokasjon      []runtime.Link `json:"arbeidslokasjon,omitempty"`
	Arbeidssted          []runtime.Link `json:"arbeidssted,omitempty"`
	Art                  []runtime.Link `json:"art,omitempty"`
	Diverse              []runtime.Link `json:"diverse,omitempty"`
	Fastlonn             []runtime.Link `json:"fastlonn,omitempty"`
	Fasttillegg          []runtime.Link `json:"fasttillegg,omitempty"`
	Formal               []runtime.Link `json:"formal,omitempty"`
	Fravar               []runtime.Link `json:"fravar,omitempty"`
	Funksjon             []runtime.Link `json:"funksjon,omitempty"`
	Kontrakt             []runtime.Link `json:"kontrakt,omitempty"`
	Lopenummer           []runtime.Link `json:"lopenummer,omitempty"`
	Objekt               []runtime.Link `json:"objekt,omitempty"`
	Personalleder        []runtime.Link `json:"personalleder,omitempty"`
	Personalressurs      []runtime.Link `json:"personalressurs,omitempty"`
	Prosjekt             []runtime.Link `json:"prosjekt,omitempty"`
	Ramme                []runtime.Link `json:"ramme,omitempty"`
	Stillingskode        []runtime.Link `json:"stillingskode,omitempty"`
	TimerPerUke          []runtime.Link `json:"timerPerUke,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
	Variabellonn         []runtime.Link `json:"variabellonn,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arbeidsforhold.
func (l ArbeidsforholdLinks) ByName(name string) []runtime.Link {
	switch name {
	case "aktivitet":
		return l.Aktivitet
	case "anlegg":
		return l.Anlegg
	case "ansvar":
		return l.Ansvar
	case "arbeidsforholdstype":
		return l.Arbeidsforholdstype
	case "arbeidslokasjon":
		return l.Arbeidslokasjon
	case "arbeidssted":
		return l.Arbeidssted
	case "art":
		return l.Art
	case "diverse":
		return l.Diverse
	case "fastlonn":
		return l.Fastlonn
	case "fasttillegg":
		return l.Fasttillegg
	case "formal":
		return l.Formal
	case "fravar":
		return l.Fravar
	case "funksjon":
		return l.Funksjon
	case "kontrakt":
		return l.Kontrakt
	case "lopenummer":
		return l.Lopenummer
	case "objekt":
		return l.Objekt
	case "personalleder":
		return l.Personalleder
	case "personalressurs":
		return l.Personalressurs
	case "prosjekt":
		return l.Prosjekt
	case "ramme":
		return l.Ramme
	case "stillingskode":
		return l.Stillingskode
	case "timerPerUke":
		return l.TimerPerUke
	case "undervisningsforhold":
		return l.Undervisningsforhold
	case "variabellonn":
		return l.Variabellonn
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arbeidsforhold) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arbeidsforhold) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ArbeidsforholdIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArbeidsforholdIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Arbeidsforhold) IDFieldNames() []string { return ArbeidsforholdIDFieldNames }

// ArbeidsforholdRelations is the runtime metadata for Arbeidsforhold's relations
// (own and inherited, flattened).
var ArbeidsforholdRelations = []runtime.Relation{
	{
		Name:         "aktivitet",
		Target:       "administrasjon-kodeverk:Aktivitet",
		Multiplicity: "0..1",
	},
	{
		Name:         "anlegg",
		Target:       "administrasjon-kodeverk:Anlegg",
		Multiplicity: "0..1",
	},
	{
		Name:         "ansvar",
		Target:       "administrasjon-kodeverk:Ansvar",
		Multiplicity: "0..1",
	},
	{
		Name:         "arbeidsforholdstype",
		Target:       "administrasjon-kodeverk:Arbeidsforholdstype",
		Multiplicity: "0..1",
	},
	{
		Name:         "arbeidslokasjon",
		Target:       "administrasjon-organisasjon:Arbeidslokasjon",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "arbeidssted",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "art",
		Target:       "administrasjon-kodeverk:Art",
		Multiplicity: "0..1",
	},
	{
		Name:         "diverse",
		Target:       "administrasjon-kodeverk:Diverse",
		Multiplicity: "0..1",
	},
	{
		Name:         "fastlonn",
		Target:       "administrasjon-personal:Fastlonn",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "fasttillegg",
		Target:       "administrasjon-personal:Fasttillegg",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "formal",
		Target:       "administrasjon-kodeverk:Formal",
		Multiplicity: "0..1",
	},
	{
		Name:         "fravar",
		Target:       "administrasjon-personal:Fravar",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "funksjon",
		Target:       "administrasjon-kodeverk:Funksjon",
		Multiplicity: "0..1",
	},
	{
		Name:         "kontrakt",
		Target:       "administrasjon-kodeverk:Kontrakt",
		Multiplicity: "0..1",
	},
	{
		Name:         "lopenummer",
		Target:       "administrasjon-kodeverk:Lopenummer",
		Multiplicity: "0..1",
	},
	{
		Name:         "objekt",
		Target:       "administrasjon-kodeverk:Objekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "personalleder",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "personalansvar",
		},
	},
	{
		Name:         "personalressurs",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "prosjekt",
		Target:       "administrasjon-kodeverk:Prosjekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "ramme",
		Target:       "administrasjon-kodeverk:Ramme",
		Multiplicity: "0..1",
	},
	{
		Name:         "stillingskode",
		Target:       "administrasjon-kodeverk:Stillingskode",
		Multiplicity: "0..1",
	},
	{
		Name:         "timerPerUke",
		Target:       "administrasjon-kodeverk:Uketimetall",
		Multiplicity: "0..1",
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
	{
		Name:         "variabellonn",
		Target:       "administrasjon-personal:Variabellonn",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "arbeidsforhold",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Arbeidsforhold) Relations() []runtime.Relation { return ArbeidsforholdRelations }

func init() {
	runtime.Register("administrasjon-personal:Arbeidsforhold", func() runtime.Resource { return &Arbeidsforhold{} })
}
