// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-personal:Fastlonn

package personal

import (
	administrasjonkompleksedatatyper "github.com/FINTLabs/fint-model-go/administrasjon/kompleksedatatyper"
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Fastlonn is the FINT administrasjon-personal type Fastlonn.
//
// Informasjon om fast lønnsbeskjeftigelse.
//
// Inneholder beskjeftigelse av den ansattes lønnsprosent.
//
// Summen av prosentene på beskjeftigelsene skal være lønnsprosent for en fullt dekket stilling.
//
// Dersom beskjeftigelsene ikke fyller lønnsprosenten har arbeidsforholdet teknisk undertid.
//
// I motsatt fall har arbeidsforholdet overtid.
//
// # Lovlige endringer
//
// ## Opprettelse av ny fastlønn
//
// - `periode` angir periode som beskjeftigelsen skal gjelde for.
// - Periode uten `slutt` betyr at beskjeftigelsen gjelder inntil videre.
//
// ## Endring av eksisterende fastlønn
//
// - Kun endring av `slutt` på `periode` er lovlig.
//
// ## Sletting av eksisterende fastlønn
//
// - Ikke tillatt.
type Fastlonn struct {
	Anvist        *time.Time                                   `json:"anvist,omitempty"`
	Attestert     *time.Time                                   `json:"attestert,omitempty"`
	Beskrivelse   string                                       `json:"beskrivelse"`
	KildesystemID *felleskompleksedatatyper.Identifikator      `json:"kildesystemId,omitempty"`
	Kontert       *time.Time                                   `json:"kontert,omitempty"`
	Kontostreng   administrasjonkompleksedatatyper.Kontostreng `json:"kontostreng"`
	Opptjent      *felleskompleksedatatyper.Periode            `json:"opptjent,omitempty"`
	Periode       felleskompleksedatatyper.Periode             `json:"periode"`
	Prosent       int64                                        `json:"prosent"`
	SystemID      *felleskompleksedatatyper.Identifikator      `json:"systemId,omitempty"`

	Links FastlonnLinks `json:"_links,omitempty"`
}

// FastlonnLinks is the typed _links envelope for Fastlonn.
type FastlonnLinks struct {
	Anviser        []runtime.Link `json:"anviser,omitempty"`
	Arbeidsforhold []runtime.Link `json:"arbeidsforhold,omitempty"`
	Attestant      []runtime.Link `json:"attestant,omitempty"`
	Konterer       []runtime.Link `json:"konterer,omitempty"`
	Lonnsart       []runtime.Link `json:"lonnsart,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fastlonn.
func (l FastlonnLinks) ByName(name string) []runtime.Link {
	switch name {
	case "anviser":
		return l.Anviser
	case "arbeidsforhold":
		return l.Arbeidsforhold
	case "attestant":
		return l.Attestant
	case "konterer":
		return l.Konterer
	case "lonnsart":
		return l.Lonnsart
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fastlonn) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fastlonn) ForEachID(fn func(name, value string) bool) {
	if r.KildesystemID != nil && !fn("kildesystemId", r.KildesystemID.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FastlonnIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FastlonnIDFieldNames = []string{
	"kildesystemId",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fastlonn) IDFieldNames() []string { return FastlonnIDFieldNames }

// FastlonnRelations is the runtime metadata for Fastlonn's relations
// (own and inherited, flattened).
var FastlonnRelations = []runtime.Relation{
	{
		Name:         "anviser",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "arbeidsforhold",
		Target:       "administrasjon-personal:Arbeidsforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fastlonn",
		},
	},
	{
		Name:         "attestant",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "konterer",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "0..1",
	},
	{
		Name:         "lonnsart",
		Target:       "administrasjon-kodeverk:Lonnsart",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Fastlonn) Relations() []runtime.Relation { return FastlonnRelations }

func init() {
	runtime.Register("administrasjon-personal:Fastlonn", func() runtime.Resource { return &Fastlonn{} })
}
