// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-personal:Personalressurs

package personal

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Personalressurs is the FINT administrasjon-personal type Personalressurs.
//
// # Arbeidstaker eller oppdragstaker i organisasjonen
//
// # Beskrivelse
//
// Personalressurs er personer som leverer tjenester i form av å være ansatt. Personalressursen kan også være en person fra vikarbyrå, eller et firma som bekler et arbeidsforhold gjennom en kontrakt/avtale. Registrert i HR-systemet.
//
// # Eksempler
//
// * *ordinære* ansatte i faste og midlertidige stillinger
// * oppdragstakere:
//   - politikere
//   - ressurser med timelønn
//   - sensorer
//   - eksamensvakt
//   - hospitant
//
// Inneholder i utgangspunktet ikke *leverandørrepresenanter* (ekstern vikar, foredragsholdere, konsulenter).
type Personalressurs struct {
	Ansattnummer       felleskompleksedatatyper.Identifikator       `json:"ansattnummer"`
	Ansettelsesperiode felleskompleksedatatyper.Periode             `json:"ansettelsesperiode"`
	Ansiennitet        *time.Time                                   `json:"ansiennitet,omitempty"`
	Brukernavn         *felleskompleksedatatyper.Identifikator      `json:"brukernavn,omitempty"`
	Jobbtittel         *string                                      `json:"jobbtittel,omitempty"`
	Kontaktinformasjon *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	SystemID           *felleskompleksedatatyper.Identifikator      `json:"systemId,omitempty"`

	Links PersonalressursLinks `json:"_links,omitempty"`
}

// PersonalressursLinks is the typed _links envelope for Personalressurs.
type PersonalressursLinks struct {
	Arbeidsforhold          []runtime.Link `json:"arbeidsforhold,omitempty"`
	Fullmakt                []runtime.Link `json:"fullmakt,omitempty"`
	Leder                   []runtime.Link `json:"leder,omitempty"`
	Person                  []runtime.Link `json:"person,omitempty"`
	Personalansvar          []runtime.Link `json:"personalansvar,omitempty"`
	Personalressurskategori []runtime.Link `json:"personalressurskategori,omitempty"`
	Skoleressurs            []runtime.Link `json:"skoleressurs,omitempty"`
	Stedfortreder           []runtime.Link `json:"stedfortreder,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Personalressurs.
func (l PersonalressursLinks) ByName(name string) []runtime.Link {
	switch name {
	case "arbeidsforhold":
		return l.Arbeidsforhold
	case "fullmakt":
		return l.Fullmakt
	case "leder":
		return l.Leder
	case "person":
		return l.Person
	case "personalansvar":
		return l.Personalansvar
	case "personalressurskategori":
		return l.Personalressurskategori
	case "skoleressurs":
		return l.Skoleressurs
	case "stedfortreder":
		return l.Stedfortreder
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Personalressurs) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Personalressurs) ForEachID(fn func(name, value string) bool) {
	if !fn("ansattnummer", r.Ansattnummer.Identifikatorverdi) {
		return
	}
	if r.Brukernavn != nil && !fn("brukernavn", r.Brukernavn.Identifikatorverdi) {
		return
	}
	if r.SystemID != nil && !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PersonalressursIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersonalressursIDFieldNames = []string{
	"ansattnummer",
	"brukernavn",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Personalressurs) IDFieldNames() []string { return PersonalressursIDFieldNames }

// PersonalressursRelations is the runtime metadata for Personalressurs's relations
// (own and inherited, flattened).
var PersonalressursRelations = []runtime.Relation{
	{
		Name:         "arbeidsforhold",
		Target:       "administrasjon-personal:Arbeidsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "personalressurs",
		},
	},
	{
		Name:         "fullmakt",
		Target:       "administrasjon-fullmakt:Fullmakt",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fullmektig",
		},
	},
	{
		Name:         "leder",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "leder",
		},
	},
	{
		Name:         "person",
		Target:       "felles:Person",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "personalressurs",
		},
	},
	{
		Name:         "personalansvar",
		Target:       "administrasjon-personal:Arbeidsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "personalleder",
		},
	},
	{
		Name:         "personalressurskategori",
		Target:       "administrasjon-kodeverk:Personalressurskategori",
		Multiplicity: "1",
	},
	{
		Name:         "skoleressurs",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "personalressurs",
		},
	},
	{
		Name:         "stedfortreder",
		Target:       "administrasjon-fullmakt:Fullmakt",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "stedfortreder",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Personalressurs) Relations() []runtime.Relation { return PersonalressursRelations }

func init() {
	runtime.Register("administrasjon-personal:Personalressurs", func() runtime.Resource { return &Personalressurs{} })
}
