apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fint-link-walker-client-ORG
  namespace: fint-core
  labels:
    fintlabs.no/team: core
    fintlabs.no/org-id: ORG
spec:
  itemPath: ITEM_PATH
