// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Ansvar

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Ansvar is the FINT administrasjon-kodeverk type Ansvar.
//
// # Kodeverk som er en del av kontostrengen som beskriver hvem som har ansvaret for en utgift eller en inntekt
//
// # Beskrivelse
//
// Ansvar viser hvordan ansvaret i organisasjonen er bygd opp i samsvar med fylkeskommunens anvisningsmyndighet.
//
// Alternative navn: `Kostsenter`, `Koststed`.
type Ansvar struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links AnsvarLinks `json:"_links,omitempty"`
}

// AnsvarLinks is the typed _links envelope for Ansvar.
type AnsvarLinks struct {
	Organisasjonselement []runtime.Link `json:"organisasjonselement,omitempty"`
	Overordnet           []runtime.Link `json:"overordnet,omitempty"`
	Underordnet          []runtime.Link `json:"underordnet,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Ansvar.
func (l AnsvarLinks) ByName(name string) []runtime.Link {
	switch name {
	case "organisasjonselement":
		return l.Organisasjonselement
	case "overordnet":
		return l.Overordnet
	case "underordnet":
		return l.Underordnet
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Ansvar) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Ansvar) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// AnsvarIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AnsvarIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Ansvar) IDFieldNames() []string { return AnsvarIDFieldNames }

// AnsvarRelations is the runtime metadata for Ansvar's relations
// (own and inherited, flattened).
var AnsvarRelations = []runtime.Relation{
	{
		Name:         "organisasjonselement",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "ansvar",
		},
	},
	{
		Name:         "overordnet",
		Target:       "administrasjon-kodeverk:Ansvar",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "underordnet",
		},
	},
	{
		Name:         "underordnet",
		Target:       "administrasjon-kodeverk:Ansvar",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "overordnet",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Ansvar) Relations() []runtime.Relation { return AnsvarRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Ansvar", func() runtime.Resource { return &Ansvar{} })
}
