// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Arbeidsforholdstype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arbeidsforholdstype is the FINT administrasjon-kodeverk type Arbeidsforholdstype.
//
// # Viser hvilket behov hos arbeidsgiver som dekkes av arbeidsforholdet
//
// # Beskrivelse
//
// # Viser hvilket behov hos arbeidsgiver som dekkes av arbeidsforholdet
//
// Alternative navn:
// * Stillingstype
// * Stillingskategori
// * Ansattforholdkode
//
// # Eksempel
//
// Kode | Beskrivelse
// ---|---
// A   |     Fast
// B    |    Timelønnet
// C   |     Lærlinger
// D   |     Folkevalgt/politiker
// E    |    Midlertidig
// ...   | ...
// Z    |    Annet
type Arbeidsforholdstype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ArbeidsforholdstypeLinks `json:"_links,omitempty"`
}

// ArbeidsforholdstypeLinks is the typed _links envelope for Arbeidsforholdstype.
type ArbeidsforholdstypeLinks struct {
	Forelder []runtime.Link `json:"forelder,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arbeidsforholdstype.
func (l ArbeidsforholdstypeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "forelder":
		return l.Forelder
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arbeidsforholdstype) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arbeidsforholdstype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ArbeidsforholdstypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArbeidsforholdstypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Arbeidsforholdstype) IDFieldNames() []string { return ArbeidsforholdstypeIDFieldNames }

// ArbeidsforholdstypeRelations is the runtime metadata for Arbeidsforholdstype's relations
// (own and inherited, flattened).
var ArbeidsforholdstypeRelations = []runtime.Relation{
	{
		Name:         "forelder",
		Target:       "administrasjon-kodeverk:Arbeidsforholdstype",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Arbeidsforholdstype) Relations() []runtime.Relation { return ArbeidsforholdstypeRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Arbeidsforholdstype", func() runtime.Resource { return &Arbeidsforholdstype{} })
}
