// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Fravarsgrunn

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fravarsgrunn is the FINT administrasjon-kodeverk type Fravarsgrunn.
//
// Grunn til fravær.
//
// # Eksempel
//
// - Arbeidsrelatert
// - Ikke arbeidsrelatert
// - Svangerskap
type Fravarsgrunn struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Fravarsgrunn) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fravarsgrunn) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FravarsgrunnIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FravarsgrunnIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fravarsgrunn) IDFieldNames() []string { return FravarsgrunnIDFieldNames }

// FravarsgrunnRelations is the runtime metadata for Fravarsgrunn's relations
// (own and inherited, flattened).
var FravarsgrunnRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Fravarsgrunn) Relations() []runtime.Relation { return FravarsgrunnRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Fravarsgrunn", func() runtime.Resource { return &Fravarsgrunn{} })
}
