// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Funksjon

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Funksjon is the FINT administrasjon-kodeverk type Funksjon.
//
// # Del av kontostrengen som beskriver hva som produseres
//
// # Beskrivelse
//
// Funksjon viser fylkeskommunens aktivitet og tjenesteproduksjon.
//
// Alternativ navn: `Tjeneste`
type Funksjon struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FunksjonLinks `json:"_links,omitempty"`
}

// FunksjonLinks is the typed _links envelope for Funksjon.
type FunksjonLinks struct {
	Overordnet  []runtime.Link `json:"overordnet,omitempty"`
	Underordnet []runtime.Link `json:"underordnet,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Funksjon.
func (l FunksjonLinks) ByName(name string) []runtime.Link {
	switch name {
	case "overordnet":
		return l.Overordnet
	case "underordnet":
		return l.Underordnet
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Funksjon) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Funksjon) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FunksjonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FunksjonIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Funksjon) IDFieldNames() []string { return FunksjonIDFieldNames }

// FunksjonRelations is the runtime metadata for Funksjon's relations
// (own and inherited, flattened).
var FunksjonRelations = []runtime.Relation{
	{
		Name:         "overordnet",
		Target:       "administrasjon-kodeverk:Funksjon",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "underordnet",
		},
	},
	{
		Name:         "underordnet",
		Target:       "administrasjon-kodeverk:Funksjon",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "overordnet",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Funksjon) Relations() []runtime.Relation { return FunksjonRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Funksjon", func() runtime.Resource { return &Funksjon{} })
}
