// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Kontodimensjon

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kontodimensjon is the FINT administrasjon-kodeverk type Kontodimensjon.
//
// Abstrakt fellesbegrep som beskriver dimensjon i kontoplan.
//
// # Beskrivelse
//
// Fellesbenevnelse for dimensjoner i en kontoplan.
type Kontodimensjon struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Kontodimensjon) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kontodimensjon) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KontodimensjonIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KontodimensjonIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kontodimensjon) IDFieldNames() []string { return KontodimensjonIDFieldNames }

// KontodimensjonRelations is the runtime metadata for Kontodimensjon's relations
// (own and inherited, flattened).
var KontodimensjonRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Kontodimensjon) Relations() []runtime.Relation { return KontodimensjonRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Kontodimensjon", func() runtime.Resource { return &Kontodimensjon{} })
}
