// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Kontrakt

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kontrakt is the FINT administrasjon-kodeverk type Kontrakt.
//
// Kontrakt transaksjonen er knyttet til.
type Kontrakt struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Kontrakt) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kontrakt) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KontraktIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KontraktIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kontrakt) IDFieldNames() []string { return KontraktIDFieldNames }

// KontraktRelations is the runtime metadata for Kontrakt's relations
// (own and inherited, flattened).
var KontraktRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Kontrakt) Relations() []runtime.Relation { return KontraktRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Kontrakt", func() runtime.Resource { return &Kontrakt{} })
}
