// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Objekt

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Objekt is the FINT administrasjon-kodeverk type Objekt.
//
// Et bygg, en vei eller en bestemt mottaker av en tjeneste eller et tilskudd m.m.
type Objekt struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Objekt) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Objekt) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ObjektIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ObjektIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Objekt) IDFieldNames() []string { return ObjektIDFieldNames }

// ObjektRelations is the runtime metadata for Objekt's relations
// (own and inherited, flattened).
var ObjektRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Objekt) Relations() []runtime.Relation { return ObjektRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Objekt", func() runtime.Resource { return &Objekt{} })
}
