// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Organisasjonstype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Organisasjonstype is the FINT administrasjon-kodeverk type Organisasjonstype.
//
// Typen til et organisasjonselement.
//
// # Eksempler
//
// - Virksomhet
// - Klinikk
// - Seksjon
// - Avdeling
// - Team
// - Divisjon
// - Stab
// - Skolegruppe
type Organisasjonstype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Organisasjonstype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Organisasjonstype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// OrganisasjonstypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var OrganisasjonstypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Organisasjonstype) IDFieldNames() []string { return OrganisasjonstypeIDFieldNames }

// OrganisasjonstypeRelations is the runtime metadata for Organisasjonstype's relations
// (own and inherited, flattened).
var OrganisasjonstypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Organisasjonstype) Relations() []runtime.Relation { return OrganisasjonstypeRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Organisasjonstype", func() runtime.Resource { return &Organisasjonstype{} })
}
