// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Personalressurskategori

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Personalressurskategori is the FINT administrasjon-kodeverk type Personalressurskategori.
//
// # Ansattform til et arbeidsforhold
//
// # Beskrivelse
//
// Alternativ navn:
// * Ansatt (er ikke datatype, men kodeverk)
// * Ansattkategori
// * Ansattformer"
//
// # Eksempel
//
// ## Eksempel fra Visma HR - Kategori:
//
// Kode | Beskrivelse
// ---|---
// F | Fast
// M | Midlertidig
// O | Oppdragstaker
// P | Politiker
// S | Sluttet
//
// ## Eksempel fra Agresso - Ressurstype:
//
// Kode  |	Beskrivelse
// ---|---
// 1 |	Ansatt - kommunal
// 10 |	Lærling/Ung arb.taker
// 2 |	Ansatt - undervisning
// 3 |	Honorar/godtgjørelse
// 4 |	Sluttet
// 5 |	Nyansatt
// 6 |	Ikke ansatt - kun bruker
// 7 |	Politikere
// 8| 	Selvstendig næringsdrivende
type Personalressurskategori struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Personalressurskategori) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Personalressurskategori) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PersonalressurskategoriIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersonalressurskategoriIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Personalressurskategori) IDFieldNames() []string { return PersonalressurskategoriIDFieldNames }

// PersonalressurskategoriRelations is the runtime metadata for Personalressurskategori's relations
// (own and inherited, flattened).
var PersonalressurskategoriRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Personalressurskategori) Relations() []runtime.Relation {
	return PersonalressurskategoriRelations
}

func init() {
	runtime.Register("administrasjon-kodeverk:Personalressurskategori", func() runtime.Resource { return &Personalressurskategori{} })
}
