// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kodeverk:Ramme

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Ramme is the FINT administrasjon-kodeverk type Ramme.
//
// Ramme er en del av kontostrengen og viser hvilken budsjettramme som skal bære kostnadene.
type Ramme struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Ramme) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Ramme) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// RammeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var RammeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Ramme) IDFieldNames() []string { return RammeIDFieldNames }

// RammeRelations is the runtime metadata for Ramme's relations
// (own and inherited, flattened).
var RammeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Ramme) Relations() []runtime.Relation { return RammeRelations }

func init() {
	runtime.Register("administrasjon-kodeverk:Ramme", func() runtime.Resource { return &Ramme{} })
}
