// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-utdanningsprogram:Arstrinn

package utdanningsprogram

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Arstrinn is the FINT utdanning-utdanningsprogram type Arstrinn.
//
// Hvert år i grunnopplæringen (grunnskole og videregående skole) kalles et årstrinn.
//
// # Eksempler
//
// * Vg1
// * Vg2
// * Vg3
// * Vg4
//
// # Synonym
//
// * Nivå (Rogaland)
// * Klassetrinn
// * Trinn
//
// # Referanser
//
// * http://grepwiki.udir.no/index.php?title=Årstrinn
// * http://psi.udir.no/ontologi/kl06/aarstrinn
type Arstrinn struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ArstrinnLinks `json:"_links,omitempty"`
}

// ArstrinnLinks is the typed _links envelope for Arstrinn.
type ArstrinnLinks struct {
	Grepreferanse []runtime.Link `json:"grepreferanse,omitempty"`
	Klasse        []runtime.Link `json:"klasse,omitempty"`
	Programomrade []runtime.Link `json:"programomrade,omitempty"`
	Vigoreferanse []runtime.Link `json:"vigoreferanse,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Arstrinn.
func (l ArstrinnLinks) ByName(name string) []runtime.Link {
	switch name {
	case "grepreferanse":
		return l.Grepreferanse
	case "klasse":
		return l.Klasse
	case "programomrade":
		return l.Programomrade
	case "vigoreferanse":
		return l.Vigoreferanse
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Arstrinn) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Arstrinn) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ArstrinnIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ArstrinnIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Arstrinn) IDFieldNames() []string { return ArstrinnIDFieldNames }

// ArstrinnRelations is the runtime metadata for Arstrinn's relations
// (own and inherited, flattened).
var ArstrinnRelations = []runtime.Relation{
	{
		Name:         "grepreferanse",
		Target:       "utdanning-kodeverk:Grepreferanse",
		Multiplicity: "0..1",
	},
	{
		Name:         "klasse",
		Target:       "utdanning-elev:Klasse",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "trinn",
		},
	},
	{
		Name:         "programomrade",
		Target:       "utdanning-utdanningsprogram:Programomrade",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "trinn",
		},
	},
	{
		Name:         "vigoreferanse",
		Target:       "utdanning-kodeverk:Vigoreferanse",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Arstrinn) Relations() []runtime.Relation { return ArstrinnRelations }

func init() {
	runtime.Register("utdanning-utdanningsprogram:Arstrinn", func() runtime.Resource { return &Arstrinn{} })
}
