// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-utdanningsprogram:Programomrade

package utdanningsprogram

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Programomrade is the FINT utdanning-utdanningsprogram type Programomrade.
//
// Programområde er et kurs i den videregående skolen. Et programområde strekker seg vanligvis over ett eller flere år og er gjerne en spesialisert retning eller område for fordypning innen utdanningsprogrammet.
//
// # Beskrivelse
//
// Innenfor utdanningsprogrammet studiespesialisering, er eksempler på programområder realfag, språk, samfunnsfag og økonomi og formgivingsfag.
//
// Innenfor utdanningsprogrammet naturbruk, finnes det for eksempel i andre klasse (Vg2) programområdene akvakultur, anleggsgartner og driftsoperatør idrettsanlegg, fiske og fangst, heste- og hovslagerfag, landbruk og gartneri, reindrift og skogbruk.
//
// Programområdekoder som slutter på  `----` angir at det er standardversjon av programområdet, og ikke en fylkeskommunal variant.
//
// # Eksempler
//
// * Anleggsmaskinførerf,PB
// * Asfaltfaget,PB
// * Banemontørfaget,PB
// * Betongfaget,PB
// * Bioenergi (D)
// * Byggdrifterfaget,PB
// * FDV-utdanning, 1 år (D)
// * Feierfaget,PB
// * Matrosfaget,PB
// * Modellbyggerfaget,PB
// * Motormannfaget,PB
// * Motormekanikerfaget,PB
// * Motorsykkelfaget,PB
//
// # Referanser
//
// * UDir Registreringshåndbok: [regbok.udir.no/35004/3344/35042-1014307.html](http://regbok.udir.no/35004/3344/35042-1014307.html)
// * Wikipedia: https://no.wikipedia.org/wiki/Programområde
// * Grepwiki: http://grepwiki.udir.no/index.php?title=Programområde
type Programomrade struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ProgramomradeLinks `json:"_links,omitempty"`
}

// ProgramomradeLinks is the typed _links envelope for Programomrade.
type ProgramomradeLinks struct {
	Fag               []runtime.Link `json:"fag,omitempty"`
	Grepreferanse     []runtime.Link `json:"grepreferanse,omitempty"`
	Gruppemedlemskap  []runtime.Link `json:"gruppemedlemskap,omitempty"`
	Trinn             []runtime.Link `json:"trinn,omitempty"`
	Utdanningsprogram []runtime.Link `json:"utdanningsprogram,omitempty"`
	Vigoreferanse     []runtime.Link `json:"vigoreferanse,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Programomrade.
func (l ProgramomradeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fag":
		return l.Fag
	case "grepreferanse":
		return l.Grepreferanse
	case "gruppemedlemskap":
		return l.Gruppemedlemskap
	case "trinn":
		return l.Trinn
	case "utdanningsprogram":
		return l.Utdanningsprogram
	case "vigoreferanse":
		return l.Vigoreferanse
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Programomrade) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Programomrade) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ProgramomradeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ProgramomradeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Programomrade) IDFieldNames() []string { return ProgramomradeIDFieldNames }

// ProgramomradeRelations is the runtime metadata for Programomrade's relations
// (own and inherited, flattened).
var ProgramomradeRelations = []runtime.Relation{
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "programomrade",
		},
	},
	{
		Name:         "grepreferanse",
		Target:       "utdanning-kodeverk:Grepreferanse",
		Multiplicity: "0..1",
	},
	{
		Name:         "gruppemedlemskap",
		Target:       "utdanning-utdanningsprogram:Programomrademedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "programomrade",
		},
	},
	{
		Name:         "trinn",
		Target:       "utdanning-utdanningsprogram:Arstrinn",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "programomrade",
		},
	},
	{
		Name:         "utdanningsprogram",
		Target:       "utdanning-utdanningsprogram:Utdanningsprogram",
		Multiplicity: "1..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "programomrade",
		},
	},
	{
		Name:         "vigoreferanse",
		Target:       "utdanning-kodeverk:Vigoreferanse",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Programomrade) Relations() []runtime.Relation { return ProgramomradeRelations }

func init() {
	runtime.Register("utdanning-utdanningsprogram:Programomrade", func() runtime.Resource { return &Programomrade{} })
}
