// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-utdanningsprogram:Programomrademedlemskap

package utdanningsprogram

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Programomrademedlemskap is the FINT utdanning-utdanningsprogram type Programomrademedlemskap.
//
// Medlemskap i programområder.
//
// # Beskrivelse
//
// Gruppemedlemskap som knytter sammen elevforhold og programområder.
type Programomrademedlemskap struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links ProgramomrademedlemskapLinks `json:"_links,omitempty"`
}

// ProgramomrademedlemskapLinks is the typed _links envelope for Programomrademedlemskap.
type ProgramomrademedlemskapLinks struct {
	Elevforhold   []runtime.Link `json:"elevforhold,omitempty"`
	Programomrade []runtime.Link `json:"programomrade,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Programomrademedlemskap.
func (l ProgramomrademedlemskapLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elevforhold":
		return l.Elevforhold
	case "programomrade":
		return l.Programomrade
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Programomrademedlemskap) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Programomrademedlemskap) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// ProgramomrademedlemskapIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var ProgramomrademedlemskapIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Programomrademedlemskap) IDFieldNames() []string { return ProgramomrademedlemskapIDFieldNames }

// ProgramomrademedlemskapRelations is the runtime metadata for Programomrademedlemskap's relations
// (own and inherited, flattened).
var ProgramomrademedlemskapRelations = []runtime.Relation{
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "programomrademedlemskap",
		},
	},
	{
		Name:         "programomrade",
		Target:       "utdanning-utdanningsprogram:Programomrade",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "gruppemedlemskap",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Programomrademedlemskap) Relations() []runtime.Relation {
	return ProgramomrademedlemskapRelations
}

func init() {
	runtime.Register("utdanning-utdanningsprogram:Programomrademedlemskap", func() runtime.Resource { return &Programomrademedlemskap{} })
}
