// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-utdanningsprogram:Skole

package utdanningsprogram

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Skole is the FINT utdanning-utdanningsprogram type Skole.
//
// Organisasjonsenhet som gjennomfører utdanning.
//
// # Beskrivelse
//
// Typisk er dette en videregående skole, men det kan også være eksamenskontor eller andre skolerelevante enheter.
//
// Inneholder utdanningsspesifikk informasjon om en organisasjonsenhet.
//
// # Eksempel
//
// - Videregående skole
// - SMI-skole
// - Fagskole
// - IB-skole
// - Eksamenskontor
// - Opplæringskontor
// - Ressurssenter
// - Fengselsundervisning
type Skole struct {
	Domenenavn          *string                                      `json:"domenenavn,omitempty"`
	Forretningsadresse  *felleskompleksedatatyper.Adresse            `json:"forretningsadresse,omitempty"`
	JuridiskNavn        *string                                      `json:"juridiskNavn,omitempty"`
	Kontaktinformasjon  *felleskompleksedatatyper.Kontaktinformasjon `json:"kontaktinformasjon,omitempty"`
	Navn                string                                       `json:"navn"`
	Organisasjonsnavn   *string                                      `json:"organisasjonsnavn,omitempty"`
	Organisasjonsnummer *felleskompleksedatatyper.Identifikator      `json:"organisasjonsnummer,omitempty"`
	Postadresse         *felleskompleksedatatyper.Adresse            `json:"postadresse,omitempty"`
	Skolenummer         felleskompleksedatatyper.Identifikator       `json:"skolenummer"`
	SystemID            felleskompleksedatatyper.Identifikator       `json:"systemId"`

	Links SkoleLinks `json:"_links,omitempty"`
}

// SkoleLinks is the typed _links envelope for Skole.
type SkoleLinks struct {
	Eksamensgruppe       []runtime.Link `json:"eksamensgruppe,omitempty"`
	Elevforhold          []runtime.Link `json:"elevforhold,omitempty"`
	Fag                  []runtime.Link `json:"fag,omitempty"`
	Faggruppe            []runtime.Link `json:"faggruppe,omitempty"`
	Klasse               []runtime.Link `json:"klasse,omitempty"`
	Kontaktlarergruppe   []runtime.Link `json:"kontaktlarergruppe,omitempty"`
	Organisasjon         []runtime.Link `json:"organisasjon,omitempty"`
	SkoleeierType        []runtime.Link `json:"skoleeierType,omitempty"`
	Skoleressurs         []runtime.Link `json:"skoleressurs,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
	Undervisningsgruppe  []runtime.Link `json:"undervisningsgruppe,omitempty"`
	Utdanningsprogram    []runtime.Link `json:"utdanningsprogram,omitempty"`
	Vigoreferanse        []runtime.Link `json:"vigoreferanse,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Skole.
func (l SkoleLinks) ByName(name string) []runtime.Link {
	switch name {
	case "eksamensgruppe":
		return l.Eksamensgruppe
	case "elevforhold":
		return l.Elevforhold
	case "fag":
		return l.Fag
	case "faggruppe":
		return l.Faggruppe
	case "klasse":
		return l.Klasse
	case "kontaktlarergruppe":
		return l.Kontaktlarergruppe
	case "organisasjon":
		return l.Organisasjon
	case "skoleeierType":
		return l.SkoleeierType
	case "skoleressurs":
		return l.Skoleressurs
	case "undervisningsforhold":
		return l.Undervisningsforhold
	case "undervisningsgruppe":
		return l.Undervisningsgruppe
	case "utdanningsprogram":
		return l.Utdanningsprogram
	case "vigoreferanse":
		return l.Vigoreferanse
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Skole) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Skole) ForEachID(fn func(name, value string) bool) {
	if r.Organisasjonsnummer != nil && !fn("organisasjonsnummer", r.Organisasjonsnummer.Identifikatorverdi) {
		return
	}
	if !fn("skolenummer", r.Skolenummer.Identifikatorverdi) {
		return
	}
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SkoleIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SkoleIDFieldNames = []string{
	"organisasjonsnummer",
	"skolenummer",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Skole) IDFieldNames() []string { return SkoleIDFieldNames }

// SkoleRelations is the runtime metadata for Skole's relations
// (own and inherited, flattened).
var SkoleRelations = []runtime.Relation{
	{
		Name:         "eksamensgruppe",
		Target:       "utdanning-vurdering:Eksamensgruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "elevforhold",
		Target:       "utdanning-elev:Elevforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "fag",
		Target:       "utdanning-timeplan:Fag",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "faggruppe",
		Target:       "utdanning-timeplan:Faggruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "klasse",
		Target:       "utdanning-elev:Klasse",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "kontaktlarergruppe",
		Target:       "utdanning-elev:Kontaktlarergruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "organisasjon",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "skole",
		},
	},
	{
		Name:         "skoleeierType",
		Target:       "utdanning-kodeverk:Skoleeiertype",
		Multiplicity: "0..1",
	},
	{
		Name:         "skoleressurs",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "undervisningsgruppe",
		Target:       "utdanning-timeplan:Undervisningsgruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "utdanningsprogram",
		Target:       "utdanning-utdanningsprogram:Utdanningsprogram",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skole",
		},
	},
	{
		Name:         "vigoreferanse",
		Target:       "utdanning-kodeverk:Vigoreferanse",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Skole) Relations() []runtime.Relation { return SkoleRelations }

func init() {
	runtime.Register("utdanning-utdanningsprogram:Skole", func() runtime.Resource { return &Skole{} })
}
