// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-tilgang:Rettighet

package tilgang

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Rettighet is the FINT ressurs-tilgang type Rettighet.
//
// Navngir en rettighet. Hva rettigheten gir tilgang til er systemspesifikt.
type Rettighet struct {
	Beskrivelse       string                                 `json:"beskrivelse"`
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links RettighetLinks `json:"_links,omitempty"`
}

// RettighetLinks is the typed _links envelope for Rettighet.
type RettighetLinks struct {
	Identitet []runtime.Link `json:"identitet,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Rettighet.
func (l RettighetLinks) ByName(name string) []runtime.Link {
	switch name {
	case "identitet":
		return l.Identitet
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Rettighet) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Rettighet) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// RettighetIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var RettighetIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Rettighet) IDFieldNames() []string { return RettighetIDFieldNames }

// RettighetRelations is the runtime metadata for Rettighet's relations
// (own and inherited, flattened).
var RettighetRelations = []runtime.Relation{
	{
		Name:         "identitet",
		Target:       "ressurs-tilgang:Identitet",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "rettighet",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Rettighet) Relations() []runtime.Relation { return RettighetRelations }

func init() {
	runtime.Register("ressurs-tilgang:Rettighet", func() runtime.Resource { return &Rettighet{} })
}
