global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'link-walker-reader'
    metrics_path: '/link-walker/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          app: 'link-walker-reader'
