// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Avbruddsarsak

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Avbruddsarsak is the FINT utdanning-kodeverk type Avbruddsarsak.
//
// Årsaken til at eleven avbryter utdanningsprogrammet (Vg1)/programområdet (Vg2/Vg3) ) i løpet av skoleåret  eller lærlingen/lærekandidaten hever lærekontrakten/opplæringskontrakten.
//
// # Referanse
//
// Registreringshåndbok: https://regbok.udir.no/35004/3344/35042-1014313.html
type Avbruddsarsak struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Avbruddsarsak) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Avbruddsarsak) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// AvbruddsarsakIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AvbruddsarsakIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Avbruddsarsak) IDFieldNames() []string { return AvbruddsarsakIDFieldNames }

// AvbruddsarsakRelations is the runtime metadata for Avbruddsarsak's relations
// (own and inherited, flattened).
var AvbruddsarsakRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Avbruddsarsak) Relations() []runtime.Relation { return AvbruddsarsakRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Avbruddsarsak", func() runtime.Resource { return &Avbruddsarsak{} })
}
