// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Betalingsstatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Betalingsstatus is the FINT utdanning-kodeverk type Betalingsstatus.
//
// Statuser for betaling av eksamen for privatister.
type Betalingsstatus struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Betalingsstatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Betalingsstatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// BetalingsstatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BetalingsstatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Betalingsstatus) IDFieldNames() []string { return BetalingsstatusIDFieldNames }

// BetalingsstatusRelations is the runtime metadata for Betalingsstatus's relations
// (own and inherited, flattened).
var BetalingsstatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Betalingsstatus) Relations() []runtime.Relation { return BetalingsstatusRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Betalingsstatus", func() runtime.Resource { return &Betalingsstatus{} })
}
