// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Bevistype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Bevistype is the FINT utdanning-kodeverk type Bevistype.
//
// Viser hvilken bevistype eleven har fått på opplæringen.
//
// * KB - Kompetansebevis
// * VM - Vitnemål
//
// # Referanse
// [UDIR - Registreringshåndbok - B22](https://regbok.udir.no/oversikt)
type Bevistype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Bevistype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Bevistype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// BevistypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BevistypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Bevistype) IDFieldNames() []string { return BevistypeIDFieldNames }

// BevistypeRelations is the runtime metadata for Bevistype's relations
// (own and inherited, flattened).
var BevistypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Bevistype) Relations() []runtime.Relation { return BevistypeRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Bevistype", func() runtime.Resource { return &Bevistype{} })
}
