// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Brevtype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Brevtype is the FINT utdanning-kodeverk type Brevtype.
//
// Beskriver hvilken prøve lærlingen/lærekandidaten går opp til.
// * F - Fagbrev
// * S - Svennebrev
// * K - Kompetansebevis
// * B - Praksisbrev
//
// # Referanse
// [UDIR - Registreringshåndbok - C22](https://regbok.udir.no/oversikt)
type Brevtype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Brevtype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Brevtype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// BrevtypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BrevtypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Brevtype) IDFieldNames() []string { return BrevtypeIDFieldNames }

// BrevtypeRelations is the runtime metadata for Brevtype's relations
// (own and inherited, flattened).
var BrevtypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Brevtype) Relations() []runtime.Relation { return BrevtypeRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Brevtype", func() runtime.Resource { return &Brevtype{} })
}
