// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Eksamensform

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Eksamensform is the FINT utdanning-kodeverk type Eksamensform.
//
// Eksamensordningens form.
//
// # Eksempler:
// * Muntlig
// * Skriftlig
// * Praktisk
//
// # Referanser
//
// * https://www.vigo.no/vigokv/ekstype.action
type Eksamensform struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Eksamensform) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Eksamensform) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// EksamensformIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var EksamensformIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Eksamensform) IDFieldNames() []string { return EksamensformIDFieldNames }

// EksamensformRelations is the runtime metadata for Eksamensform's relations
// (own and inherited, flattened).
var EksamensformRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Eksamensform) Relations() []runtime.Relation { return EksamensformRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Eksamensform", func() runtime.Resource { return &Eksamensform{} })
}
