// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Fagmerknad

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fagmerknad is the FINT utdanning-kodeverk type Fagmerknad.
//
// # Merknader til vitnemål og kompetansebevis
//
// # Beskrivelse
//
// # En fagmerknad er en merknad som har en eller flere av disse funksjonene
//
// - gir opplysninger om faget som ikke går fram av karakterer eller eksamensform
// - utdyper opplysninger om karakterer og/eller eksamensform
// - henviser til vedlegg som gir slike opplysninger
//
// # Referanser
//
// [Merknader til vitnemål og kompetansebevis](https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/3-merknader-til-vitnemal-og-kompetansebevis/)
type Fagmerknad struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Fagmerknad) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fagmerknad) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FagmerknadIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FagmerknadIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fagmerknad) IDFieldNames() []string { return FagmerknadIDFieldNames }

// FagmerknadRelations is the runtime metadata for Fagmerknad's relations
// (own and inherited, flattened).
var FagmerknadRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Fagmerknad) Relations() []runtime.Relation { return FagmerknadRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Fagmerknad", func() runtime.Resource { return &Fagmerknad{} })
}
