// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Fagstatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fagstatus is the FINT utdanning-kodeverk type Fagstatus.
//
// Elevens, privatistens eller kandidatens (voksne) status på et gitt fag.
//
// # Beskrivelse
//
// Fagstatus er en kode for undervisningen og/eller grunnlaget for karakteren. Den gir informasjon om hvordan det enkelte faget er gjennomført eller evt. ikke gjennomført.
//
// # Eksempler
//
// * E - Elev
// * F - Fritatt
//
// # Referanse
//
// [Registreringshåndbok]( https://regbok.udir.no/felt/?Id=1014315)
type Fagstatus struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Fagstatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fagstatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FagstatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FagstatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fagstatus) IDFieldNames() []string { return FagstatusIDFieldNames }

// FagstatusRelations is the runtime metadata for Fagstatus's relations
// (own and inherited, flattened).
var FagstatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Fagstatus) Relations() []runtime.Relation { return FagstatusRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Fagstatus", func() runtime.Resource { return &Fagstatus{} })
}
