// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Fullfortkode

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fullfortkode is the FINT utdanning-kodeverk type Fullfortkode.
//
// Gir status på hvordan eleven har gjennomført et programområde ved (det normale) skoleårs slutt.
//
// # Referanse
// [UDIR - Registreringshåndbok - B21](https://regbok.udir.no/oversikt)
type Fullfortkode struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Fullfortkode) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fullfortkode) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FullfortkodeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FullfortkodeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fullfortkode) IDFieldNames() []string { return FullfortkodeIDFieldNames }

// FullfortkodeRelations is the runtime metadata for Fullfortkode's relations
// (own and inherited, flattened).
var FullfortkodeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Fullfortkode) Relations() []runtime.Relation { return FullfortkodeRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Fullfortkode", func() runtime.Resource { return &Fullfortkode{} })
}
