// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Karakterskala

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Karakterskala is the FINT utdanning-kodeverk type Karakterskala.
//
// Gruppering av karakterer etter skala (bokstav, orden osv).
//
// # Eksempler
//
// * Bokstav – bokstavkarakterer
// * Tall – tallkarakterer
// * Binær – Bestått/Ikke-bestått
// * Prosent – prosentpoeng.
type Karakterskala struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links KarakterskalaLinks `json:"_links,omitempty"`
}

// KarakterskalaLinks is the typed _links envelope for Karakterskala.
type KarakterskalaLinks struct {
	Verdi         []runtime.Link `json:"verdi,omitempty"`
	Vigoreferanse []runtime.Link `json:"vigoreferanse,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Karakterskala.
func (l KarakterskalaLinks) ByName(name string) []runtime.Link {
	switch name {
	case "verdi":
		return l.Verdi
	case "vigoreferanse":
		return l.Vigoreferanse
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Karakterskala) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Karakterskala) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KarakterskalaIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KarakterskalaIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Karakterskala) IDFieldNames() []string { return KarakterskalaIDFieldNames }

// KarakterskalaRelations is the runtime metadata for Karakterskala's relations
// (own and inherited, flattened).
var KarakterskalaRelations = []runtime.Relation{
	{
		Name:         "verdi",
		Target:       "utdanning-vurdering:Karakterverdi",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skala",
		},
	},
	{
		Name:         "vigoreferanse",
		Target:       "utdanning-kodeverk:Vigoreferanse",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Karakterskala) Relations() []runtime.Relation { return KarakterskalaRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Karakterskala", func() runtime.Resource { return &Karakterskala{} })
}
