// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Karakterstatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Karakterstatus is the FINT utdanning-kodeverk type Karakterstatus.
//
// Kode for karakterer som blir endret.
//
// # Referanse
//
// https://regbok.udir.no/35004/3344/35042-1015043.html
type Karakterstatus struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Karakterstatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Karakterstatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KarakterstatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KarakterstatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Karakterstatus) IDFieldNames() []string { return KarakterstatusIDFieldNames }

// KarakterstatusRelations is the runtime metadata for Karakterstatus's relations
// (own and inherited, flattened).
var KarakterstatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Karakterstatus) Relations() []runtime.Relation { return KarakterstatusRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Karakterstatus", func() runtime.Resource { return &Karakterstatus{} })
}
