// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:OtEnhet

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// OtEnhet is the FINT utdanning-kodeverk type OtEnhet.
//
// Stedet hvor OT-ungdom er under oppfølging.
type OtEnhet struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links OtEnhetLinks `json:"_links,omitempty"`
}

// OtEnhetLinks is the typed _links envelope for OtEnhet.
type OtEnhetLinks struct {
	Kommune []runtime.Link `json:"kommune,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on OtEnhet.
func (l OtEnhetLinks) ByName(name string) []runtime.Link {
	switch name {
	case "kommune":
		return l.Kommune
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r OtEnhet) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r OtEnhet) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// OtEnhetIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var OtEnhetIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (OtEnhet) IDFieldNames() []string { return OtEnhetIDFieldNames }

// OtEnhetRelations is the runtime metadata for OtEnhet's relations
// (own and inherited, flattened).
var OtEnhetRelations = []runtime.Relation{
	{
		Name:         "kommune",
		Target:       "felles-kodeverk:Kommune",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (OtEnhet) Relations() []runtime.Relation { return OtEnhetRelations }

func init() {
	runtime.Register("utdanning-kodeverk:OtEnhet", func() runtime.Resource { return &OtEnhet{} })
}
