// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:OtStatus

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// OtStatus is the FINT utdanning-kodeverk type OtStatus.
//
// # Statuskoder angir hva som er ungdommens hovedaktivitet
//
// # Eksempel
//
// * OTAR – I arbeid
// * OTMI – Er i militæret
// * OTAP – Arbeidspraksis eller annet tiltak i regi av NAV
// * OTUK – Ukjent aktivitet
type OtStatus struct {
	Beskrivelse       *string                                `json:"beskrivelse,omitempty"`
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
	Type              string                                 `json:"type"`
}

// LinksByName satisfies runtime.Resource.
func (r OtStatus) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r OtStatus) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// OtStatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var OtStatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (OtStatus) IDFieldNames() []string { return OtStatusIDFieldNames }

// OtStatusRelations is the runtime metadata for OtStatus's relations
// (own and inherited, flattened).
var OtStatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (OtStatus) Relations() []runtime.Relation { return OtStatusRelations }

func init() {
	runtime.Register("utdanning-kodeverk:OtStatus", func() runtime.Resource { return &OtStatus{} })
}
