// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Skolear

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Skolear is the FINT utdanning-kodeverk type Skolear.
//
// Del av året da skoler har undervisning (og ikke ferie).
//
// # Beskrivelse
//
// Et skoleår varer som hovedregel fra august til juni.
type Skolear struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Skolear) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Skolear) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SkolearIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SkolearIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Skolear) IDFieldNames() []string { return SkolearIDFieldNames }

// SkolearRelations is the runtime metadata for Skolear's relations
// (own and inherited, flattened).
var SkolearRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Skolear) Relations() []runtime.Relation { return SkolearRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Skolear", func() runtime.Resource { return &Skolear{} })
}
