// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-kodeverk:Vigoreferanse

package kodeverk

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Vigoreferanse is the FINT utdanning-kodeverk type Vigoreferanse.
//
// Ekstern referanse til VIGO Kodeverksbase.
//
// # Beskrivelse
//
// Kodeverket kommer fra Grep (Utdanningsdirektoratet sin læreplandatabase), Nasjonalt skoleregister og VIGO.
//
// Referanser til VIGO Kodeverksbase skal referere til gyldige og unike koder i REST (JSON) API fra Vigo IKS/FINTLabs.
//
// https://api.felleskomponent.no/utdanning/vigo/kodeverk/swagger-ui.html#/
type Vigoreferanse struct {
}

// LinksByName satisfies runtime.Resource.
func (r Vigoreferanse) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Vigoreferanse) ForEachID(fn func(name, value string) bool) {
}

// VigoreferanseIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var VigoreferanseIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Vigoreferanse) IDFieldNames() []string { return VigoreferanseIDFieldNames }

// VigoreferanseRelations is the runtime metadata for Vigoreferanse's relations
// (own and inherited, flattened).
var VigoreferanseRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Vigoreferanse) Relations() []runtime.Relation { return VigoreferanseRelations }

func init() {
	runtime.Register("utdanning-kodeverk:Vigoreferanse", func() runtime.Resource { return &Vigoreferanse{} })
}
