// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-kodeverk:Brukertype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Brukertype is the FINT ressurs-kodeverk type Brukertype.
//
// De ulike brukertypene som kan benytte lisensen.
//
// Eksempler:
//
// * ELEV
// * ANSATTSKOLE
// * ANSATTADMINISTRASJON
// * EKSTERN
type Brukertype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Brukertype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Brukertype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// BrukertypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var BrukertypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Brukertype) IDFieldNames() []string { return BrukertypeIDFieldNames }

// BrukertypeRelations is the runtime metadata for Brukertype's relations
// (own and inherited, flattened).
var BrukertypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Brukertype) Relations() []runtime.Relation { return BrukertypeRelations }

func init() {
	runtime.Register("ressurs-kodeverk:Brukertype", func() runtime.Resource { return &Brukertype{} })
}
