// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-kodeverk:Handhevingstype

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Handhevingstype is the FINT ressurs-kodeverk type Handhevingstype.
//
// Hvordan ulike lisensmodeller kan håndheves av systemer for forvaltning av applikasjonen.
//
// Eksempel:
//
// * Hardstopp (ikke lov å tildele flere lisenser enn det kildesystemet angir)
// * Ubegrenset (ingen begrensing på antall lisenser som kan tildeles)
// * Overallokering tillatt (kan tildeles lisenser utover maks antall. Ikke nødvendigvis ubegrenset)
type Handhevingstype struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Handhevingstype) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Handhevingstype) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// HandhevingstypeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var HandhevingstypeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Handhevingstype) IDFieldNames() []string { return HandhevingstypeIDFieldNames }

// HandhevingstypeRelations is the runtime metadata for Handhevingstype's relations
// (own and inherited, flattened).
var HandhevingstypeRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Handhevingstype) Relations() []runtime.Relation { return HandhevingstypeRelations }

func init() {
	runtime.Register("ressurs-kodeverk:Handhevingstype", func() runtime.Resource { return &Handhevingstype{} })
}
