// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-kodeverk:Plattform

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Plattform is the FINT ressurs-kodeverk type Plattform.
//
// Plattformen tjenesten kan leveres på.
//
// Eksempel:
//
// * Windows
// * MAC OS
// * Linux
// * IOS
// * Android
type Plattform struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Plattform) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Plattform) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PlattformIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PlattformIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Plattform) IDFieldNames() []string { return PlattformIDFieldNames }

// PlattformRelations is the runtime metadata for Plattform's relations
// (own and inherited, flattened).
var PlattformRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Plattform) Relations() []runtime.Relation { return PlattformRelations }

func init() {
	runtime.Register("ressurs-kodeverk:Plattform", func() runtime.Resource { return &Plattform{} })
}
