// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   ressurs-kodeverk:Status

package kodeverk

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

type Status struct {
	Gyldighetsperiode *felleskompleksedatatyper.Periode      `json:"gyldighetsperiode,omitempty"`
	Kode              string                                 `json:"kode"`
	Navn              string                                 `json:"navn"`
	Passiv            *bool                                  `json:"passiv,omitempty"`
	SystemID          felleskompleksedatatyper.Identifikator `json:"systemId"`
}

// LinksByName satisfies runtime.Resource.
func (r Status) LinksByName(name string) []runtime.Link {
	return nil
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Status) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// StatusIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var StatusIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Status) IDFieldNames() []string { return StatusIDFieldNames }

// StatusRelations is the runtime metadata for Status's relations
// (own and inherited, flattened).
var StatusRelations = []runtime.Relation{}

// Relations satisfies runtime.Resource.
func (Status) Relations() []runtime.Relation { return StatusRelations }

func init() {
	runtime.Register("ressurs-kodeverk:Status", func() runtime.Resource { return &Status{} })
}
