// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-larling:AvlagtProve

package larling

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// AvlagtProve is the FINT utdanning-larling type AvlagtProve.
//
// Informasjon om en avlagt prøve for en person i et fag.
type AvlagtProve struct {
	Provedato *time.Time                             `json:"provedato,omitempty"`
	SystemID  felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links AvlagtProveLinks `json:"_links,omitempty"`
}

// AvlagtProveLinks is the typed _links envelope for AvlagtProve.
type AvlagtProveLinks struct {
	Bevistype    []runtime.Link `json:"bevistype,omitempty"`
	Brevtype     []runtime.Link `json:"brevtype,omitempty"`
	Fullfortkode []runtime.Link `json:"fullfortkode,omitempty"`
	Larling      []runtime.Link `json:"larling,omitempty"`
	Provestatus  []runtime.Link `json:"provestatus,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on AvlagtProve.
func (l AvlagtProveLinks) ByName(name string) []runtime.Link {
	switch name {
	case "bevistype":
		return l.Bevistype
	case "brevtype":
		return l.Brevtype
	case "fullfortkode":
		return l.Fullfortkode
	case "larling":
		return l.Larling
	case "provestatus":
		return l.Provestatus
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r AvlagtProve) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r AvlagtProve) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// AvlagtProveIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var AvlagtProveIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (AvlagtProve) IDFieldNames() []string { return AvlagtProveIDFieldNames }

// AvlagtProveRelations is the runtime metadata for AvlagtProve's relations
// (own and inherited, flattened).
var AvlagtProveRelations = []runtime.Relation{
	{
		Name:         "bevistype",
		Target:       "utdanning-kodeverk:Bevistype",
		Multiplicity: "0..1",
	},
	{
		Name:         "brevtype",
		Target:       "utdanning-kodeverk:Brevtype",
		Multiplicity: "0..1",
	},
	{
		Name:         "fullfortkode",
		Target:       "utdanning-kodeverk:Fullfortkode",
		Multiplicity: "0..1",
	},
	{
		Name:         "larling",
		Target:       "utdanning-larling:Larling",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "avlagtprove",
		},
	},
	{
		Name:         "provestatus",
		Target:       "utdanning-kodeverk:Provestatus",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (AvlagtProve) Relations() []runtime.Relation { return AvlagtProveRelations }

func init() {
	runtime.Register("utdanning-larling:AvlagtProve", func() runtime.Resource { return &AvlagtProve{} })
}
