// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-larling:Larling

package larling

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Larling is the FINT utdanning-larling type Larling.
//
// Å være lærling betyr at du utdanner deg til et yrke ved å jobbe i en bedrift.
type Larling struct {
	Kontraktstype *string                                `json:"kontraktstype,omitempty"`
	Laretid       *felleskompleksedatatyper.Periode      `json:"laretid,omitempty"`
	SystemID      felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links LarlingLinks `json:"_links,omitempty"`
}

// LarlingLinks is the typed _links envelope for Larling.
type LarlingLinks struct {
	Avlagtprove   []runtime.Link `json:"avlagtprove,omitempty"`
	Bedrift       []runtime.Link `json:"bedrift,omitempty"`
	Person        []runtime.Link `json:"person,omitempty"`
	Programomrade []runtime.Link `json:"programomrade,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Larling.
func (l LarlingLinks) ByName(name string) []runtime.Link {
	switch name {
	case "avlagtprove":
		return l.Avlagtprove
	case "bedrift":
		return l.Bedrift
	case "person":
		return l.Person
	case "programomrade":
		return l.Programomrade
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Larling) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Larling) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// LarlingIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var LarlingIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Larling) IDFieldNames() []string { return LarlingIDFieldNames }

// LarlingRelations is the runtime metadata for Larling's relations
// (own and inherited, flattened).
var LarlingRelations = []runtime.Relation{
	{
		Name:         "avlagtprove",
		Target:       "utdanning-larling:AvlagtProve",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "larling",
		},
	},
	{
		Name:         "bedrift",
		Target:       "felles:Virksomhet",
		Multiplicity: "0..1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "larling",
		},
	},
	{
		Name:         "person",
		Target:       "felles:Person",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "larling",
		},
	},
	{
		Name:         "programomrade",
		Target:       "utdanning-utdanningsprogram:Programomrade",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Larling) Relations() []runtime.Relation { return LarlingRelations }

func init() {
	runtime.Register("utdanning-larling:Larling", func() runtime.Resource { return &Larling{} })
}
