// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   administrasjon-kompleksedatatyper:Kontostreng

package kompleksedatatyper

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kontostreng is the FINT administrasjon-kompleksedatatyper type Kontostreng.
//
// # Sammensetning av kontodimensjoner for bokføring
//
// # Beskrivelse
//
// Henvisninger til koder i alle kontodimensjoner for kontering av en kostnad eller inntekt.
type Kontostreng struct {
	Links KontostrengLinks `json:"_links,omitempty"`
}

// KontostrengLinks is the typed _links envelope for Kontostreng.
type KontostrengLinks struct {
	Aktivitet   []runtime.Link `json:"aktivitet,omitempty"`
	Anlegg      []runtime.Link `json:"anlegg,omitempty"`
	Ansvar      []runtime.Link `json:"ansvar,omitempty"`
	Art         []runtime.Link `json:"art,omitempty"`
	Diverse     []runtime.Link `json:"diverse,omitempty"`
	Formal      []runtime.Link `json:"formal,omitempty"`
	Funksjon    []runtime.Link `json:"funksjon,omitempty"`
	Kontrakt    []runtime.Link `json:"kontrakt,omitempty"`
	Lopenummer  []runtime.Link `json:"lopenummer,omitempty"`
	Objekt      []runtime.Link `json:"objekt,omitempty"`
	Prosjekt    []runtime.Link `json:"prosjekt,omitempty"`
	Prosjektart []runtime.Link `json:"prosjektart,omitempty"`
	Ramme       []runtime.Link `json:"ramme,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Kontostreng.
func (l KontostrengLinks) ByName(name string) []runtime.Link {
	switch name {
	case "aktivitet":
		return l.Aktivitet
	case "anlegg":
		return l.Anlegg
	case "ansvar":
		return l.Ansvar
	case "art":
		return l.Art
	case "diverse":
		return l.Diverse
	case "formal":
		return l.Formal
	case "funksjon":
		return l.Funksjon
	case "kontrakt":
		return l.Kontrakt
	case "lopenummer":
		return l.Lopenummer
	case "objekt":
		return l.Objekt
	case "prosjekt":
		return l.Prosjekt
	case "prosjektart":
		return l.Prosjektart
	case "ramme":
		return l.Ramme
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Kontostreng) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kontostreng) ForEachID(fn func(name, value string) bool) {
}

// KontostrengIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KontostrengIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Kontostreng) IDFieldNames() []string { return KontostrengIDFieldNames }

// KontostrengRelations is the runtime metadata for Kontostreng's relations
// (own and inherited, flattened).
var KontostrengRelations = []runtime.Relation{
	{
		Name:         "aktivitet",
		Target:       "administrasjon-kodeverk:Aktivitet",
		Multiplicity: "0..1",
	},
	{
		Name:         "anlegg",
		Target:       "administrasjon-kodeverk:Anlegg",
		Multiplicity: "0..1",
	},
	{
		Name:         "ansvar",
		Target:       "administrasjon-kodeverk:Ansvar",
		Multiplicity: "1",
	},
	{
		Name:         "art",
		Target:       "administrasjon-kodeverk:Art",
		Multiplicity: "1",
	},
	{
		Name:         "diverse",
		Target:       "administrasjon-kodeverk:Diverse",
		Multiplicity: "0..1",
	},
	{
		Name:         "formal",
		Target:       "administrasjon-kodeverk:Formal",
		Multiplicity: "0..1",
	},
	{
		Name:         "funksjon",
		Target:       "administrasjon-kodeverk:Funksjon",
		Multiplicity: "1",
	},
	{
		Name:         "kontrakt",
		Target:       "administrasjon-kodeverk:Kontrakt",
		Multiplicity: "0..1",
	},
	{
		Name:         "lopenummer",
		Target:       "administrasjon-kodeverk:Lopenummer",
		Multiplicity: "0..1",
	},
	{
		Name:         "objekt",
		Target:       "administrasjon-kodeverk:Objekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "prosjekt",
		Target:       "administrasjon-kodeverk:Prosjekt",
		Multiplicity: "0..1",
	},
	{
		Name:         "prosjektart",
		Target:       "administrasjon-kodeverk:Prosjektart",
		Multiplicity: "0..1",
	},
	{
		Name:         "ramme",
		Target:       "administrasjon-kodeverk:Ramme",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Kontostreng) Relations() []runtime.Relation { return KontostrengRelations }

func init() {
	runtime.Register("administrasjon-kompleksedatatyper:Kontostreng", func() runtime.Resource { return &Kontostreng{} })
}
