// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-faktura:Fakturagrunnlag

package faktura

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Fakturagrunnlag is the FINT okonomi-faktura type Fakturagrunnlag.
//
// Grunnlag for fakturering.
//
// # Beskrivelse
//
// Dokumentasjon som danner grunnlag for å fakturere en kunde.
//
// Beskriver hvem som skal utstede faktura og dermed motta betaling, hvem som skal faktureres, og hvilke varer det skal faktureres for.
type Fakturagrunnlag struct {
	Avgiftsbelop  *int64                                 `json:"avgiftsbelop,omitempty"`
	Fakturalinjer []Fakturalinje                         `json:"fakturalinjer,omitempty"`
	Leveringsdato *time.Time                             `json:"leveringsdato,omitempty"`
	Mottaker      Fakturamottaker                        `json:"mottaker"`
	Nettobelop    *int64                                 `json:"nettobelop,omitempty"`
	Ordrenummer   felleskompleksedatatyper.Identifikator `json:"ordrenummer"`
	Totalbelop    *int64                                 `json:"totalbelop,omitempty"`

	Links FakturagrunnlagLinks `json:"_links,omitempty"`
}

// FakturagrunnlagLinks is the typed _links envelope for Fakturagrunnlag.
type FakturagrunnlagLinks struct {
	Faktura         []runtime.Link `json:"faktura,omitempty"`
	Fakturautsteder []runtime.Link `json:"fakturautsteder,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fakturagrunnlag.
func (l FakturagrunnlagLinks) ByName(name string) []runtime.Link {
	switch name {
	case "faktura":
		return l.Faktura
	case "fakturautsteder":
		return l.Fakturautsteder
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fakturagrunnlag) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fakturagrunnlag) ForEachID(fn func(name, value string) bool) {
	if !fn("ordrenummer", r.Ordrenummer.Identifikatorverdi) {
		return
	}
}

// FakturagrunnlagIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FakturagrunnlagIDFieldNames = []string{
	"ordrenummer",
}

// IDFieldNames satisfies runtime.Resource.
func (Fakturagrunnlag) IDFieldNames() []string { return FakturagrunnlagIDFieldNames }

// FakturagrunnlagRelations is the runtime metadata for Fakturagrunnlag's relations
// (own and inherited, flattened).
var FakturagrunnlagRelations = []runtime.Relation{
	{
		Name:         "faktura",
		Target:       "okonomi-faktura:Faktura",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fakturagrunnlag",
		},
	},
	{
		Name:         "fakturautsteder",
		Target:       "okonomi-faktura:Fakturautsteder",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "fakturagrunnlag",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Fakturagrunnlag) Relations() []runtime.Relation { return FakturagrunnlagRelations }

func init() {
	runtime.Register("okonomi-faktura:Fakturagrunnlag", func() runtime.Resource { return &Fakturagrunnlag{} })
}
