// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-faktura:Fakturalinje

package faktura

import (
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fakturalinje is the FINT okonomi-faktura type Fakturalinje.
//
// Del av Fakturagrunnlag som beskriver en enkelt vare.
//
// # Beskrivelse
//
// Inneholder referanse til vare i et vareregister.
type Fakturalinje struct {
	Antall   float32  `json:"antall"`
	Fritekst []string `json:"fritekst,omitempty"`
	Pris     int64    `json:"pris"`

	Links FakturalinjeLinks `json:"_links,omitempty"`
}

// FakturalinjeLinks is the typed _links envelope for Fakturalinje.
type FakturalinjeLinks struct {
	Vare []runtime.Link `json:"vare,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fakturalinje.
func (l FakturalinjeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "vare":
		return l.Vare
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fakturalinje) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fakturalinje) ForEachID(fn func(name, value string) bool) {
}

// FakturalinjeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FakturalinjeIDFieldNames = []string{}

// IDFieldNames satisfies runtime.Resource.
func (Fakturalinje) IDFieldNames() []string { return FakturalinjeIDFieldNames }

// FakturalinjeRelations is the runtime metadata for Fakturalinje's relations
// (own and inherited, flattened).
var FakturalinjeRelations = []runtime.Relation{
	{
		Name:         "vare",
		Target:       "okonomi-kodeverk:Vare",
		Multiplicity: "1",
	},
}

// Relations satisfies runtime.Resource.
func (Fakturalinje) Relations() []runtime.Relation { return FakturalinjeRelations }

func init() {
	runtime.Register("okonomi-faktura:Fakturalinje", func() runtime.Resource { return &Fakturalinje{} })
}
