// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   okonomi-faktura:Fakturautsteder

package faktura

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Fakturautsteder is the FINT okonomi-faktura type Fakturautsteder.
//
// Enhet som utformer og oversender faktura og mottar betaling.
//
// # Beskrivelse
//
// Enhet som etter Regnskapsloven er pliktig å arkivere dokumentasjon for faktura.
type Fakturautsteder struct {
	Navn     string                                 `json:"navn"`
	SystemID felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links FakturautstederLinks `json:"_links,omitempty"`
}

// FakturautstederLinks is the typed _links envelope for Fakturautsteder.
type FakturautstederLinks struct {
	Fakturagrunnlag      []runtime.Link `json:"fakturagrunnlag,omitempty"`
	Organisasjonselement []runtime.Link `json:"organisasjonselement,omitempty"`
	Vare                 []runtime.Link `json:"vare,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Fakturautsteder.
func (l FakturautstederLinks) ByName(name string) []runtime.Link {
	switch name {
	case "fakturagrunnlag":
		return l.Fakturagrunnlag
	case "organisasjonselement":
		return l.Organisasjonselement
	case "vare":
		return l.Vare
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Fakturautsteder) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Fakturautsteder) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// FakturautstederIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var FakturautstederIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Fakturautsteder) IDFieldNames() []string { return FakturautstederIDFieldNames }

// FakturautstederRelations is the runtime metadata for Fakturautsteder's relations
// (own and inherited, flattened).
var FakturautstederRelations = []runtime.Relation{
	{
		Name:         "fakturagrunnlag",
		Target:       "okonomi-faktura:Fakturagrunnlag",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fakturautsteder",
		},
	},
	{
		Name:         "organisasjonselement",
		Target:       "administrasjon-organisasjon:Organisasjonselement",
		Multiplicity: "0..1",
	},
	{
		Name:         "vare",
		Target:       "okonomi-kodeverk:Vare",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "fakturautsteder",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Fakturautsteder) Relations() []runtime.Relation { return FakturautstederRelations }

func init() {
	runtime.Register("okonomi-faktura:Fakturautsteder", func() runtime.Resource { return &Fakturautsteder{} })
}
