// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-elev:Klasse

package elev

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Klasse is the FINT utdanning-elev type Klasse.
//
// Elevgruppe som definert i Opplæringslova &#167;8-2.
//
// # Beskrivelse
//
// I opplæringa skal elevane delast i klassar eller basisgrupper som skal vareta deira behov for sosialt tilhør. For delar av opplæringa kan elevane delast i andre grupper etter behov. Til vanleg skal organiseringa ikkje skje etter fagleg nivå, kjønn eller etnisk tilhør. Klassane, basisgruppene og gruppene må ikkje vere større enn det som er pedagogisk og tryggleiksmessig forsvarleg.
//
// Klassen eller basisgruppa skal ha ein eller fleire lærarar (kontaktlærarar) som har særleg ansvar for dei praktiske, administrative og sosialpedagogiske gjeremåla som gjeld klassen eller basisgruppa og dei elevane som er der, mellom anna kontakten med heimen.
//
// Begrepet som har tildligere vært kjent som "klasse".
//
// "Vanlig" gruppe i SATS (klassegruppe)
//
// Viser informasjon om:
// * År på VGS person går i
// * Programområdet
// * A, B eller C klasse
//
// Synonym:
// * Klasse
//
// Øvre grense er beskrevet i Opplæringslova &#167;8-3 eller i forskrift.
type Klasse struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links KlasseLinks `json:"_links,omitempty"`
}

// KlasseLinks is the typed _links envelope for Klasse.
type KlasseLinks struct {
	Klassemedlemskap     []runtime.Link `json:"klassemedlemskap,omitempty"`
	Kontaktlarergruppe   []runtime.Link `json:"kontaktlarergruppe,omitempty"`
	Skole                []runtime.Link `json:"skole,omitempty"`
	Skolear              []runtime.Link `json:"skolear,omitempty"`
	Termin               []runtime.Link `json:"termin,omitempty"`
	Trinn                []runtime.Link `json:"trinn,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Klasse.
func (l KlasseLinks) ByName(name string) []runtime.Link {
	switch name {
	case "klassemedlemskap":
		return l.Klassemedlemskap
	case "kontaktlarergruppe":
		return l.Kontaktlarergruppe
	case "skole":
		return l.Skole
	case "skolear":
		return l.Skolear
	case "termin":
		return l.Termin
	case "trinn":
		return l.Trinn
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Klasse) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Klasse) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KlasseIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KlasseIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Klasse) IDFieldNames() []string { return KlasseIDFieldNames }

// KlasseRelations is the runtime metadata for Klasse's relations
// (own and inherited, flattened).
var KlasseRelations = []runtime.Relation{
	{
		Name:         "klassemedlemskap",
		Target:       "utdanning-elev:Klassemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "klasse",
		},
	},
	{
		Name:         "kontaktlarergruppe",
		Target:       "utdanning-elev:Kontaktlarergruppe",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "klasse",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "klasse",
		},
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
	{
		Name:         "termin",
		Target:       "utdanning-kodeverk:Termin",
		Multiplicity: "0..*",
	},
	{
		Name:         "trinn",
		Target:       "utdanning-utdanningsprogram:Arstrinn",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "klasse",
		},
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "klasse",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Klasse) Relations() []runtime.Relation { return KlasseRelations }

func init() {
	runtime.Register("utdanning-elev:Klasse", func() runtime.Resource { return &Klasse{} })
}
