// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-elev:Kontaktlarergruppe

package elev

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Kontaktlarergruppe is the FINT utdanning-elev type Kontaktlarergruppe.
//
// Elevgruppe som ein kontaktlærer har særleg ansvar for.
//
// # Beskrivelse
//
// Kontaktlæreren har i denne gruppa særleg ansvar for dei praktiske, administrative og sosialpedagogiske gjeremåla som gjeld klassen eller basisgruppa og dei elevane som er der, mellom anna kontakten med heimen, jf Opplæringslova §8-2.
type Kontaktlarergruppe struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links KontaktlarergruppeLinks `json:"_links,omitempty"`
}

// KontaktlarergruppeLinks is the typed _links envelope for Kontaktlarergruppe.
type KontaktlarergruppeLinks struct {
	Gruppemedlemskap     []runtime.Link `json:"gruppemedlemskap,omitempty"`
	Klasse               []runtime.Link `json:"klasse,omitempty"`
	Skole                []runtime.Link `json:"skole,omitempty"`
	Skolear              []runtime.Link `json:"skolear,omitempty"`
	Termin               []runtime.Link `json:"termin,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Kontaktlarergruppe.
func (l KontaktlarergruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "gruppemedlemskap":
		return l.Gruppemedlemskap
	case "klasse":
		return l.Klasse
	case "skole":
		return l.Skole
	case "skolear":
		return l.Skolear
	case "termin":
		return l.Termin
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Kontaktlarergruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Kontaktlarergruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// KontaktlarergruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var KontaktlarergruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Kontaktlarergruppe) IDFieldNames() []string { return KontaktlarergruppeIDFieldNames }

// KontaktlarergruppeRelations is the runtime metadata for Kontaktlarergruppe's relations
// (own and inherited, flattened).
var KontaktlarergruppeRelations = []runtime.Relation{
	{
		Name:         "gruppemedlemskap",
		Target:       "utdanning-elev:Kontaktlarergruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "kontaktlarergruppe",
		},
	},
	{
		Name:         "klasse",
		Target:       "utdanning-elev:Klasse",
		Multiplicity: "1..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "kontaktlarergruppe",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "kontaktlarergruppe",
		},
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..1",
	},
	{
		Name:         "termin",
		Target:       "utdanning-kodeverk:Termin",
		Multiplicity: "0..*",
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "kontaktlarergruppe",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Kontaktlarergruppe) Relations() []runtime.Relation { return KontaktlarergruppeRelations }

func init() {
	runtime.Register("utdanning-elev:Kontaktlarergruppe", func() runtime.Resource { return &Kontaktlarergruppe{} })
}
