// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-elev:Persongruppe

package elev

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Persongruppe is the FINT utdanning-elev type Persongruppe.
//
// Gruppe av personer som ikke handler om undervisning. Dette kan f.eks. være grupper av elever som skal faktureres.
type Persongruppe struct {
	Beskrivelse string                                 `json:"beskrivelse"`
	Navn        string                                 `json:"navn"`
	SystemID    felleskompleksedatatyper.Identifikator `json:"systemId"`

	Links PersongruppeLinks `json:"_links,omitempty"`
}

// PersongruppeLinks is the typed _links envelope for Persongruppe.
type PersongruppeLinks struct {
	Elev                   []runtime.Link `json:"elev,omitempty"`
	Persongruppemedlemskap []runtime.Link `json:"persongruppemedlemskap,omitempty"`
	Skole                  []runtime.Link `json:"skole,omitempty"`
	Skolear                []runtime.Link `json:"skolear,omitempty"`
	Skoleressurs           []runtime.Link `json:"skoleressurs,omitempty"`
	Termin                 []runtime.Link `json:"termin,omitempty"`
	Undervisningsforhold   []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Persongruppe.
func (l PersongruppeLinks) ByName(name string) []runtime.Link {
	switch name {
	case "elev":
		return l.Elev
	case "persongruppemedlemskap":
		return l.Persongruppemedlemskap
	case "skole":
		return l.Skole
	case "skolear":
		return l.Skolear
	case "skoleressurs":
		return l.Skoleressurs
	case "termin":
		return l.Termin
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Persongruppe) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Persongruppe) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// PersongruppeIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var PersongruppeIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Persongruppe) IDFieldNames() []string { return PersongruppeIDFieldNames }

// PersongruppeRelations is the runtime metadata for Persongruppe's relations
// (own and inherited, flattened).
var PersongruppeRelations = []runtime.Relation{
	{
		Name:         "elev",
		Target:       "utdanning-elev:Elev",
		Multiplicity: "0..*",
	},
	{
		Name:         "persongruppemedlemskap",
		Target:       "utdanning-elev:Persongruppemedlemskap",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "persongruppe",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "0..*",
	},
	{
		Name:         "skolear",
		Target:       "utdanning-kodeverk:Skolear",
		Multiplicity: "0..*",
	},
	{
		Name:         "skoleressurs",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "0..*",
	},
	{
		Name:         "termin",
		Target:       "utdanning-kodeverk:Termin",
		Multiplicity: "0..*",
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
	},
}

// Relations satisfies runtime.Resource.
func (Persongruppe) Relations() []runtime.Relation { return PersongruppeRelations }

func init() {
	runtime.Register("utdanning-elev:Persongruppe", func() runtime.Resource { return &Persongruppe{} })
}
