// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-elev:Skoleressurs

package elev

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
)

// Skoleressurs is the FINT utdanning-elev type Skoleressurs.
//
// Ansatte på en skole.
//
// # Beskrivelse
//
// Kan være undervisningspersonell eller andre administrativt ansatte.
type Skoleressurs struct {
	Feidenavn *felleskompleksedatatyper.Identifikator `json:"feidenavn,omitempty"`
	SystemID  felleskompleksedatatyper.Identifikator  `json:"systemId"`

	Links SkoleressursLinks `json:"_links,omitempty"`
}

// SkoleressursLinks is the typed _links envelope for Skoleressurs.
type SkoleressursLinks struct {
	Person               []runtime.Link `json:"person,omitempty"`
	Personalressurs      []runtime.Link `json:"personalressurs,omitempty"`
	Sensor               []runtime.Link `json:"sensor,omitempty"`
	Skole                []runtime.Link `json:"skole,omitempty"`
	Undervisningsforhold []runtime.Link `json:"undervisningsforhold,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Skoleressurs.
func (l SkoleressursLinks) ByName(name string) []runtime.Link {
	switch name {
	case "person":
		return l.Person
	case "personalressurs":
		return l.Personalressurs
	case "sensor":
		return l.Sensor
	case "skole":
		return l.Skole
	case "undervisningsforhold":
		return l.Undervisningsforhold
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Skoleressurs) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Skoleressurs) ForEachID(fn func(name, value string) bool) {
	if r.Feidenavn != nil && !fn("feidenavn", r.Feidenavn.Identifikatorverdi) {
		return
	}
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// SkoleressursIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var SkoleressursIDFieldNames = []string{
	"feidenavn",
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Skoleressurs) IDFieldNames() []string { return SkoleressursIDFieldNames }

// SkoleressursRelations is the runtime metadata for Skoleressurs's relations
// (own and inherited, flattened).
var SkoleressursRelations = []runtime.Relation{
	{
		Name:         "person",
		Target:       "felles:Person",
		Multiplicity: "0..1",
	},
	{
		Name:         "personalressurs",
		Target:       "administrasjon-personal:Personalressurs",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "skoleressurs",
		},
	},
	{
		Name:         "sensor",
		Target:       "utdanning-vurdering:Sensor",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    false,
			InverseName: "skoleressurs",
		},
	},
	{
		Name:         "skole",
		Target:       "utdanning-utdanningsprogram:Skole",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "skoleressurs",
		},
	},
	{
		Name:         "undervisningsforhold",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..*",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "skoleressurs",
		},
	},
}

// Relations satisfies runtime.Resource.
func (Skoleressurs) Relations() []runtime.Relation { return SkoleressursRelations }

func init() {
	runtime.Register("utdanning-elev:Skoleressurs", func() runtime.Resource { return &Skoleressurs{} })
}
