// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
// Type:   utdanning-elev:Varsel

package elev

import (
	felleskompleksedatatyper "github.com/FINTLabs/fint-model-go/felles/kompleksedatatyper"
	"github.com/FINTLabs/fint-model-go/runtime"
	"time"
)

// Varsel is the FINT utdanning-elev type Varsel.
//
// Varsel sendt til en elev.
//
// # Referanse
//
// * [VIS - Opprette og sende varsel ](https://inschool.zendesk.com/hc/no/articles/360030859132-4b-21-Opprette-og-sende-varsel)
// * [Forskrift til opplæringslova - &#167; 3-8. Varsling](https://lovdata.no/dokument/SF/forskrift/2006-06-23-724/KAPITTEL_5-1#%C2%A73-8)
type Varsel struct {
	Fravarsprosent int64                                  `json:"fravarsprosent"`
	Sendt          time.Time                              `json:"sendt"`
	SystemID       felleskompleksedatatyper.Identifikator `json:"systemId"`
	Tekst          string                                 `json:"tekst"`

	Links VarselLinks `json:"_links,omitempty"`
}

// VarselLinks is the typed _links envelope for Varsel.
type VarselLinks struct {
	Faggruppemedlemskap []runtime.Link `json:"faggruppemedlemskap,omitempty"`
	Karakteransvarlig   []runtime.Link `json:"karakteransvarlig,omitempty"`
	Type                []runtime.Link `json:"type,omitempty"`
	Utsteder            []runtime.Link `json:"utsteder,omitempty"`
}

// ByName returns the link slice for the named relation, or nil if the
// name is not a relation on Varsel.
func (l VarselLinks) ByName(name string) []runtime.Link {
	switch name {
	case "faggruppemedlemskap":
		return l.Faggruppemedlemskap
	case "karakteransvarlig":
		return l.Karakteransvarlig
	case "type":
		return l.Type
	case "utsteder":
		return l.Utsteder
	}
	return nil
}

// LinksByName satisfies runtime.Resource.
func (r Varsel) LinksByName(name string) []runtime.Link {
	return r.Links.ByName(name)
}

// ForEachID invokes fn for each populated identifier field with its
// (jsonName, identifikatorverdi) pair. fn returns true to continue
// iteration, false to stop. Zero-allocation: nothing is captured or
// returned, the method body just calls fn directly.
func (r Varsel) ForEachID(fn func(name, value string) bool) {
	if !fn("systemId", r.SystemID.Identifikatorverdi) {
		return
	}
}

// VarselIDFieldNames lists every identifier field name on this
// type, in the same order IDFields yields them. Stable across
// regenerations — consumers can rely on the ordering.
var VarselIDFieldNames = []string{
	"systemId",
}

// IDFieldNames satisfies runtime.Resource.
func (Varsel) IDFieldNames() []string { return VarselIDFieldNames }

// VarselRelations is the runtime metadata for Varsel's relations
// (own and inherited, flattened).
var VarselRelations = []runtime.Relation{
	{
		Name:         "faggruppemedlemskap",
		Target:       "utdanning-timeplan:Faggruppemedlemskap",
		Multiplicity: "1",
		Bidirectional: &runtime.Bidirectional{
			IsSource:    true,
			InverseName: "varsel",
		},
	},
	{
		Name:         "karakteransvarlig",
		Target:       "utdanning-elev:Undervisningsforhold",
		Multiplicity: "0..1",
	},
	{
		Name:         "type",
		Target:       "utdanning-kodeverk:Varseltype",
		Multiplicity: "0..1",
	},
	{
		Name:         "utsteder",
		Target:       "utdanning-elev:Skoleressurs",
		Multiplicity: "0..1",
	},
}

// Relations satisfies runtime.Resource.
func (Varsel) Relations() []runtime.Relation { return VarselRelations }

func init() {
	runtime.Register("utdanning-elev:Varsel", func() runtime.Resource { return &Varsel{} })
}
