// Code generated by fint-model. DO NOT EDIT.
//
// Source: metamodel.json
//
// Package manifest enumerates every component and type in the FINT
// model so consumers can iterate the catalog without importing the
// per-resource packages. The list is sorted by component name (then
// type name) so output stays diff-stable across regenerations.
//
// TypeInfo.Path is the REST URL fragment for hovedklasse types — the
// only stereotype that's REST-exposed. Non-hovedklasse types carry an
// empty Path; consumers filter by Stereotype to skip them when fetching.
package manifest

// ComponentInfo describes a single FINT component (e.g. "utdanning-elev")
// and the types it owns.
type ComponentInfo struct {
	Name  string
	Path  []string
	Types []TypeInfo
}

// TypeInfo describes a single type within a component. Key is the
// "component:Name" string accepted by runtime.New from the runtime
// package.
type TypeInfo struct {
	Key        string
	Name       string
	Path       string
	Stereotype string
}

// Components is the full sorted list of every component in the model.
var Components = []ComponentInfo{
	{
		Name: "administrasjon-fullmakt",
		Path: []string{"Administrasjon", "Fullmakt"},
		Types: []TypeInfo{
			{Key: "administrasjon-fullmakt:Fullmakt", Name: "Fullmakt", Path: "administrasjon/fullmakt/fullmakt", Stereotype: "hovedklasse"},
			{Key: "administrasjon-fullmakt:Rolle", Name: "Rolle", Path: "administrasjon/fullmakt/rolle", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "administrasjon-kodeverk",
		Path: []string{"Administrasjon", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "administrasjon-kodeverk:Aktivitet", Name: "Aktivitet", Path: "administrasjon/kodeverk/aktivitet", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Anlegg", Name: "Anlegg", Path: "administrasjon/kodeverk/anlegg", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Ansvar", Name: "Ansvar", Path: "administrasjon/kodeverk/ansvar", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Arbeidsforholdstype", Name: "Arbeidsforholdstype", Path: "administrasjon/kodeverk/arbeidsforholdstype", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Art", Name: "Art", Path: "administrasjon/kodeverk/art", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Diverse", Name: "Diverse", Path: "administrasjon/kodeverk/diverse", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Formal", Name: "Formal", Path: "administrasjon/kodeverk/formal", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Fravarsgrunn", Name: "Fravarsgrunn", Path: "administrasjon/kodeverk/fravarsgrunn", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Fravarstype", Name: "Fravarstype", Path: "administrasjon/kodeverk/fravarstype", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Funksjon", Name: "Funksjon", Path: "administrasjon/kodeverk/funksjon", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Kontodimensjon", Name: "Kontodimensjon", Path: "", Stereotype: "abstrakt"},
			{Key: "administrasjon-kodeverk:Kontrakt", Name: "Kontrakt", Path: "administrasjon/kodeverk/kontrakt", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Lonnsart", Name: "Lonnsart", Path: "administrasjon/kodeverk/lonnsart", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Lopenummer", Name: "Lopenummer", Path: "administrasjon/kodeverk/lopenummer", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Objekt", Name: "Objekt", Path: "administrasjon/kodeverk/objekt", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Organisasjonstype", Name: "Organisasjonstype", Path: "administrasjon/kodeverk/organisasjonstype", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Personalressurskategori", Name: "Personalressurskategori", Path: "administrasjon/kodeverk/personalressurskategori", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Prosjekt", Name: "Prosjekt", Path: "administrasjon/kodeverk/prosjekt", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Prosjektart", Name: "Prosjektart", Path: "administrasjon/kodeverk/prosjektart", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Ramme", Name: "Ramme", Path: "administrasjon/kodeverk/ramme", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Stillingskode", Name: "Stillingskode", Path: "administrasjon/kodeverk/stillingskode", Stereotype: "hovedklasse"},
			{Key: "administrasjon-kodeverk:Uketimetall", Name: "Uketimetall", Path: "administrasjon/kodeverk/uketimetall", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "administrasjon-kompleksedatatyper",
		Path: []string{"Administrasjon", "Kompleksedatatyper"},
		Types: []TypeInfo{
			{Key: "administrasjon-kompleksedatatyper:Kontostreng", Name: "Kontostreng", Path: "", Stereotype: "datatype"},
		},
	},
	{
		Name: "administrasjon-organisasjon",
		Path: []string{"Administrasjon", "Organisasjon"},
		Types: []TypeInfo{
			{Key: "administrasjon-organisasjon:Arbeidslokasjon", Name: "Arbeidslokasjon", Path: "administrasjon/organisasjon/arbeidslokasjon", Stereotype: "hovedklasse"},
			{Key: "administrasjon-organisasjon:Organisasjonselement", Name: "Organisasjonselement", Path: "administrasjon/organisasjon/organisasjonselement", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "administrasjon-personal",
		Path: []string{"Administrasjon", "Personal"},
		Types: []TypeInfo{
			{Key: "administrasjon-personal:Arbeidsforhold", Name: "Arbeidsforhold", Path: "administrasjon/personal/arbeidsforhold", Stereotype: "hovedklasse"},
			{Key: "administrasjon-personal:Fastlonn", Name: "Fastlonn", Path: "administrasjon/personal/fastlonn", Stereotype: "hovedklasse"},
			{Key: "administrasjon-personal:Fasttillegg", Name: "Fasttillegg", Path: "administrasjon/personal/fasttillegg", Stereotype: "hovedklasse"},
			{Key: "administrasjon-personal:Fravar", Name: "Fravar", Path: "administrasjon/personal/fravar", Stereotype: "hovedklasse"},
			{Key: "administrasjon-personal:Lonn", Name: "Lonn", Path: "", Stereotype: "abstrakt"},
			{Key: "administrasjon-personal:Personalressurs", Name: "Personalressurs", Path: "administrasjon/personal/personalressurs", Stereotype: "hovedklasse"},
			{Key: "administrasjon-personal:Variabellonn", Name: "Variabellonn", Path: "administrasjon/personal/variabellonn", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "arkiv-kodeverk",
		Path: []string{"Arkiv", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "arkiv-kodeverk:DokumentStatus", Name: "DokumentStatus", Path: "arkiv/kodeverk/dokumentstatus", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:DokumentType", Name: "DokumentType", Path: "arkiv/kodeverk/dokumenttype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Format", Name: "Format", Path: "arkiv/kodeverk/format", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:JournalStatus", Name: "JournalStatus", Path: "arkiv/kodeverk/journalstatus", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:JournalpostType", Name: "JournalpostType", Path: "arkiv/kodeverk/journalposttype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Klassifikasjonstype", Name: "Klassifikasjonstype", Path: "arkiv/kodeverk/klassifikasjonstype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:KorrespondansepartType", Name: "KorrespondansepartType", Path: "arkiv/kodeverk/korrespondanseparttype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Merknadstype", Name: "Merknadstype", Path: "arkiv/kodeverk/merknadstype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:PartRolle", Name: "PartRolle", Path: "arkiv/kodeverk/partrolle", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Rolle", Name: "Rolle", Path: "arkiv/kodeverk/rolle", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Saksmappetype", Name: "Saksmappetype", Path: "arkiv/kodeverk/saksmappetype", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Saksstatus", Name: "Saksstatus", Path: "arkiv/kodeverk/saksstatus", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Skjermingshjemmel", Name: "Skjermingshjemmel", Path: "arkiv/kodeverk/skjermingshjemmel", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Tilgangsgruppe", Name: "Tilgangsgruppe", Path: "arkiv/kodeverk/tilgangsgruppe", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Tilgangsrestriksjon", Name: "Tilgangsrestriksjon", Path: "arkiv/kodeverk/tilgangsrestriksjon", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:TilknyttetRegistreringSom", Name: "TilknyttetRegistreringSom", Path: "arkiv/kodeverk/tilknyttetregistreringsom", Stereotype: "hovedklasse"},
			{Key: "arkiv-kodeverk:Variantformat", Name: "Variantformat", Path: "arkiv/kodeverk/variantformat", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "arkiv-kulturminnevern",
		Path: []string{"Arkiv", "Kulturminnevern"},
		Types: []TypeInfo{
			{Key: "arkiv-kulturminnevern:DispensasjonAutomatiskFredaKulturminne", Name: "DispensasjonAutomatiskFredaKulturminne", Path: "arkiv/kulturminnevern/dispensasjonautomatiskfredakulturminne", Stereotype: "hovedklasse"},
			{Key: "arkiv-kulturminnevern:TilskuddFartoy", Name: "TilskuddFartoy", Path: "arkiv/kulturminnevern/tilskuddfartoy", Stereotype: "hovedklasse"},
			{Key: "arkiv-kulturminnevern:TilskuddFredaBygningPrivatEie", Name: "TilskuddFredaBygningPrivatEie", Path: "arkiv/kulturminnevern/tilskuddfredabygningprivateie", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "arkiv-noark",
		Path: []string{"Arkiv", "Noark"},
		Types: []TypeInfo{
			{Key: "arkiv-noark:AdministrativEnhet", Name: "AdministrativEnhet", Path: "arkiv/noark/administrativenhet", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Arkivdel", Name: "Arkivdel", Path: "arkiv/noark/arkivdel", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Arkivressurs", Name: "Arkivressurs", Path: "arkiv/noark/arkivressurs", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Autorisasjon", Name: "Autorisasjon", Path: "arkiv/noark/autorisasjon", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Avskrivning", Name: "Avskrivning", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Dokumentbeskrivelse", Name: "Dokumentbeskrivelse", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Dokumentfil", Name: "Dokumentfil", Path: "arkiv/noark/dokumentfil", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Dokumentobjekt", Name: "Dokumentobjekt", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Journalpost", Name: "Journalpost", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Klasse", Name: "Klasse", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Klassifikasjonssystem", Name: "Klassifikasjonssystem", Path: "arkiv/noark/klassifikasjonssystem", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Korrespondansepart", Name: "Korrespondansepart", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Mappe", Name: "Mappe", Path: "", Stereotype: "abstrakt"},
			{Key: "arkiv-noark:Merknad", Name: "Merknad", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Part", Name: "Part", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Registrering", Name: "Registrering", Path: "", Stereotype: "abstrakt"},
			{Key: "arkiv-noark:Sak", Name: "Sak", Path: "arkiv/noark/sak", Stereotype: "hovedklasse"},
			{Key: "arkiv-noark:Saksmappe", Name: "Saksmappe", Path: "", Stereotype: "abstrakt"},
			{Key: "arkiv-noark:Skjerming", Name: "Skjerming", Path: "", Stereotype: "datatype"},
			{Key: "arkiv-noark:Tilgang", Name: "Tilgang", Path: "arkiv/noark/tilgang", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "arkiv-personal",
		Path: []string{"Arkiv", "Personal"},
		Types: []TypeInfo{
			{Key: "arkiv-personal:Personalmappe", Name: "Personalmappe", Path: "arkiv/personal/personalmappe", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "arkiv-samferdsel",
		Path: []string{"Arkiv", "Samferdsel"},
		Types: []TypeInfo{
			{Key: "arkiv-samferdsel:SoknadDrosjeloyve", Name: "SoknadDrosjeloyve", Path: "arkiv/samferdsel/soknaddrosjeloyve", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "felles",
		Path: []string{"Felles"},
		Types: []TypeInfo{
			{Key: "felles:Kontaktperson", Name: "Kontaktperson", Path: "felles/kontaktperson", Stereotype: "hovedklasse"},
			{Key: "felles:Person", Name: "Person", Path: "felles/person", Stereotype: "hovedklasse"},
			{Key: "felles:Virksomhet", Name: "Virksomhet", Path: "felles/virksomhet", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "felles-basisklasser",
		Path: []string{"Felles", "Basisklasser"},
		Types: []TypeInfo{
			{Key: "felles-basisklasser:Aktor", Name: "Aktor", Path: "", Stereotype: "abstrakt"},
			{Key: "felles-basisklasser:Begrep", Name: "Begrep", Path: "", Stereotype: "abstrakt"},
			{Key: "felles-basisklasser:Enhet", Name: "Enhet", Path: "", Stereotype: "abstrakt"},
		},
	},
	{
		Name: "felles-kodeverk",
		Path: []string{"Felles", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "felles-kodeverk:Fylke", Name: "Fylke", Path: "felles/kodeverk/fylke", Stereotype: "hovedklasse"},
			{Key: "felles-kodeverk:Kommune", Name: "Kommune", Path: "felles/kodeverk/kommune", Stereotype: "hovedklasse"},
			{Key: "felles-kodeverk:Valuta", Name: "Valuta", Path: "felles/kodeverk/valuta", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "felles-kodeverk-iso",
		Path: []string{"Felles", "Kodeverk", "Iso"},
		Types: []TypeInfo{
			{Key: "felles-kodeverk-iso:Kjonn", Name: "Kjonn", Path: "felles/kodeverk/iso/kjonn", Stereotype: "hovedklasse"},
			{Key: "felles-kodeverk-iso:Landkode", Name: "Landkode", Path: "felles/kodeverk/iso/landkode", Stereotype: "hovedklasse"},
			{Key: "felles-kodeverk-iso:Sprak", Name: "Sprak", Path: "felles/kodeverk/iso/sprak", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "felles-kompleksedatatyper",
		Path: []string{"Felles", "Kompleksedatatyper"},
		Types: []TypeInfo{
			{Key: "felles-kompleksedatatyper:Adresse", Name: "Adresse", Path: "", Stereotype: "datatype"},
			{Key: "felles-kompleksedatatyper:Identifikator", Name: "Identifikator", Path: "", Stereotype: "datatype"},
			{Key: "felles-kompleksedatatyper:Kontaktinformasjon", Name: "Kontaktinformasjon", Path: "", Stereotype: "datatype"},
			{Key: "felles-kompleksedatatyper:Matrikkelnummer", Name: "Matrikkelnummer", Path: "", Stereotype: "datatype"},
			{Key: "felles-kompleksedatatyper:Periode", Name: "Periode", Path: "", Stereotype: "datatype"},
			{Key: "felles-kompleksedatatyper:Personnavn", Name: "Personnavn", Path: "", Stereotype: "datatype"},
		},
	},
	{
		Name: "okonomi-faktura",
		Path: []string{"Okonomi", "Faktura"},
		Types: []TypeInfo{
			{Key: "okonomi-faktura:Faktura", Name: "Faktura", Path: "okonomi/faktura/faktura", Stereotype: "hovedklasse"},
			{Key: "okonomi-faktura:Fakturagrunnlag", Name: "Fakturagrunnlag", Path: "okonomi/faktura/fakturagrunnlag", Stereotype: "hovedklasse"},
			{Key: "okonomi-faktura:Fakturalinje", Name: "Fakturalinje", Path: "", Stereotype: "datatype"},
			{Key: "okonomi-faktura:Fakturamottaker", Name: "Fakturamottaker", Path: "", Stereotype: "datatype"},
			{Key: "okonomi-faktura:Fakturautsteder", Name: "Fakturautsteder", Path: "okonomi/faktura/fakturautsteder", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "okonomi-kodeverk",
		Path: []string{"Okonomi", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "okonomi-kodeverk:Merverdiavgift", Name: "Merverdiavgift", Path: "okonomi/kodeverk/merverdiavgift", Stereotype: "hovedklasse"},
			{Key: "okonomi-kodeverk:Vare", Name: "Vare", Path: "okonomi/kodeverk/vare", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "okonomi-regnskap",
		Path: []string{"Okonomi", "Regnskap"},
		Types: []TypeInfo{
			{Key: "okonomi-regnskap:Bilag", Name: "Bilag", Path: "", Stereotype: "datatype"},
			{Key: "okonomi-regnskap:Leverandor", Name: "Leverandor", Path: "okonomi/regnskap/leverandor", Stereotype: "hovedklasse"},
			{Key: "okonomi-regnskap:Leverandorgruppe", Name: "Leverandorgruppe", Path: "okonomi/regnskap/leverandorgruppe", Stereotype: "hovedklasse"},
			{Key: "okonomi-regnskap:Postering", Name: "Postering", Path: "okonomi/regnskap/postering", Stereotype: "hovedklasse"},
			{Key: "okonomi-regnskap:Transaksjon", Name: "Transaksjon", Path: "okonomi/regnskap/transaksjon", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "personvern-kodeverk",
		Path: []string{"Personvern", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "personvern-kodeverk:Behandlingsgrunnlag", Name: "Behandlingsgrunnlag", Path: "personvern/kodeverk/behandlingsgrunnlag", Stereotype: "hovedklasse"},
			{Key: "personvern-kodeverk:Personopplysning", Name: "Personopplysning", Path: "personvern/kodeverk/personopplysning", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "personvern-samtykke",
		Path: []string{"Personvern", "Samtykke"},
		Types: []TypeInfo{
			{Key: "personvern-samtykke:Behandling", Name: "Behandling", Path: "personvern/samtykke/behandling", Stereotype: "hovedklasse"},
			{Key: "personvern-samtykke:Samtykke", Name: "Samtykke", Path: "personvern/samtykke/samtykke", Stereotype: "hovedklasse"},
			{Key: "personvern-samtykke:Tjeneste", Name: "Tjeneste", Path: "personvern/samtykke/tjeneste", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "ressurs-datautstyr",
		Path: []string{"Ressurs", "Datautstyr"},
		Types: []TypeInfo{
			{Key: "ressurs-datautstyr:DigitalEnhet", Name: "DigitalEnhet", Path: "ressurs/datautstyr/digitalenhet", Stereotype: "hovedklasse"},
			{Key: "ressurs-datautstyr:Enhetsgruppe", Name: "Enhetsgruppe", Path: "ressurs/datautstyr/enhetsgruppe", Stereotype: "hovedklasse"},
			{Key: "ressurs-datautstyr:Enhetsgruppemedlemskap", Name: "Enhetsgruppemedlemskap", Path: "ressurs/datautstyr/enhetsgruppemedlemskap", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "ressurs-eiendel",
		Path: []string{"Ressurs", "Eiendel"},
		Types: []TypeInfo{
			{Key: "ressurs-eiendel:Applikasjon", Name: "Applikasjon", Path: "ressurs/eiendel/applikasjon", Stereotype: "hovedklasse"},
			{Key: "ressurs-eiendel:Applikasjonsressurs", Name: "Applikasjonsressurs", Path: "ressurs/eiendel/applikasjonsressurs", Stereotype: "hovedklasse"},
			{Key: "ressurs-eiendel:Applikasjonsressurstilgjengelighet", Name: "Applikasjonsressurstilgjengelighet", Path: "ressurs/eiendel/applikasjonsressurstilgjengelighet", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "ressurs-kodeverk",
		Path: []string{"Ressurs", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "ressurs-kodeverk:Applikasjonskategori", Name: "Applikasjonskategori", Path: "ressurs/kodeverk/applikasjonskategori", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Brukertype", Name: "Brukertype", Path: "ressurs/kodeverk/brukertype", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Enhetstype", Name: "Enhetstype", Path: "ressurs/kodeverk/enhetstype", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Handhevingstype", Name: "Handhevingstype", Path: "ressurs/kodeverk/handhevingstype", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Lisensmodell", Name: "Lisensmodell", Path: "ressurs/kodeverk/lisensmodell", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Plattform", Name: "Plattform", Path: "ressurs/kodeverk/plattform", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Produsent", Name: "Produsent", Path: "ressurs/kodeverk/produsent", Stereotype: "hovedklasse"},
			{Key: "ressurs-kodeverk:Status", Name: "Status", Path: "ressurs/kodeverk/status", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "ressurs-tilgang",
		Path: []string{"Ressurs", "Tilgang"},
		Types: []TypeInfo{
			{Key: "ressurs-tilgang:Identitet", Name: "Identitet", Path: "ressurs/tilgang/identitet", Stereotype: "hovedklasse"},
			{Key: "ressurs-tilgang:Rettighet", Name: "Rettighet", Path: "ressurs/tilgang/rettighet", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-basisklasser",
		Path: []string{"Utdanning", "Basisklasser"},
		Types: []TypeInfo{
			{Key: "utdanning-basisklasser:Gruppe", Name: "Gruppe", Path: "", Stereotype: "abstrakt"},
			{Key: "utdanning-basisklasser:Gruppemedlemskap", Name: "Gruppemedlemskap", Path: "", Stereotype: "abstrakt"},
			{Key: "utdanning-basisklasser:Utdanningsforhold", Name: "Utdanningsforhold", Path: "", Stereotype: "abstrakt"},
		},
	},
	{
		Name: "utdanning-elev",
		Path: []string{"Utdanning", "Elev"},
		Types: []TypeInfo{
			{Key: "utdanning-elev:Elev", Name: "Elev", Path: "utdanning/elev/elev", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Elevforhold", Name: "Elevforhold", Path: "utdanning/elev/elevforhold", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Elevtilrettelegging", Name: "Elevtilrettelegging", Path: "utdanning/elev/elevtilrettelegging", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Klasse", Name: "Klasse", Path: "utdanning/elev/klasse", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Klassemedlemskap", Name: "Klassemedlemskap", Path: "utdanning/elev/klassemedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Kontaktlarergruppe", Name: "Kontaktlarergruppe", Path: "utdanning/elev/kontaktlarergruppe", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Kontaktlarergruppemedlemskap", Name: "Kontaktlarergruppemedlemskap", Path: "utdanning/elev/kontaktlarergruppemedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Persongruppe", Name: "Persongruppe", Path: "utdanning/elev/persongruppe", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Persongruppemedlemskap", Name: "Persongruppemedlemskap", Path: "utdanning/elev/persongruppemedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Skoleressurs", Name: "Skoleressurs", Path: "utdanning/elev/skoleressurs", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Undervisningsforhold", Name: "Undervisningsforhold", Path: "utdanning/elev/undervisningsforhold", Stereotype: "hovedklasse"},
			{Key: "utdanning-elev:Varsel", Name: "Varsel", Path: "utdanning/elev/varsel", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-kodeverk",
		Path: []string{"Utdanning", "Kodeverk"},
		Types: []TypeInfo{
			{Key: "utdanning-kodeverk:Avbruddsarsak", Name: "Avbruddsarsak", Path: "utdanning/kodeverk/avbruddsarsak", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Betalingsstatus", Name: "Betalingsstatus", Path: "utdanning/kodeverk/betalingsstatus", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Bevistype", Name: "Bevistype", Path: "utdanning/kodeverk/bevistype", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Brevtype", Name: "Brevtype", Path: "utdanning/kodeverk/brevtype", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Eksamensform", Name: "Eksamensform", Path: "utdanning/kodeverk/eksamensform", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Elevkategori", Name: "Elevkategori", Path: "utdanning/kodeverk/elevkategori", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Fagmerknad", Name: "Fagmerknad", Path: "utdanning/kodeverk/fagmerknad", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Fagstatus", Name: "Fagstatus", Path: "utdanning/kodeverk/fagstatus", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Fravarstype", Name: "Fravarstype", Path: "utdanning/kodeverk/fravarstype", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Fullfortkode", Name: "Fullfortkode", Path: "utdanning/kodeverk/fullfortkode", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Grepreferanse", Name: "Grepreferanse", Path: "", Stereotype: "referanse"},
			{Key: "utdanning-kodeverk:Karakterskala", Name: "Karakterskala", Path: "utdanning/kodeverk/karakterskala", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Karakterstatus", Name: "Karakterstatus", Path: "utdanning/kodeverk/karakterstatus", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:OtEnhet", Name: "OtEnhet", Path: "utdanning/kodeverk/otenhet", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:OtStatus", Name: "OtStatus", Path: "utdanning/kodeverk/otstatus", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Provestatus", Name: "Provestatus", Path: "utdanning/kodeverk/provestatus", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Skolear", Name: "Skolear", Path: "utdanning/kodeverk/skolear", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Skoleeiertype", Name: "Skoleeiertype", Path: "utdanning/kodeverk/skoleeiertype", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Termin", Name: "Termin", Path: "utdanning/kodeverk/termin", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Tilrettelegging", Name: "Tilrettelegging", Path: "utdanning/kodeverk/tilrettelegging", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Varseltype", Name: "Varseltype", Path: "utdanning/kodeverk/varseltype", Stereotype: "hovedklasse"},
			{Key: "utdanning-kodeverk:Vigoreferanse", Name: "Vigoreferanse", Path: "", Stereotype: "referanse"},
			{Key: "utdanning-kodeverk:Vitnemalsmerknad", Name: "Vitnemalsmerknad", Path: "utdanning/kodeverk/vitnemalsmerknad", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-larling",
		Path: []string{"Utdanning", "Larling"},
		Types: []TypeInfo{
			{Key: "utdanning-larling:AvlagtProve", Name: "AvlagtProve", Path: "utdanning/larling/avlagtprove", Stereotype: "hovedklasse"},
			{Key: "utdanning-larling:Larling", Name: "Larling", Path: "utdanning/larling/larling", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-ot",
		Path: []string{"Utdanning", "Ot"},
		Types: []TypeInfo{
			{Key: "utdanning-ot:OtUngdom", Name: "OtUngdom", Path: "utdanning/ot/otungdom", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-timeplan",
		Path: []string{"Utdanning", "Timeplan"},
		Types: []TypeInfo{
			{Key: "utdanning-timeplan:Eksamen", Name: "Eksamen", Path: "utdanning/timeplan/eksamen", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Fag", Name: "Fag", Path: "utdanning/timeplan/fag", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Faggruppe", Name: "Faggruppe", Path: "utdanning/timeplan/faggruppe", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Faggruppemedlemskap", Name: "Faggruppemedlemskap", Path: "utdanning/timeplan/faggruppemedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Rom", Name: "Rom", Path: "utdanning/timeplan/rom", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Time", Name: "Time", Path: "utdanning/timeplan/time", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Undervisningsgruppe", Name: "Undervisningsgruppe", Path: "utdanning/timeplan/undervisningsgruppe", Stereotype: "hovedklasse"},
			{Key: "utdanning-timeplan:Undervisningsgruppemedlemskap", Name: "Undervisningsgruppemedlemskap", Path: "utdanning/timeplan/undervisningsgruppemedlemskap", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-utdanningsprogram",
		Path: []string{"Utdanning", "Utdanningsprogram"},
		Types: []TypeInfo{
			{Key: "utdanning-utdanningsprogram:Arstrinn", Name: "Arstrinn", Path: "utdanning/utdanningsprogram/arstrinn", Stereotype: "hovedklasse"},
			{Key: "utdanning-utdanningsprogram:Programomrade", Name: "Programomrade", Path: "utdanning/utdanningsprogram/programomrade", Stereotype: "hovedklasse"},
			{Key: "utdanning-utdanningsprogram:Programomrademedlemskap", Name: "Programomrademedlemskap", Path: "utdanning/utdanningsprogram/programomrademedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-utdanningsprogram:Skole", Name: "Skole", Path: "utdanning/utdanningsprogram/skole", Stereotype: "hovedklasse"},
			{Key: "utdanning-utdanningsprogram:Utdanningsprogram", Name: "Utdanningsprogram", Path: "utdanning/utdanningsprogram/utdanningsprogram", Stereotype: "hovedklasse"},
		},
	},
	{
		Name: "utdanning-vurdering",
		Path: []string{"Utdanning", "Vurdering"},
		Types: []TypeInfo{
			{Key: "utdanning-vurdering:Anmerkninger", Name: "Anmerkninger", Path: "utdanning/vurdering/anmerkninger", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Eksamensgruppe", Name: "Eksamensgruppe", Path: "utdanning/vurdering/eksamensgruppe", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Eksamensgruppemedlemskap", Name: "Eksamensgruppemedlemskap", Path: "utdanning/vurdering/eksamensgruppemedlemskap", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Eksamensvurdering", Name: "Eksamensvurdering", Path: "utdanning/vurdering/eksamensvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Elevfravar", Name: "Elevfravar", Path: "utdanning/vurdering/elevfravar", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Elevvurdering", Name: "Elevvurdering", Path: "utdanning/vurdering/elevvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Fagvurdering", Name: "Fagvurdering", Path: "", Stereotype: "abstrakt"},
			{Key: "utdanning-vurdering:Fravarsoversikt", Name: "Fravarsoversikt", Path: "utdanning/vurdering/fravarsoversikt", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Fravarsprosent", Name: "Fravarsprosent", Path: "", Stereotype: "datatype"},
			{Key: "utdanning-vurdering:Fravarsregistrering", Name: "Fravarsregistrering", Path: "utdanning/vurdering/fravarsregistrering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Halvarsfagvurdering", Name: "Halvarsfagvurdering", Path: "utdanning/vurdering/halvarsfagvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Halvarsordensvurdering", Name: "Halvarsordensvurdering", Path: "utdanning/vurdering/halvarsordensvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Karakterhistorie", Name: "Karakterhistorie", Path: "utdanning/vurdering/karakterhistorie", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Karakterverdi", Name: "Karakterverdi", Path: "utdanning/vurdering/karakterverdi", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Ordensvurdering", Name: "Ordensvurdering", Path: "", Stereotype: "abstrakt"},
			{Key: "utdanning-vurdering:Sensor", Name: "Sensor", Path: "utdanning/vurdering/sensor", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Sluttfagvurdering", Name: "Sluttfagvurdering", Path: "utdanning/vurdering/sluttfagvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Sluttordensvurdering", Name: "Sluttordensvurdering", Path: "utdanning/vurdering/sluttordensvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Underveisfagvurdering", Name: "Underveisfagvurdering", Path: "utdanning/vurdering/underveisfagvurdering", Stereotype: "hovedklasse"},
			{Key: "utdanning-vurdering:Underveisordensvurdering", Name: "Underveisordensvurdering", Path: "utdanning/vurdering/underveisordensvurdering", Stereotype: "hovedklasse"},
		},
	},
}
